### ISSUE TITLE
Enhance UI for creating shifts as an admin

### ISSUE THREAD

**Issue by willingc** [systers/vms#100]
When creating a shift (http://localhost:8001/shift/create/1), the system should pre-populate the fields with database information already know about the event like venue, location, date, etc. to minimize typing by admin. The admin should be able to override the pre-populated information.

<img width="578" alt="screen shot 2015-07-26 at 5 47 25 pm" src="https://cloud.githubusercontent.com/assets/2680980/8896902/03cdf85c-33bf-11e5-9798-3c441d54aefc.png">

**Comment by vubo** [comment]
@willingc I really like your idea: https://github.com/systers/vms/pull/120 :sparkles:
