### ISSUE TITLE
Volunteer report enhancement

### ISSUE THREAD

**Issue by vubo** [systers/vms#102]
Improve report for volunteers:

- [x] Add a data range instead of the date

![image](https://cloud.githubusercontent.com/assets/7673323/8973231/e868d4c8-3662-11e5-8ab6-77917c3542e3.png)

cc @rosariorobinson

**Comment by tapasweni-pathak** [comment]
Data range as in the options for the user to generate report right?

**Comment by vubo** [comment]
Yes. A volunteer can see her/his completed shifts (for this dates).

**Comment by tapasweni-pathak** [comment]
Okay. Cool. :+1:

**Comment by vubo** [comment]
O, yes, this is a mistake. Thank you!

**Comment by tapasweni-pathak** [comment]
Cool. Merged it, so closing this issue.
