### ISSUE TITLE
Enhancement: Consider using coverage and Travis for monitoring testing and code health

### ISSUE THREAD

**Issue by willingc** [systers/vms#11]
Many Django projects use the coverage project to measure test coverage and display the resulting percentage in the GitHub repo. Projects also frequently use Travis for continuous integration to build, test, and report on the project. Travis integration with GitHub provides a nice widget to display current build status.

**Comment by jayesh92** [comment]
@willingc I'm working to enable CI for this repo. Currenlty, I've integrated with travis on my fork. Will merge with this soon.

**Comment by willingc** [comment]
@jayesh92 That's great. Thanks for the update :smile:

**Comment by tapasweni-pathak** [comment]
@jayesh92 Do you have any updates for this?

**Comment by tapasweni-pathak** [comment]
We have #140 for this. So closing this. It will soon be fixed by pull request #332. :smile:
