### ISSUE TITLE
Coordinate with Portal group re: moving to Django 1.8 LTS

### ISSUE THREAD

**Issue by willingc** [systers/vms#12]
Django 1.8 is a long term supported release (LTS). It would be useful to upgrade the code bases to Django 1.8 since it will have longer term support than the current version used. https://www.djangoproject.com/download/  for details.

**Comment by willingc** [comment]
@rosariorobinson @tapasweni-pathak @ana-balica @vubo @jayesh92 Rose, I'm wondering if it would make sense to use Python 3 which the Systers Portal project uses? Thoughts anyone?

**Comment by Nerdylicious** [comment]
Hi Carol,

Rose wanted VMS to be integrated with Portal eventually, so I think it would make sense to port to Python 3. It would be better to port earlier than later so there's less code to port over.

**Comment by willingc** [comment]
@Nerdylicious Thanks for the input. I agree that sooner is better than later.

**Comment by tapasweni-pathak** [comment]
Hi Carol,

I too believe, we should port to Python 3 early, as later more code fixing and porting will be required.

**Comment by willingc** [comment]
@tapasweni-pathak :+1:

**Comment by vubo** [comment]
@willingc thank you! I ported all code to Python 3 and I'm using Python 3.4 and Django 1.8.3 now.

**Comment by tapasweni-pathak** [comment]
Awesome @vubo. :smile:  
Closing this then.
