### ISSUE TITLE
Plan and release v0.3.0

### ISSUE THREAD

**Issue by willingc** [systers/vms#123]
@vubo Well, the time has come to set up the release of v0.3.0. :tada: This should be released before the presentation to @rosariorobinson @tapasweni-pathak. 

Here's a general plan on setting up a release:
1. Create a milestone for `Release v0.3.0` and set a date for the milestone.
2. Tag any issues that should be completed with prior to `Release v0.3.0`.
3. Work on any open issues for the release.
4. When you hit the milestone release date or complete the open issues, please let us know. We will then create a tag and release for 0.3.0.

After the presentation, any bug fixes would push the release to 0.3.1. If new features are added later, we would move the release to 0.4.0.

**Comment by vubo** [comment]
@willingc I created the milestone https://github.com/systers/vms/milestones/Release%20v0.3.0

**Comment by willingc** [comment]
@vubo, @tapasweni-pathak, @rosariorobinson It is with great pleasure that I am officially releasing version 0.3.0 of the VMS project. :tada: :star2: :balloon: :joy: :smile: :trophy: :tada:

Today, @vubo presented this release to GSoC mentors. Thank you @vubo for your contributions, work ethic, and excellent teamwork.

I'm closing this issue!!! Thanks everyone for support of this project.

@vubo Any additional tweaks that you wish to make during the remainder of the GSoC period would go in release 0.3.1 unless it is a major feature addition which we would then bump to 0.4.0 ;)

**Comment by Nerdylicious** [comment]
@vubo Congratulations on your contributions! You did a great job taking over the project from our contributions last year and early this year. I hope you'll stick around!

A big thank you to @willingc and @tapasweni-pathak as well. I'm going to GHC this year so maybe I'll see some of you there!

**Comment by willingc** [comment]
@Nerdylicious If you have time at GHC, and this offer goes for any VMS contributor at GHC, I would love to share a meal with you and hear about what you have been working on. :) And thank you for all of your continued help on VMS and proving last summer that it was worth continuing the project :dancer: :bouquet:

**Comment by tapasweni-pathak** [comment]
Wohoo. :boom: :smile: :sparkling_heart:

Thanks @vubo for making it that awesome. 

@willingc It was great being a co-mentor with you. I learnt many things. :smile: :bouquet: 

Thanks @Nerdylicious @rosariorobinson for the issues, help and everything. :+1: :smile:

I'm gonna stick around for sure. :dancer:

**Comment by Nerdylicious** [comment]
@willingc @tapasweni-pathak @vubo That sounds great Carol! @rosariorobinson mentioned during my demo that there will be a Systers lunch during the conference so I'll see you there! I'm also attending PyCon next year in Portland (I got to go to PyCon this year in Montreal and I saw your talk but I didn't get a chance to talk to you) and possibly attending Django: Under The Hood in Amsterdam later this year. Hopefully I'll see some of you at these events.

**Comment by vubo** [comment]
I'm so happy to see this issue :relaxed:

Thank you @tapasweni-pathak and @willingc! I really appreciate all the help and advice you’ve given me, it’s been a lot of help. @willingc thank you for coming yesterday, I hope your father is doing well.

@Nerdylicious thank you for answering all my questions :smile: I'm gonna stick around too.
