### ISSUE TITLE
Cleanup items

### ISSUE THREAD

**Issue by willingc** [systers/vms#124]
@vubo, I'm doing a review of some of the code base this weekend. I will leave small items here and larger ones (if any) in separate issues
-  [ ] [~~missing closing tag~~](https://github.com/systers/vms/blob/develop/vms/home/templates/home/home.html#L11)
-  [ ] [unneeded import](https://github.com/systers/vms/blob/develop/vms/home/views.py#L2)
-  [ ] Consider refactor imports in `administrator/forms.py` 
  
  ```
     from django import forms
  
     from .models import Administrator
  
     class AdministratorForm(forms.ModelForm):
  ```

**Comment by vubo** [comment]
@willingc thank you!

- [missing closing tag](https://github.com/systers/vms/blob/develop/vms/home/templates/home/home.html#L11) - what tag do you mean? I have not found...

- `administrator/forms.py` produces an error without `from django.forms import ModelForm`

![image](https://cloud.githubusercontent.com/assets/7673323/9314976/966a1a78-452c-11e5-9e72-4d146d73b21e.png)

**Comment by willingc** [comment]
@vubo Missing closing tag was my error :) I didn't see the closing tag before the double braces. Sorry!

**Comment by willingc** [comment]
@vubo Clearing the release milestone on these.

**Comment by tapasweni-pathak** [comment]
@willingc Are we done with this, or they are still left?
