### ISSUE TITLE
Android 5.0 test - menu is not displayed

### ISSUE THREAD

**Issue by vubo** [systers/vms#126]
I tested the VMS on my Android phone. It looks awesome, but I don't see the menu. We use a CSS framework Bootstrap Lumen, so it can be a Bootstrap issue.

![image](https://cloud.githubusercontent.com/assets/7673323/9294991/cdc2c7f0-445e-11e5-9207-9ab88786bfbc.png)

![image](https://cloud.githubusercontent.com/assets/7673323/9294993/de1ce126-445e-11e5-9742-bbfc365a0480.png)

![image](https://cloud.githubusercontent.com/assets/7673323/9294994/eca5354a-445e-11e5-83d5-5b167ca23c56.png)

![image](https://cloud.githubusercontent.com/assets/7673323/9294996/f8079c0c-445e-11e5-8202-2f9ce1123d1b.png)

**Comment by willingc** [comment]
@vubo This is so awesome!!! I didn't even think of loading up on Android, but I'm so pleased that you did. Make sure that you demo this.

Check out these two projects (cookiecutter and cookiecutter-django) from the authors of Two Scoops of Django https://github.com/pydanny/cookiecutter-django Danny's template likely shows how to do the menu since it's pretty much a batteries included template.

**Comment by vubo** [comment]
@willingc thank you! :panda_face:

I found instructions on the [Bootstrap Lumen website] (https://bootswatch.com/lumen/) and fixed the code https://github.com/systers/vms/pull/127

**Comment by Nerdylicious** [comment]
@vubo great job on testing it out on a mobile device! Have you also tried it out on smaller and larger tablets?

**Comment by tapasweni-pathak** [comment]
@vubo This is awesome. Its great that you thought of testing it on Android. :+1: :dancer:

**Comment by willingc** [comment]
@vubo Super! Wonderful job. :sunrise: 

Great teamwork and support @Nerdylicious and @tapasweni-pathak. :smile:  I also wanted to share that I heard @tapasweni-pathak did a fine job teaching web scraping on PyLadies remote today. I hope you enjoyed it :tada:

**Comment by tapasweni-pathak** [comment]
I enjoyed doing it. I hope it made people to love Python, more. :smile: :high_brightness:

@willingc I would love to have suggestions on what all I can improve. :)

**Comment by vubo** [comment]
@Nerdylicious @tapasweni-pathak thank you! :octocat:

@Nerdylicious no, I have not tried. But this can be easily done with the Chrome. Stretching his window, you can simulate the screen of the tablet or phone. It is not quite correct, but possible. That's how I tested the menu.

![image](https://cloud.githubusercontent.com/assets/7673323/9301010/941ee7aa-44cb-11e5-8fe6-82eef532c175.png)
