### ISSUE TITLE
SHIFT SIGN UP list enchancement

### ISSUE THREAD

**Issue by vubo** [systers/vms#130]
In the "SHIFT SIGN UP" list show only relevant shifts: the shifts that start today or later.

![image](https://cloud.githubusercontent.com/assets/7673323/9688102/7efdcb28-532d-11e5-96b2-af3d1c8c8f8c.png)

**Comment by KokareIITP** [comment]
@vubo 
https://github.com/KokareIITP/vms/commit/83bc609c8dcab7541c463217b949468f67ecbbd5
Please review.

I made the change in service.py for shifts taking care that the particular function was used only in the required view, thus not affecting any other view.
![screenshot 35](https://cloud.githubusercontent.com/assets/9394028/11756194/4757ad8a-a07e-11e5-9164-53b3312e2427.png)
![screenshot 34](https://cloud.githubusercontent.com/assets/9394028/11756199/4dab82d8-a07e-11e5-921a-facc8a1bf644.png)

**Comment by KokareIITP** [comment]
Here is the pull request for the issue stated @tapasweni-pathak  @vubo 
https://github.com/systers/vms/pull/173
Please review.
