### ISSUE TITLE
Simplify the creating of the job

### ISSUE THREAD

**Issue by vubo** [systers/vms#131]
When we create a job for the event, we don't see the event dates. But it can be helpful. 

![image](https://cloud.githubusercontent.com/assets/7673323/9689895/58a696e2-5339-11e5-97fd-6edc2bc1824d.png)

My suggestion: show the dates of the event under the Event field.

![image](https://cloud.githubusercontent.com/assets/7673323/9691919/e19750ac-5345-11e5-9d63-9ac49be263e5.png)

**Comment by KokareIITP** [comment]
According to the link given in the installation guide, for the project to be run on local machine 
http://localhost:8001/home/#
But as the pictures above, the webpage doesn't look like that.
Is it the case that the link needs to be updated in the installation guide @tapasweni-pathak di.

**Comment by vubo** [comment]
@KokareIITP and how it looks? For this page you should be an Administrator and click "Events".

**Comment by KokareIITP** [comment]
![screenshot 10](https://cloud.githubusercontent.com/assets/9394028/10788826/00c4901e-7da0-11e5-86c4-34663fc578a0.png)
The page looks like this to me. 
Moreover, when I select the signup option I get an error saying 
"You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page."

**Comment by vubo** [comment]
@KokareIITP first you need to register as admin:
1. SIGN UP ADMIN and create an admin account
2. Now you can sign up as admin

**Comment by KokareIITP** [comment]
@vubo  As I mentioned earlier it gives an error saying
"You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page."
![screenshot 12](https://cloud.githubusercontent.com/assets/9394028/10789539/0a9aca5a-7da4-11e5-961f-98b15e1891cd.png)

**Comment by vubo** [comment]
@KokareIITP ok, I see now. Did you change vms/settings.py file here: https://github.com/systers/vms/blob/develop/vms/vms/settings.py#L64 ? You should write here your databse admin login and password.

**Comment by KokareIITP** [comment]
Thanks @vubo I got the page successfully.

**Comment by vubo** [comment]
@KokareIITP cool! Good job  :tulip: :sparkles: :+1:

**Comment by KokareIITP** [comment]
Is there a way that we can access the start date and end date of event using the event id ?

**Comment by vubo** [comment]
@KokareIITP this file https://github.com/systers/vms/blob/develop/vms/event/services.py can be useful for you. Here you can find many examples how to access an event and perhaps you need to program your function, that will return the start and end date for an event.

**Comment by varunnaganathan** [comment]
I want to work on this issue!

**Comment by KokareIITP** [comment]
I have made some changes in services.py and job\create. Please review.

**Comment by vubo** [comment]
@KokareIITP did you test the code? I don't see the dates... Could you also always provide the link to your code please?

**Comment by KokareIITP** [comment]
@Vubo . Here is the link to my edits.
https://github.com/KokareIITP/vms/commit/9fdfce2e2a046bf2d9560d7f64ad32073066d57f
Actually I did try the test cases and I know it isn't working. But I am unable to track the loop hole in the code. I am stuck now. It would be really kind of you if you could help me out.

**Comment by vubo** [comment]
@KokareIITP looks good :+1: And can you show your unit tests? What error they output?

**Comment by KokareIITP** [comment]
I also made edits in job/views.py
https://github.com/KokareIITP/vms/commit/6e1ad2e6550ca8fb6ad85edaf9a6aa0fe38a2789
and job/create.html
https://github.com/KokareIITP/vms/commit/8bb5cf624c73b6c85ff30d2b6f990e8313ddde4f

And the error which I am getting is 
![screenshot 16](https://cloud.githubusercontent.com/assets/9394028/10917255/d4287a44-8285-11e5-80df-071b50b15b22.png)
How do I resolve this ?

**Comment by vubo** [comment]
@KokareIITP you have an error in the line 58 in the view.py (see exception value string). After ```else``` you forgot a colon (```:```).

**Comment by KokareIITP** [comment]
Sorry for the last one. Made the edit.
https://github.com/KokareIITP/vms/commit/30fa01d602c05ae231b77f15d3cd3615ce051eec
Now isn't showing an error, but neither is it displaying the dates. :(

**Comment by vubo** [comment]
@KokareIITP did you program the unit tests for your functions? You can program it here: https://github.com/systers/vms/blob/develop/vms/event/tests.py and then test your functions: ```python manage.py test event``` It is simple, but then you can understand, whether these functions work.

**Comment by KokareIITP** [comment]
I added the test cases.
Here is the link 
https://github.com/KokareIITP/vms/commit/3b43b2472816b4322354a38da5c84041faa3056e
And after running python manage.py test event I get
Creating database for alias 'default' ...
..........
--------------------
Ran 6 tests in 0.685s

OK
Destroying test database for alias 'default' ...

I think maybe the issue is in the job/create.html file I sent you
KokareIITP@ 8bb5cf6

**Comment by vubo** [comment]
@KokareIITP looks good! But in your tests here:

```
self.assertEqual(get_start_date_by_event_id(e1.id), e1)
self.assertEqual(get_start_date_by_event_id(e2.id), e2)
self.assertEqual(get_start_date_by_event_id(e3.id), e3)
```

You need to compare ```get_start_date_by_event_id(e1.id)``` - date with the date. And ```e1``` is not a date. Instead of the e1 shall be the date of the e1.

**Comment by KokareIITP** [comment]
https://github.com/KokareIITP/vms/commit/f31181126269c89c8aa3a46e9528e2e675aa6536
@vubo  Made the edits. python manage.py test event gives OK.

**Comment by vubo** [comment]
@KokareIITP 
>Ran 6 tests in 0.685s

But you have 8 test functions in your tests.py file.

**Comment by KokareIITP** [comment]
@vubo 
Made necessary changes in the tests.py file
https://github.com/KokareIITP/vms/commit/6e767d705d6a7d5f654b15f2a37aa8b2dbbb1997
and made changes in functions at services.py
https://github.com/KokareIITP/vms/commit/94e42a06707fc225daef6d275991e6e717e311f4

All the 8 test functions successfully run. :)

**Comment by KokareIITP** [comment]
@vubo 
Edited the create.html and views.py file for ajax javascript to update the dates. But I am unable to track down the fault. Please help.
https://github.com/KokareIITP/vms/commit/2fb4cfc1ec3612ce8f6b6ee98e54bcd930c5ba46
https://github.com/KokareIITP/vms/commit/638c99ba0ebefd54108931a4e7e14f1152905a7f

**Comment by vubo** [comment]
@KokareIITP I was at a conference and could not answer. I will view the code and answer you in the next days!

**Comment by KokareIITP** [comment]
Sure @vubo !!!

**Comment by vubo** [comment]
@KokareIITP I reviewed your code. I think, the problem is in your ajax-code. Could you try another option? For example, javascript?

**Comment by KokareIITP** [comment]
@vubo  Since we want to flash the values of start date and end date as soon as the user selects the event, without submitting the form, I feel Ajax will help.

**Comment by KokareIITP** [comment]
@vubo  I am unable to run vagrant up. Please help with the following error.
![screenshot 17](https://cloud.githubusercontent.com/assets/9394028/11524350/1fd58d76-98f0-11e5-8a13-ada297ebd375.png)

P.S. I have Vagrant 1.7.4 and Virtual Box 5.0.10

**Comment by vubo** [comment]
@KokareIITP as I see, there is a VirtualBox problem. You can try to reinstall it and do all installation steps again: http://vms.readthedocs.org/en/latest/Installation%20Guide/

**Comment by KokareIITP** [comment]
Yes. I read about it and it shows to be a virtual box problem. I did reinstall vagrant as well as virtual box, but it didn't work. So I further moved to Virtual Box 4.3.12 version after reading some more articles over the internet.
After following the installation steps, I get the error
![screenshot 18](https://cloud.githubusercontent.com/assets/9394028/11526878/87a0356a-9903-11e5-92a2-69bce993925e.png)

**Comment by vubo** [comment]
@KokareIITP did you try this: http://stackoverflow.com/questions/23633276/vagrant-is-attempting-to-interface-with-the-ui-in-a-way-that-requires-a-tty ?

**Comment by KokareIITP** [comment]
I again tried to use the same setup as I was using earlier i.e. Vagrant 1.7.4 and Virtual Box 5.0.6. Earlier it was working perfectly, now it isn't. I found out this.
https://www.virtualbox.org/ticket/14040#comment:54
But I was wondering , since I had Windows 10 earlier as well, how come it worked earlier ?

**Comment by KokareIITP** [comment]
I have tried Vagrant 1.7.4, Vagrant 1.7.2, Virtual Box 4.3.12, Virtual Box 5.0.6, Virtual Box 5.0.10 with the 14040 fix wherever necessary. Also, I have tried many ways to debug the issue, but none of them seem to work. The conclusive things I discovered were that not all vagrant and virtual boxes are compatible, and thus the issue was occurring. I guess something with the operating system also makes a difference in it.
I am badly stuck with the same set of errors. I am still trying to figure out some or the other way to resolve this.

**Comment by vubo** [comment]
@KokareIITP I just checked my versions.

Vagrant: 1.7.2
VirtualBox: 4.3.26 r98988

And it works:
![image](https://cloud.githubusercontent.com/assets/7673323/11540408/ec9d81ba-992c-11e5-80ec-af8a22ab56b7.png)

I hope, it can help you.

**Comment by KokareIITP** [comment]
Is it Windows 10 ?

**Comment by vubo** [comment]
No, it is 8.1. What have you used before?

**Comment by KokareIITP** [comment]
Earlier too it was Windows 10. Vagrant 1.7.4 and Virtual Box 5.0.6

**Comment by vubo** [comment]
And after what it stopped working?

**Comment by KokareIITP** [comment]
I guess approximately 15 days ago:
I had Windows 10, Vagrant 1.7.4 and Virtual Box 5.0.6

I didn't make any changes, except the update by Windows 10 released recently. 2 days back when I started to begin my work, it didn't work.

**Comment by KokareIITP** [comment]
Maybe the below link 
http://www.gospelherald.com/articles/60197/20151129/windows-10-update-fixes-bug-patches-and-news-microsoft-pulled-november-update-admits-presence-of-privacy-glitch.htm
might help.

**Comment by vubo** [comment]
@KokareIITP you can just delete your last windows updates and test.

**Comment by KokareIITP** [comment]
@vubo  I deleted all the last updates and made changes in the Windows Network Connection, and after uninstalling and reinstalling here is what I get.
![screenshot 22](https://cloud.githubusercontent.com/assets/9394028/11554623/bb88ffee-99bf-11e5-89cd-eaa00f0cfaeb.png)
There is a warning but atleast the virtual machine has started.

**Comment by KokareIITP** [comment]
@vubo 
Could do it for Windows 10. Everything is running successfully. 
Thanks a lot ! :)

**Comment by vubo** [comment]
@KokareIITP glad to hear it! :thumbsup:

**Comment by smarshy** [comment]
@tapasweni-pathak This seems to be completed. I can see event dates now while creating job.
