### ISSUE TITLE
Simplify the creating of the shift

### ISSUE THREAD

**Issue by vubo** [systers/vms#132]
When we create a shift for the job, we don't see the job name and dates. My suggestion: show the job name and dates above the form.

![image](https://cloud.githubusercontent.com/assets/7673323/9695366/3530377c-5361-11e5-9533-c3de1fa0cb6e.png)

**Comment by KokareIITP** [comment]
I made changes in 
views.py for shift https://github.com/KokareIITP/vms/commit/7b4336c11d9bdfc415e161d9ca209218e13460e2
and create.html for shift https://github.com/KokareIITP/vms/commit/4202d1de6a63749641aced7c90d5512fe3cec413

Please review.

**Comment by vubo** [comment]
@KokareIITP did you test it? Does it work by you?

**Comment by KokareIITP** [comment]
Yes.

**Comment by KokareIITP** [comment]
@vubo
While I was testing it I discovered the shifts were not being saved. For that I made the edits, hope it will work now.
So here is the final views.py https://github.com/KokareIITP/vms/commit/e6f3fe9ed075e6fef7f60b1b47e5fe270fb011ee
and create.html for shifts
https://github.com/KokareIITP/vms/commit/4202d1de6a63749641aced7c90d5512fe3cec413

**Comment by vubo** [comment]
@KokareIITP I tested it, it doesn't work by me. Do I need to change only 2 files?

**Comment by KokareIITP** [comment]
Yes @vubo 
Here is the link to my shifts/views.py
https://github.com/KokareIITP/vms/blob/develop/vms/shift/views.py
Here is the link to shifts/create.html
https://github.com/KokareIITP/vms/blob/develop/vms/shift/templates/shift/create.html

I have sent the pull requests for the same:
First views.py :  https://github.com/KokareIITP/vms/commit/7b4336c11d9bdfc415e161d9ca209218e13460e2
Final views.py(Since shifts were not being saved.)
https://github.com/KokareIITP/vms/commit/e6f3fe9ed075e6fef7f60b1b47e5fe270fb011ee

create.html
https://github.com/KokareIITP/vms/commit/4202d1de6a63749641aced7c90d5512fe3cec413

And here are the recorded steps for the creating of shift : 


[Systers-Issue.pdf](https://github.com/systers/vms/files/55098/Systers-Issue.pdf)

Please let me know if it works.

**Comment by vubo** [comment]
@KokareIITP I tested it, it looks good :+1: :cherries: 

Could you do some styling please, that Job Name, Start and End Dates are in the "table" like Date, Start Time, End Time? So it looks the same. And then you can do a Pull Request. 

You don't need to do pdf-instructions, it takes a lot of time. One or two printscreens would be enough to understand, how it looks.

**Comment by KokareIITP** [comment]
Sure @vubo .
I am glad that it works. I will do that now.

**Comment by KokareIITP** [comment]
Here are the pull requests:
https://github.com/systers/vms/pull/169
https://github.com/systers/vms/pull/168

And here is how it looks:
![screenshot 28](https://cloud.githubusercontent.com/assets/9394028/11662843/ee4b5ce0-9dfe-11e5-991f-5316d52bd735.png)

**Comment by vubo** [comment]
@KokareIITP thank you, looks much better :smiley: Why did you send 2 PRs? Could you do only one? One PR for one feature. And put this printscreen also in the PR please, so anyone can see what you did.

**Comment by KokareIITP** [comment]
Done @vubo 
Here is the pull request https://github.com/systers/vms/pull/168

**Comment by vubo** [comment]
@KokareIITP thank you. I will test it one more time and then merge it. In this time you can try to merge your two commits from this PR in a one commit (hint: you can use ```rebase```).

**Comment by KokareIITP** [comment]
@vubo 
![screenshot 32](https://cloud.githubusercontent.com/assets/9394028/11737408/07f87ea0-9fff-11e5-9236-a1df28c33c3f.png)
I don't find my commits listed in this.

**Comment by vubo** [comment]
@KokareIITP you should rebase a pull request which has multiple commits and squash them into one commit. This gives a cleaner project history over time. You do not need to close this PR and create a new PR. Simply push to your same branch (you may need to force push) and the PR should auto-magically update.

Here you can find some help:
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by smarshy** [comment]
@tapasweni-pathak This too is completed. Job dates are shown while creating shift.
