### ISSUE TITLE
Dates check

### ISSUE THREAD

**Issue by vubo** [systers/vms#133]
By creating event -> job -> shift check, that we can not create shift outside job dates and job outside event dates.

![image](https://cloud.githubusercontent.com/assets/7673323/9695761/8970d7de-5365-11e5-9e91-607e033854d9.png)

**Comment by KokareIITP** [comment]
Changed shift/views.py to avoid creating shift outside job.
https://github.com/KokareIITP/vms/commit/0fde4c1ff22324d7eeb6d6bd04b756324e9e6c19

Changed job/views.py to avoid creating job outside event.
https://github.com/KokareIITP/vms/commit/96907ddb226d6fe28a125c06e82dc8a1c78075f7

Please review.

**Comment by tapasweni-pathak** [comment]
This looks great @KokareIITP. :+1:  :smile: 

But let's wait for @vubo's comments. 

I have one question, why did you not submit a PR for this? Instead of giving a link to your code changes, you can send a pull request and then maintainers will review your pull request. 

While submitting a PR for a issue you can reference it. That links the issue with your PR.

**Comment by KokareIITP** [comment]
@tapasweni-pathak Actually I was waiting for the approval. So that if I needed to make changes,I would rather make it my code, and send a clean pull request, to make it easy for you to merge and analyze. :)

**Comment by vubo** [comment]
@KokareIITP thank you for your work! I updated this 2 files, but it doesn't work completely by me. I can't create a job or a shift, but I don't see any message. The user need to understand, why she/he can not create a shift.

**Comment by KokareIITP** [comment]
Yes @vubo 
I added the messages, but they are being displayed on the events page instead. I am working on it.

**Comment by vubo** [comment]
@KokareIITP and an advice from me: we use bootstrap lumen, so you can simply design your alerts http://getbootstrap.com/components/#alerts

**Comment by KokareIITP** [comment]
Thanks @vubo

**Comment by tapasweni-pathak** [comment]
@KokareIITP Please submit PR's from now on. Ideally, the comments on issues should be to discuss the issue, not to do code reviews. For ex if someone want to work on this issue, thinking that all the comments are a discussion over this issue they will read it, which is not at all required.

Every time you want your code to get reviewed, submit a PR. If you are changing something in the same PR, rebase to have clean commits. You can reference a issue in your PR that will automatically link the issue to your PR as well.

Let us know if you get stuck somewhere.

**Comment by KokareIITP** [comment]
Sure @tapasweni-pathak .
I agree with you and will definitely submit PR's from now onwards.

**Comment by tapasweni-pathak** [comment]
@KokareIITP Cool. :+1: :smile:

**Comment by KokareIITP** [comment]
@tapasweni-pathak @vubo 
Made necessary changes. Now it displays the error to user whenever needed.
Here is the pull request.
https://github.com/systers/vms/pull/174
Please review.

**Comment by vubo** [comment]
Closed via https://github.com/systers/vms/pull/174
