### ISSUE TITLE
Add a progress bar at the end of page having form

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#135]
Some pages on vms have large number of fields. Google form has a progress bar in the end of the form. It is nice for the user to know how much is done. Show a progress bar at the end of such pages.

**Comment by varunnaganathan** [comment]
I want to work on this !

**Comment by varunnaganathan** [comment]
Please review pull request:
https://github.com/systers/vms/pull/162

**Comment by varunnaganathan** [comment]
@tapasweni-pathak ,I have a doubt.I have created a branch with the ProgressBar implemented.However whenever I try to create a Pull Request,commits by other users are also included as a part of it.How do i deal with that??Any help would be appreciated.

**Comment by tapasweni-pathak** [comment]
@varunnaganathan You have to create a PR on develop branch, from your fork to vms repo. Ideally, the things that you have changed will come in diff when you will create one. 

I didn't exactly get it.  :( What do you mean by commits by other users are also included as a part of it?

**Comment by varunnaganathan** [comment]
@tapasweni-pathak I know about the basic working of pull requests.My doubt was regarding the inclusion of commits by other users which is present in my remote repository which is being included along with my changes
![pullrequest](https://cloud.githubusercontent.com/assets/9789511/11689980/63f702b2-9eba-11e5-818e-8edc8771b69b.png)
as the following screenshot shows,The diff shows not only the changes i made but also those made by other users.How can i include only commits by me in my pull requests?

**Comment by tapasweni-pathak** [comment]
@varunnaganathan I have never faced this. :( 

Are you using GitHub UI to create a pull request or command line?

**Comment by varunnaganathan** [comment]
@tapasweni-pathak   I have been using the github UI for the PR.I will try to find a solution and create the PR.

**Comment by tapasweni-pathak** [comment]
Cool. :+1:  Let me know if you are not able to for long, I'll look for something. 

Meanwhile we can review your code on your forked repo. Link when done. :)

**Comment by varunnaganathan** [comment]
@tapasweni-pathak here's the link to my repo.
https://github.com/varunnaganathan/vms/tree/progress1

**Comment by varunnaganathan** [comment]
@tapasweni-pathak 
Here's the link to the diff between my repo and the man development branch
https://github.com/systers/vms/compare/develop...varunnaganathan:progress1?expand=1
The main differences are in the /event/templates/event/create.html file.
If everything seems ok,ill add a new file for the javascript/jquery.

**Comment by varunnaganathan** [comment]
@tapasweni-pathak 
Here is the new pull request.I was able to solve the multiple commits problem mentioned by me above.
Please Review
https://github.com/systers/vms/pull/183

**Comment by anjali-dhanuka** [comment]
Please use the issue template.
