### ISSUE TITLE
Show Country/City suggestions

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#136]
VMS has forms that requires user to input city, country e.t.c. There are a lot of Django packages which are easy and support suggesting country names e.t.c. Use them and suggest Country/City as the user enters values in the fields.

**Comment by varunnaganathan** [comment]
i want to work on this.
Have given it a try please review pull request:
https://github.com/systers/vms/pull/162

**Comment by varunnaganathan** [comment]
i want to work on this !!
Please review pull request:
https://github.com/systers/vms/pull/164

**Comment by medhach** [comment]
@tapasweni-pathak :
Is this issue closed, or can I work on it?

**Comment by smarshy** [comment]
@tapasweni-pathak Is issue #75 same as this? One of them can be closed then.

**Comment by tapasweni-pathak** [comment]
I will close this one.
