### ISSUE TITLE
Add integration to Travis CI

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#140]

**Comment by smarshy** [comment]
@tapasweni-pathak If no one else has taken this up, could I work on this?

**Comment by tapasweni-pathak** [comment]
@smarshy Sure. Please go ahead.

**Comment by smarshy** [comment]
I might get to this tomorrow, slightly busy updating PRs now. If anyone else could tackle it sooner, please drop in a message and feel free to go ahead :)

**Comment by smarshy** [comment]
Started working on this
