### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#141]
* Link to contributors website
* Include GCI information, tasks

**Comment by KokareIITP** [comment]
Done . Is it fine ?

**Comment by tapasweni-pathak** [comment]
Thanks for trying fixing it @KokareIITP. But if you see on the right side of this issue, there is something as Assignee. I have assigned this to myself. As I know what is to be added where. I'll fix this. 

But we have a lot of newbie friendly issues. You can also try fixing issues tagged with GCI15.

**Comment by KokareIITP** [comment]
Sure Mam. Will look into other issues.

**Comment by tapasweni-pathak** [comment]
> Sure Mam. Will look into other issues.

Great.

**Comment by smarshy** [comment]
@tapasweni-pathak Is something still to be added or can this be closed?
