### ISSUE TITLE
docs page link to requirements document is broken

### ISSUE THREAD

**Issue by aarongable** [systers/vms#145]
The docs page (https://github.com/systers/vms/tree/develop/docs) has a link to the Requirements Document (https://github.com/systers/vms/blob/develop/docs/docs/Systers_GSoC14_VMS_Requirements.pdf) which 404s.

**Comment by rebeccag7** [comment]
This file doesn't exist and so we require somebody to change the reference on the page.

**Comment by KokareIITP** [comment]
The docs page has the following link. It is working well. 
https://github.com/systers/vms/blob/develop/docs/Systers_GSoC14_VMS_Requirements.pdf

**Comment by tapasweni-pathak** [comment]
Thanks for the issue @aarongable. #3dc5571 fixes this, so closing it.
