### ISSUE TITLE
Add links to Django Girls tutorial: how to install Python

### ISSUE THREAD

**Issue by Dr-G** [systers/vms#151]
http://tutorial.djangogirls.org/en/python_installation/index.html

**Comment by KokareIITP** [comment]
Done. Please check.

**Comment by tapasweni-pathak** [comment]
Thanks for the issue @Dr-G. Please always try to describe the issue, you open. It will become easier for the reviewers why we need it actually? Should it be closed or it is relevant.

For ex : Here, how adding this will improve the VMS readme? Why should be include this? e.t.c.

**Comment by tapasweni-pathak** [comment]
We have the necessary links to install things in our installation guides, so closing this without including this link. Repoen if needed. :)
