### ISSUE TITLE
Vagrant VM login

### ISSUE THREAD

**Issue by varunnaganathan** [systers/vms#160]
The vagrant Virtual Machine that boots up after running "vagrant up" asks for a login and password details of which are not present in the Installation Guide http://vms.readthedocs.org/en/latest/Installation%20Guide/

**Comment by vubo** [comment]
@varunnaganathan did you download Systers Ubuntu Virtual Machine? Did you save the vagrant file as "Vagrantfile" in the top level directory for the project?

**Comment by varunnaganathan** [comment]
Yes I did exactly all the steps the installation mentioned..I personally
didn't need to use the virtual machine.but for those who wish to ,as soon
as the VM boots it asks for a login and password.

**Comment by tapasweni-pathak** [comment]
@varunnaganathan Were you able to fix this or is this still irritating you?

**Comment by varunnaganathan** [comment]
@tapasweni-pathak  Not yet.I tried fixing it but couldnt get through.I however did not need to use the virtual machine.I could directly test the django App.

**Comment by KokareIITP** [comment]
@tapasweni-pathak 
The login: vagrant
       password:vagrant
And we can start working with the virtual machine.

**Comment by tapasweni-pathak** [comment]
@varunnaganathan Does what @KokareIITP is suggesting fixes the issue for you?

**Comment by varunnaganathan** [comment]
@KokareIITP Ya,that does it.@tapasweni-pathak I think we should add that to the installation guide ?

**Comment by tapasweni-pathak** [comment]
@vubo I searched and did not find this information in the installation guide. Is this already present?

If not @varunnaganathan please go ahead and add this. :+1: 

Thanks @KokareIITP for resolving the issue. I'm closing this. :)

**Comment by vubo** [comment]
@tapasweni-pathak no, this is not represented. Also I did not have this problem. It would be very helpful for other, if we add this. Thank you @varunnaganathan and @KokareIITP :tada:

**Comment by varunnaganathan** [comment]
@tapasweni-pathak  and @vubo 
will update the Installation guide as soon as possible.
Thanks @KokareIITP .

**Comment by varunnaganathan** [comment]
@tapasweni-pathak 
I added the login and password details in the installation Docs as discussed above.
https://github.com/systers/vms/pull/182
