### ISSUE TITLE
Addition of organization

### ISSUE THREAD

**Issue by KokareIITP** [systers/vms#167]
When we create a new administrator account, and suppose we don't choose any organization from the drop-down menu and write a new one. So, for the next time we create an administrator account it would be helpful if all previously registered organizations appear in the drop-down menu. But this doesn't happen.

Do we want this feature to be added ?

**Comment by tapasweni-pathak** [comment]
Adding every new organization to do the drop down menu doesn't seems to be good choice. We can even have people who can register to VMS without any actual need. We can have more organizations for sure. Right now we only have Google. Adding a total of 10 or something will make it useful. Then we have other option, where the user writes the organization, which they belong to. 

I have opened #324 closely related. I am closing this issue. Feel free to reopen it.

Thanks for the suggestion. :)

**Comment by KokareIITP** [comment]
@tapasweni-pathak . May be we could add a flag that checks if the organization ( not in dropdown list) has been registered more than a certain number of times, we could add it to the list. This would save our effort of updating the list.

**Comment by tapasweni-pathak** [comment]
Let's say someone tries to play with VMS with bogus registration and add non existent organizations and used them a lot of times by registering a lot of times. Our query will hit the database and will find it exceeded our set limit and then add it to the drop down list. It can be any name. 

It does reduces are work. But we need to think about the negative impact as well. If this part is in our control, such a situation cannot arise. We are loosing something, but we are gaining a better control on our application, isn't it?

**Comment by KokareIITP** [comment]
I agree with you. (Y)

**Comment by tapasweni-pathak** [comment]
Yes, captcha we will need, to avoid the cases when such a thing is automated. But still the above problem will be there.
