### ISSUE TITLE
Update the project README.md file

### ISSUE THREAD

**Issue by willingc** [systers/vms#17]
The README.md file of a project's repository is the world's outside view to the project. Examples of well done and not so well done examples can be found be looking at other projects.

Since the vms project will be actively worked on this summer and there are docs now at read the docs and a number of other places, let's make it easier for new contributors, current contributors, mentors, and future users to find the documentation that they are looking for. One of my favorite resources on documentation is Write the Docs. Here's a link to their tips on what makes a good README.md file: http://docs.writethedocs.org/writing/beginners-guide-to-docs/#readme

Use the template at the end of the Write the Docs section and the Systers/Portal README files for guidance. Some helpful things to include:
- Brief Project description (2 or 3 sentences)
- Features (link to the existing requirements documents) Also make a note that the project is under active development
- Installation instructions (for now just link to the Read the Docs for VMS)
- Contributing (links to source code, issue tracker)
- GSOC 2015 (links to key docs - timeline, blog)
- GSOC 2014 (links to key docs)
- License (refer to the license file)

**Comment by willingc** [comment]
@vubo This would be a good issue to practice your markdown skills and git/github skills for branches and pull requests. 

Helpful reminders:
1. Update your master branch. 
    * git checkout master
    * git remote -v (make sure you have an upstream remote)
    * git fetch upstream
    * git rebase upstream/master
    * git status
    * git log
2. Create a new branch for your README edits
    * git branch <new_branch_name>
    * git checkout <new_branch_name>
3. Work on your edits
    * git status
    * git add <changed_file or files>
    * git commit -m"message about the change"
    * git log
    * git status
    * git push origin <new_branch_name>

4. Go into GitHub and create a pull request

**Comment by vubo** [comment]
@willingc, thank you very much for your help and reminders!

I have a small question. When I do the first part:

1. Update your master branch. 
* git checkout master
* git remote -v (make sure you have an upstream remote)
* git fetch upstream
* git rebase upstream/master
* git status
* git log

![gitvaleria](https://cloud.githubusercontent.com/assets/7673323/7912718/3cd39c5e-086a-11e5-9da5-b8ba0d496603.png)

In the logs I see, that the last commit is from me: Fix two bugs... But in systers/master there are not this commits: https://github.com/systers/vms/commits/master

And if I do PR, I will send this old commits too.

![commit](https://cloud.githubusercontent.com/assets/7673323/7912911/aecb1462-086b-11e5-8c7e-a44c5767587f.png)

How can I pull only my last commit (test commit)?

Thank you!

**Comment by jayesh92** [comment]
@vubo you'll need to create a new branch, cherry-pick the desired commits and then submit a PR.
(I do it this way)

**Comment by willingc** [comment]
@jayesh92 Nice teamwork commenting on this issue and sharing `git cherry-pick`. You are correct that cherry-pick would be one way to do this.

@vubo and @jayesh92: While one could certainly use `git cherry-pick` to create a PR, it would be better, in the long run, to get the local `master` branch history to be the same as 'upstream', 'origin', and locally.

Valeria, good job noticing that the 'git log' history locally and upstream for master do not have the same commits. In systers/vms repo, the most recent commit is 0190b907673f638c21ef3bc1673bfcc3c1a4735e (or the HEAD of the systers/vms master branch).

Looking at Valeria's origin repo at https://github.com/vubo/vms, the master branch is 3 commits ahead of upstream. 
![screen shot 2015-06-01 at 6 31 54 am](https://cloud.githubusercontent.com/assets/2680980/7913945/85701934-0828-11e5-822d-612a2fbb336f.png)
And Valeria's origin/test branch (current feature branch) at https://github.com/vubo/vms/tree/test is 4 commits ahead of upstream/master.
![screen shot 2015-06-01 at 6 32 26 am](https://cloud.githubusercontent.com/assets/2680980/7913938/75df85ea-0828-11e5-9e89-8021161699e2.png)

Yikes, I need to be in a meeting.

Here is a good resource for understanding branches and git visually: http://pcottle.github.io/learnGitBranching/

More to come later...

**Comment by vubo** [comment]
@willingc and @jayesh92 thank you, I did it: https://github.com/systers/vms/pull/18

I used reset --hard and then cherry-pick. 

I'm turning to the README file now.
