### ISSUE TITLE
Suggestions to improve installation instructions

### ISSUE THREAD

**Issue by willingc** [systers/vms#172]
GCI student Ahmeds shared the following good suggestions for improving the installation instructions:

>The installation instructions were pretty good, and most of the things listed worked fine. To improve the >instructions, error handling should be added since I had a fair bit of issues. Here is what I would add:
>1.	Step 6: vagrant ssh did NOT initially work for me due to my Git installation. Selecting "Use Git from >the Windows Command Prompt" in the "Adjusting your PATH environment" in the GIT installation >causes ssh to not work. "Use Git and optional Unix tools from the Windows Command Prompt” should >be selected instead. Perhaps this should be added to Step 1
>2.	Step 9: “python manage.py syncdb” kept generating the error “FATAL: role "myuser" does not exist”. >I ran sudo su –postgres and then created the user myuser by doing “createuser –s –r myuser”. Exit >should be run after to exit the sudo su. Syncdb worked fine after.
>3.	Step 9 continued: “insert into organization_organization values (1, ‘Google’); would not work as I did >not have the permissions when logged in as vmsadmin. Instead, I quit the postgres client and logged in >again as “myuser” by doing “psql –U myuser –d vms –h localhost –W”, then inserting worked well. Not >sure how to change the permissions so vmsadmin can do the same

**Comment by tapasweni-pathak** [comment]
@willingc Need to reproduce to understand them better. But they indeed seems good. Many face problem in python manage.py syncdb.

We already have a issue for this #134. Can we club everything there, together and then we can close this issue?

**Comment by willingc** [comment]
@tapasweni-pathak Absolutely :smile: Good suggestion.

Closing and link to #134.

**Comment by tapasweni-pathak** [comment]
@willingc :+1:
