### ISSUE TITLE
No way to find which features are implemented to date

### ISSUE THREAD

**Issue by maydhak** [systers/vms#186]
VMS has a requirements document and multiple to-do lists for features (such as GSoC 2014/2015) but it is unclear which features are implemented to date without installing and trying out various use-cases in the product itself (tedious). Maybe the issue tracker on GitHub can be used to track features by tagging them as 'feature'. If there is already a trackable feature list somewhere, please update this issue and feel free to close it. Thanks.

**Comment by tapasweni-pathak** [comment]
@maydhak We use the issue tracker on GitHub to track the issues. Whatever you see as open issues are the only things to-dos, unless you find something new. The to-do list you have seen were for that specific GSOC's. 

You can check the releases [here](https://github.com/systers/vms/releases). 

Does this answer what you were looking for?

**Comment by maydhak** [comment]
The release page is not exactly what I was looking for. I was looking for something that specifies what has already been completed, rather than what is left to do. Without installing the system, a user doesn't know the current capabilities of the program compared to the requirements document/initial vision.

**Comment by tapasweni-pathak** [comment]
@maydhak It is better to install it and then find out what is the current stage. It is not something which is tedious but a necessary thing to do. ☺

For improvement, enhancements e.t.c we use GitHub issue tracker. What all is closed, is done. Whatever is still open, that is a todo.

If this answers your question, I'll close this issue.

**Comment by tapasweni-pathak** [comment]
Closing this. Feel free to reopen if needed.
