### ISSUE TITLE
Shift can start and end at the same time

### ISSUE THREAD

**Issue by maydhak** [systers/vms#194]
I created a shift that started and ended at the same time. No errors were reported and the creation was successful which is incorrect.

**Comment by willingc** [comment]
There is an open PR #246 pending on this issue.

**Comment by KokareIITP** [comment]
@willingc . It was actually mentioned in the code that end time was not made greater than start time intentionally. What is the reason we are changing it now ?

**Comment by smarshy** [comment]
@tapasweni-pathak Unable to replicate this issue, seems to be resolved
