### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by sarayd** [systers/vms#201]
When completing Step 7 of the Installation Guide, you may face trouble when you enter the command "python manage.py syncdb". The error is: "FATAL: password authentication failed for user 'myuser'". Here is a way to resolve that.
[alternatesetup.pdf](https://github.com/systers/vms/files/103742/alternatesetup.pdf)

**Comment by AaskaShah** [comment]
I just made following changes in my settings.py

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'vms',
      **'USER': 'vmsadmin',**
   **'PASSWORD': '0xdeadbeef',**
        'HOST': 'localhost',
    }
}

And it worked !

**Comment by sarayd** [comment]
Interesting! I'm surprised the resources I viewed online didn't suggest that @AaskaShah Thanks for the tip though!

**Comment by willingc** [comment]
Thanks @sarayd and @AaskaShah. I'm closing this now that #232 has been merged.
