### ISSUE TITLE
Ability to edit events and jobs leads to discrepancy in dates

### ISSUE THREAD

**Issue by smarshy** [systers/vms#210]
The dates of an event can be changed anytime after its creation. However, there is no check for its jobs to see if it still falls within the new date range. There is a similar situation for jobs and shifts. 

I am working on this but there seem to be various possible ways:

1. Not allowing editing of an event if it has jobs and similarly not allowing editing of jobs if it has shifts (similar to the current deletion procedure)
2. Cascade deletion of jobs/shifts if changes are made to event/jobs
3. Checking if jobs/shifts violate new range and deleting those which do or not allowing editing in case they do

Which one is preferred?

**Comment by vubo** [comment]
@smarshy good catch :+1:  

I would say don't delete something automatically, it is not so good for the system. 

Your first option is fine. We schould check dates and if this dates are incorrect for shifts or jobs, then we should show a detailed info message and prevent incorrect changes.

**Comment by smarshy** [comment]
@vubo done :+1:
