### ISSUE TITLE
Mistakes in the Installation Guide

### ISSUE THREAD

**Issue by musicakc** [systers/vms#227]
In the vms installation guide here, when I was Setting up Postgresql, the command given in the docs is:
`psql -U vmsadmin -d vms -h localhost -W`

This should list the tables but actually this is giving me a `No relations found` response.

I changed `psql -U` to `psql -E` and it listed the tables then.

Maybe the doc should be changed?

Also the command right above this one is:
`createdb -U vmsadmin vms;` which also prompts for a password which isn't mentioned in the doc and I think it should be mentioned.

**Comment by KokareIITP** [comment]
@musicakc  I agree that after < createdb -U vmsadmin vms; > , we need to mention about the password. 
But even though I tried psql -E , the tables didn't list in my case. Here is a screenshot.
 https://gyazo.com/98fa11ffc5fc37ce517bd91cec4b2b53
Whereas after following the installation guide, I could list the tables.
https://gyazo.com/be906c312a44d19127b68fcfd5082cec
