### ISSUE TITLE
404 error when editing shifts

### ISSUE THREAD

**Issue by smarshy** [systers/vms#228]
Hi! Ran into this after a fresh pull. After editing a shift, when we click on the save button, an error page pops up

![k2](https://cloud.githubusercontent.com/assets/13931206/13171030/73a6fade-d716-11e5-91a9-3b4c281b287e.png)

**Comment by KokareIITP** [comment]
@smarshy It works fine in my case. Please can you recheck.

**Comment by smarshy** [comment]
@KokareIITP If that is the case, I might have messed up something on my end which triggered this error. I will check it soon.

**Comment by smarshy** [comment]
@KokareIITP Hi! So i tried replicating this and ran into a 404 error again.  :see_no_evil:
Whenever you click on the save button, there are two possible responses - one that gives you an error message for invalid dates but saves anyways and another when your dates are valid. The 404 page crops up in the latter situation. [This](https://github.com/smarshy/vms/commit/852117f9afb294deeb86f075e417e324d7348118) was attempting to solve both actually.

![www gifcreator me_mkhbzp](https://cloud.githubusercontent.com/assets/13931206/13202731/6e35aeea-d8cb-11e5-99df-19b896ac94c4.gif)

In the above, you can see what was happening - the shifts are listed by the job id. Here you can see that though the job id is 3, it tries to access the list using the shift id which is 7... and hence the 404 error. Sorry for not specifying the replication instructions clearly. :sweat_smile:
Anyways, I guess this issue is pointless once some changes are rolled back.

**Comment by KokareIITP** [comment]
@smarshy Here in my case, it is working perfectly fine.
Please see https://gyazo.com/cd67e3d9e2b4efd2ffb8276731b8956b

**Comment by smarshy** [comment]
@KokareIITP Umm.... It still doesn't work actually. You have uploaded a snapshot of a case when the job id and shift id are same ( both 1) . I understand why you might not be getting the error then. Try creating a job (eg. with id 1) , two shifts within it (eg. id 1 and id 2) and then a second job (id 2). Now, create a shift within this job ( id 3). Basically just check for a test case when shift and job ids are not same. That is when you run into an error. Please try.

**Comment by KokareIITP** [comment]
Yes @smarshy . The error occurred for the case you mentioned. (Y)

**Comment by smarshy** [comment]
@KokareIITP  Thanks for confirming :+1:

**Comment by willingc** [comment]
Marking this as a bug since reported and verified.

@vubo Thoughts?

**Comment by softcoder32** [comment]
hello @willingc , i have solve this already, Please review this pull request
https://github.com/systers/vms/pull/249
