### ISSUE TITLE
About link

### ISSUE THREAD

**Issue by KokareIITP** [systers/vms#241]
The About link beside the Systers link ( homepage) does not seem to provide any utility. Is there any change to be made to redirect it to some wiki page ? 

https://gyazo.com/631fb378a0df4a2607e0c2dcb1a75a2e

**Comment by smarshy** [comment]
@tapasweni-pathak This is valid. The link is not leading to anywhere as of yet.

**Comment by tapasweni-pathak** [comment]
@rosariorobinson What should we connect with the about page, in VMS?

**Comment by willingc** [comment]
@tapasweni-pathak My recommendation would be to remove "About" or to use "About" to discuss the history of the VMS project and its roots in GSoC projects.
