### ISSUE TITLE
Show an error message, when no organization is added and sign-up is clicked 

### ISSUE THREAD

**Issue by tonythomas01** [systers/vms#257]
Currently, Django checks if an organization exists, and try rendering a faulty ('organization/add_organizations.html') which do not exist. A possible better approach would be to either: 

1. Show up an error message, or badrequest message saying "You need to have atleast one organization" 
2. Do not show the 'Signup Volunteer' button at all, when no organization are available 
3. Show up a neat message in and alert div saying that you need to have at-least one organization. 

Even though its mentioned in http://vms.readthedocs.org/en/latest/Installation%20Guide/ that There needs to be at least one organization in the organization_organization table in order to register for an account (this be changed later). Add Google as an organization -- its not a recommended approach to send a user to a 404 right from the home page. 

Related :  #39

**Comment by softcoder32** [comment]
hey @tonythomas01 , will take on this issue! working on it now.

**Comment by smarshy** [comment]
@tonythomas01 I would like to give this a go. However, instead of this, would it be okay if I go ahead and try to remove the need for an organization to be in the table?

**Comment by smarshy** [comment]
@softcoder32 Sorry, just refreshed and saw your message. You can go ahead :)

**Comment by Raxerz** [comment]
#269

**Comment by Raxerz** [comment]
#269

**Comment by Raxerz** [comment]
@tonythomas01 Please review  #269

**Comment by tapasweni-pathak** [comment]
@tonythomas01 For some reason I'm not able to reproduce this issue. Do you want me to leave the organization field blank on *registration/signup_volunteer/*  page or enter an invalid value like something which has digits?

**Comment by tonythomas01** [comment]
> @tonythomas01 For some reason I'm not able to reproduce this issue. Do you want me to leave the organization field blank on registration/signup_volunteer/ page or enter an invalid value like something which has digits?

@tapasweni-pathak It happens during the initial setup time, with 0 organizations in the organization_organization table. Accordingly, you can either truncate organization_organization and check, or go for a fresh clone + db. This doesn't happen when we leave something blank in some forms.

**Comment by tapasweni-pathak** [comment]
@tonythomas01 Thanks!
