### ISSUE TITLE
Models are not connected with admin.py 

### ISSUE THREAD

**Issue by tonythomas01** [systers/vms#258]
Only the User model seems to be connected with admin.py, while we have volunteer, organization, job etc still not connected to admin.py. 

https://docs.djangoproject.com/en/1.9/ref/contrib/admin/

**Comment by softcoder32** [comment]
@tonythomas01, working on this already.

**Comment by softcoder32** [comment]
hello, @tonythomas01 , there are many files to change should i do one single pull request??

**Comment by softcoder32** [comment]
hello @tonythomas01 , added models to admin panel and function to return appropriate infos in each Model please review #262
