### ISSUE TITLE
Navigation bar should show dropdown with user actions instead of separate links

### ISSUE THREAD

**Issue by tonythomas01** [systers/vms#266]
The current design has the navigation bar, after sign-in as: 
![image](https://cloud.githubusercontent.com/assets/4214481/13603883/553372ea-e566-11e5-85e1-82b678a69c24.png)

This should look better if we can have something like 
![selection_056](https://cloud.githubusercontent.com/assets/4214481/13603979/a59b4c4e-e566-11e5-92fa-4874ad44ee9b.png)

with the logged in user name  + a drop down.

**Comment by tapasweni-pathak** [comment]
@tonythomas01 This indeed looks better. Thanks for the issue. :+1:
