### ISSUE TITLE
Discrepancy in same model fields between volunteer and other models

### ISSUE THREAD

**Issue by smarshy** [systers/vms#273]
The following fields seem to have a different length for volunteers file
1. City - (75 for volunteers, otherwise 30)
2. Country - (75 for volunteers, otherwise 30)
3. Address - (75 for volunteers, otherwise 30)
4. First name - (30 for volunteers, otherwise 20)
5. Last name- (30 for volunteers, otherwise 20)
6. State - (75 for volunteers, otherwise 30)

For example, for address the differences can be seen [here](https://github.com/systers/vms/blob/develop/vms/volunteer/models.py#L30) and compared to [admin](https://github.com/systers/vms/blob/develop/vms/administrator/models.py#L26), [event](https://github.com/systers/vms/blob/develop/vms/event/models.py#L18), [shift](https://github.com/systers/vms/blob/develop/vms/shift/models.py#L24)

**Comment by KokareIITP** [comment]
@smarshy  I guess it includes the issues with models :+1: 
@tapasweni-pathak Is there any particular reason for this ?

**Comment by smarshy** [comment]
@tapasweni-pathak The discrepancies are still there, I don't know if it is an issue though and if the lengths need to be updated

**Comment by tapasweni-pathak** [comment]
Length of the entities should be changed to :

1. City - 75
2. Country - 75
3. Address - 75
4. First name - 30
5. Last name- 30
6. State - 50

everywhere.
