### ISSUE TITLE
Drop down menu for jobs in report

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#276]
In the report for administrator, create a dropdown menu for jobs.

**Comment by softcoder32** [comment]
@tapasweni-pathak , please review #281 
![screenshot from 2016-03-16 08 00 36](https://cloud.githubusercontent.com/assets/17668677/13804477/94eb274c-eb4d-11e5-8ef1-f3b90aaabcaa.png)

**Comment by softcoder32** [comment]
@tapasweni-pathak , i also want to do same for report in the volunteer section, should i believe the jobs displayed there should be jobs which linked with the volunteer, please for you opinion, thanks.

**Comment by tapasweni-pathak** [comment]
@KokareIITP or did you fix this with pull request #316?

**Comment by KokareIITP** [comment]
Yes @tapasweni-pathak . This issue is solved by #316 .
