### ISSUE TITLE
Display Message above page in case of no result in Admin Report

### ISSUE THREAD

**Issue by softcoder32** [systers/vms#283]
when admin makes a search to view report, if no results is found, message is displayed below the page and user needs to scroll down to see the the error message, displaying this message above the page will be more user friendly.

**Comment by Himanshi-Khandelwal** [comment]
@softcoder32  are you talking about this error message in red?

![screenshot from 2017-01-26 11 55 32](https://cloud.githubusercontent.com/assets/17119462/22321915/6a14b258-e3be-11e6-901d-11e73f348a16.png)
