### ISSUE TITLE
Migrating Volunteer Management System to Class based Views

### ISSUE THREAD

**Issue by amruthasangeeth** [systers/vms#288]
Systers’ Volunteer Management System  currently uses function based views. It repeats certain patterns again and again, and is mostly redundant. Function based views are deprecated after python version 1.3.  Class Based generic views helps to streamline common use cases, saving development time and effort.
One of the advantages of CBV is Inheritance. For instance, large projects like VMS has a lot of redundant code due the repetition of similar views. By migrating to CBV, views could be inherited and thus avoid code redundancy.

Few advantages, which VMS can achieve by migrating to Django’s class based views are :
- Django offers various generic views like CreateView, UpdateView, FormView, ListView and DetailView to handle views easily. For eg: Allow users to Create, Update and Delete events and shifts of volunteers with or without authorization, without violating DRY.
- Better code readability, reducing the number of lines of code, easing the code review process. 
- Replacing the decorators by mixins instead, makes them more flexible, extensible and DRYer, just like the move from FBVs to CBVs.  
- Better handling of form data, which is handled in a traditional way in FBVs.
- Better support from the Django development community as the recent developments are CBV based.

Considering various advantages of shifting to CBV, I propose this migration for all the apps in VMS to be a Google Summer of Code 2016 project, and I have come up with a proposal for the same. The following are the tasks to be completed for migration of VMS to CBV

- [x] Migrating home app to CBV
- [x] Migrating authentication app to CBV
- [x] Migrating administrator app to CBV
- [ ] Not allowing a shift cancellation once the shift is started
- [ ] Implement forgot password functionality
- [ ] Email confirmation for account functionality
- [x] Migrating event app to CBV
- [x] Migrating job app to CBV
- [x] Migrating registration app to CBV
- [ ] Support for timezones
- [x] Migrating volunteer app to CBV
- [ ] Implementing 12 hour or 24 hour format
- [x] Migrating shift app to CBV
- [x] Migrating organization app to CBV

**Comment by tapasweni-pathak** [comment]
@amruthasangeeth Please write the advantages of shifting to CBV. 
Reference this issue every time you open a pull request related to this change. Don't use 'close' or 'fixes'.
Have a checkbox option in the description of the issue here, for the apps. Check the app when it is done.

Let me know if you need any help in doing this.

**Comment by amruthasangeeth** [comment]
@tapasweni-pathak I have updated the issue. Is this enough?

**Comment by tapasweni-pathak** [comment]
Thanks. We needed this. :+1:

**Comment by tapasweni-pathak** [comment]
As we have marked the end of GSoC'16, I am closing this issue. 

Thanks for the work. :sparkles:
