### ISSUE TITLE
Command "createdb -U vmsadmin vms;" prompts for a password

### ISSUE THREAD

**Issue by shoaib1987** [systers/vms#295]
Command "createdb -U vmsadmin vms;" prompts for a password, not mentioned in the installation guide.

**Comment by smarshy** [comment]
@shoaib1987 - Hi, [This](http://vms.readthedocs.org/en/latest/Installation%20Guide/) one still isn't reflecting the recent changes. I am not sure why :( but there is an installation guide [here](https://github.com/systers/vms/blob/develop/docs/Installation%20Guide.md) which has the latest changes.

**Comment by shoaib1987** [comment]
As per the new installation guide Django (version >= 1.7 and version < 1.8) is required, my current version is :
>>> django.VERSION
(1, 9, 5, 'final', 0)

**Comment by KokareIITP** [comment]
@shoaib1987 . As @smarshy mentioned it is available on the installation file on github. Moreover whenever you may login into postgres, the password will be what you set in the command 
_create role vmsadmin with createrole createdb login password '0xdeadbeef';
_ which seems to be 0xdeadbeef here. I hope that helps.

**Comment by shoaib1987** [comment]
@smarshy and @KokareIITP thanks for prompt reply .  May be we should close this issue when installation guide on github starts reflecting the recent changes.

**Comment by tapasweni-pathak** [comment]
@shoaib1987 I'm closing this. I have opened a more specific issue #298.

@KokareIITP, @smarshy Thanks for the help.
