### ISSUE TITLE
In edit event retain the end date of even if user enters wrong start date

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#301]
If user enters wrong start date (before today or something similar), error message comes and even the end date field goes blank. Retain all the information other than start date on the page.

**Comment by malabikas** [comment]
@tapasweni-pathak The issue can be closed now.

**Comment by tapasweni-pathak** [comment]
@malabikas You can refer the issue in your Pull Request using closes #issue_number or fixes #issue_number. That will close the issue when the PR gets merged. That will be helpful.
