### ISSUE TITLE
Enter cities_light in INSTALLED_APPS, in the guide.

### ISSUE THREAD

**Issue by malabikas** [systers/vms#303]
The installation guide doesn't specify modifying the `settings.py` file for the project.

Before proceeding with `python manage.py cities_light` , `cities_light` should be added as an entry in `INSTALLED_APPS` in the `settings.py` file. This is missing in the documentation.

**Comment by tapasweni-pathak** [comment]
Can you submit a pull request for this?

**Comment by malabikas** [comment]
I just happened to know that the issue has been already resolved [here](https://github.com/systers/vms/blob/develop/vms/vms/settings.py) . The installation guide [here](https://github.com/systers/vms/blob/develop/docs/Installation%20Guide.md#ppm) says that we need to clone this repo  `https://github.com/Nerdylicious/vms-integrated.git` which has not been updated since a long time and that's why I had to open this issue. 
Should I submit a pull request to update the doc saying `git clone https://github.com/systers/vms.git` ?
