### ISSUE TITLE
Unable to upload resume; 'Permission denied' error

### ISSUE THREAD

**Issue by malabikas** [systers/vms#305]
While signing up as a volunteer, after submitting I get this error:
![django_perm](https://cloud.githubusercontent.com/assets/16019535/14841851/7ce0da2e-0c5f-11e6-9c7d-51f4b674f34a.png)

The permissions for the folder have been set as 777 using
`sudo chmod 777 /srv`

```
ls -ld /srv
drwxrwxrwx 2 root root 4096 Oct 21  2015 /srv
```

I just can't figure out what's the problem. Any help will be appreciated. Thanks!

**Comment by tapasweni-pathak** [comment]
I was able to reproduce. Thanks for the issue.

**Comment by anjali-dhanuka** [comment]
@tapasweni-pathak You just need to create the directory srv/vms/resume in vms and change its permission by running sudo chmod -777 srv/ . It works perfectly fine then. 
![screenshot from 2018-01-26 18-23-50](https://user-images.githubusercontent.com/22369767/35440700-8c84f924-02c6-11e8-801e-08ec70e15dd0.png)
