### ISSUE TITLE
 Dependent dropdown menu for jobs for report generation

### ISSUE THREAD

**Issue by KokareIITP** [systers/vms#313]
In report.html when the user generates report , to avoid confusion for which event belongs to which job, it is better to create a dropdown option list rather than currently used text input. The options in the job list will be updated based on the event selected in the dropdown menu for events.

**Comment by tapasweni-pathak** [comment]
@KokareIITP Did you fix this with pull request #316?

**Comment by KokareIITP** [comment]
No @tapasweni-pathak . Though #316 creates a dropdown for jobs, but it doesn't depend on the event selected.

**Comment by anjali-dhanuka** [comment]
Please use the issue template
