### ISSUE TITLE
Run pycodestyle on vms

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#318]
Check if there are any significant changes or is it just a new name, when it comes to VMS.

[PyCodeStyle](https://pypi.python.org/pypi/pycodestyle/1.8.0.dev0).

**Comment by rach-01** [comment]
I would like to help.

**Comment by kits-ragh** [comment]
I would like to help on this

**Comment by tapasweni-pathak** [comment]
@rach-01 Sure. Let us know if you get stuck somewhere.

**Comment by anweshknayak** [comment]
Hey exactly on which files ?

**Comment by tapasweni-pathak** [comment]
@anweshknayak On all *.py files. 

This is also labelled as first-timers-only. On the top right side you can see all the labels. 
I have opened these issue for people who want to get started with contributing to open sources and this can be their first pull request ever on GitHub. Please don't pick this up. 

You can help us by fixing any other issue which is **not** labelled as first-timers-only. Let us know if you need any help.

**Comment by Xavier-J-Ortiz** [comment]
is this still open?

I'd like to take a swing at this. Would also be my very first PR as well! :)

**Comment by cherya** [comment]
@tapasweni-pathak does it mean only check? Or check and fix errors?

**Comment by tapasweni-pathak** [comment]
@cherya Check and fix will be great.

**Comment by cherya** [comment]
[vms.log](https://github.com/systers/vms/files/547416/vms_log.txt)
it is too much errors
maybe ignore warnings?

**Comment by tapasweni-pathak** [comment]
@cherya Run it on all the *.py files i.e., all python files.

**Comment by cherya** [comment]
@tapasweni-pathak it's only *.py files in log. Am I doing something wrong?

**Comment by tapasweni-pathak** [comment]
@cherya, oh sorry, I understood something else before. You can ignore warnings plus all files which are present in test directory, for the time being.
