### ISSUE TITLE
Implement forgot password functionality

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#320]
Django’s inbuilt PasswordResetForm can be used.

Suggested by @smarshy.

**Comment by anjali-dhanuka** [comment]
I would like to work on this issue if noone is working on it

**Comment by anjali-dhanuka** [comment]
Mam I have implemented the feature. Just wanted to ask you the host for sending emails in vms.

**Comment by kamsuri** [comment]
I'm closing this issue as it doesn't follow the standards.  I've opened a new one #683 for the same.
