### ISSUE TITLE
Don’t allow shift cancellation once a shift has started

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#321]
Suggested by @smarshy.

**Comment by rituranjna** [comment]
@tapasweni-pathak @smarshy @amruthasangeeth 
Is this bug still opened ?

**Comment by smarshy** [comment]
@rituranjna Sure, go ahead :)

**Comment by smarshy** [comment]
++gci

**Comment by pradeepgangwar** [comment]
@Chauhan99 are you still working on this? I would like to fix it if you are not working.

**Comment by anjali-dhanuka** [comment]
Please use the issue template
