### ISSUE TITLE
Edit event forces you to reset start date again

### ISSUE THREAD

**Issue by smarshy** [systers/vms#340]
## Description
As a USER when I edit the event, even if I don't edit anything, it forces me to reset the dates if they are later than today's.

## Mocks
![image](https://user-images.githubusercontent.com/22369767/41815054-263157ae-777d-11e8-8ffa-134da2acea5e.png)

### Update [Required]
- Make changes in EventUpdateView

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by tapasweni-pathak** [comment]
@smarshy As discussed I am marking this as a question. For your test cases take it as a right behavior and reference this when you submit a pull request for the tests.

**Comment by anjali-dhanuka** [comment]
closed #856
