### ISSUE TITLE
Server Error triggered on adding null values to edit event

### ISSUE THREAD

**Issue by smarshy** [systers/vms#345]
Instead of showing a proper helper message when null value is entered while editing an event, an error page shows up

**Comment by tapasweni-pathak** [comment]
Did you save it keeping some fields as blank?

**Comment by smarshy** [comment]
@tapasweni-pathak I blanked out all the values in the edit event form and tried saving it. I created a test for this expecting messages asking to enter valid value for the compulsory fields. But instead, I got the following error:

![eeror](https://cloud.githubusercontent.com/assets/13931206/16230622/16370efe-37e0-11e6-908e-7ea9e155c758.png)

**Comment by tapasweni-pathak** [comment]
@smarshy I was able to reproduce it. Thanks for the issue.
