### ISSUE TITLE
Non-uniform behaviour in forms when they are reloaded

### ISSUE THREAD

**Issue by smarshy** [systers/vms#350]
When incorrect values are entered in the fields, in some situations the form values are erased while in other cases they are still visible.

For eg. while creating event if start date is incorrect, error message is shown but the date is not erased. However, if the same values are put in edit event form, the error message is shown and the start date vanishes

**Comment by rituranjna** [comment]
@smarshy  Are you working on this ? If not, i am willing to take this task.

**Comment by smarshy** [comment]
@rituranjna No, I haven't taken this up. Feel free to go ahead

**Comment by anjali-dhanuka** [comment]
@rituranjna @smarshy @tapasweni-pathak @tonythomas01 I have found that when we edit one of the start date or end date the other automatically gets removed. I have gone through the code and I have found that Datetimepicker jquery is used in both forms but I am unable to guess why is it working fine in create form. Can you guide me how to proceed?

**Comment by anjali-dhanuka** [comment]
please use the issue template.

**Comment by anjali-dhanuka** [comment]
have a look at this @tonythomas01 
https://github.com/systers/vms/blob/gsoc18-code/vms/job/templates/job/edit.html

**Comment by tonythomas01** [comment]
```
							<input class="form-control" type="text" name="start_date" id="from" name="from" value="{% if form.start_date.value %}{{ form.start_date.value|date:"SHORT_DATE_FORMAT" }}{% endif %}">
``` 
multiple name field, making it ugly. Well, it again depends on what is happening on the JS side.
