### ISSUE TITLE
Using selectors in template for easy access of elements

### ISSUE THREAD

**Issue by smarshy** [systers/vms#354]
This is a suggestion to use ids uniformly in templates. This makes accessing these elements much easier by the selenium webdriver and will remove dependency on xpath (and hence UI structure). 
For some files in vms, these selectors are already available.(See[registration template](https://github.com/systers/vms/blob/develop/vms/registration/templates/registration/signup_administrator.html#L283))
while there is a lack of such selectors in others (eg. [Event creation page](https://github.com/systers/vms/blob/develop/vms/event/templates/event/create.html#L29))

**Comment by bryongloden** [comment]
Greetings @smarshy. I'm trying to help here. Maybe I don't understand too well. Is the selenium webdriver similiar to the [dejaclick by alertsite](http://dejaclick.alertsite.com/) web driver? I did not know of  the selenium before reading it here first a moment ago. Dejaclick works great for me. How are selenium and dejaclick similiar and different I guess I what I'm just asking here

**Comment by tapasweni-pathak** [comment]
@bryongloden I am not sure if you are a bot or a human, be it anyone, what you are doing is irritating. Can you please stop spamming our conversations? Let me know if you are not able to I will report and block you. 


If you want to contribute to VMS please see the list of [open issues](https://github.com/systers/vms/issues) and read the [documentation](https://github.com/systers/vms/tree/develop/docs) to get started. Let us know if you have any specific questions or need any help in doing something useful for [VMS](https://github.com/systers/vms).

**Comment by bryongloden** [comment]
Greetings @tapasweni-pathak. I'm not a bot. What on earth gave you that idea? And it wasn't spamming it was helping. Spamming is much different. At the very least thanks for giving me a chance to explain myself in here. I was only trying to help by using words and emoji of encouragement. From our perspective it takes time to read the open issues and even more time to volunteer to fix something. For you to accuse a @GitHub volunteer of spamming this early in the process of getting to know each other is disgusting. You ought to be ashamed of yourselves. And you ought to read the rules of making friends. I'll re-read your list of open issues and documentation and take it from there. Have a nice day!

**Comment by tapasweni-pathak** [comment]
> I'm not a bot. What on earth gave you that idea?

A human cannot be this intrusive. Please see your past 15 days activities on VMS GitHub repository. 

>I was only trying to help by using words and emoji of encouragement.

It didn't help or encourage us. We are irritated.

One more irrelevant/unnecessary comment or piece of encouragement from you and we will block and report you.

**Comment by Himanshi-Khandelwal** [comment]
I have seen the templates and wish to know at what all places I should use the selector?

**Comment by anjali-dhanuka** [comment]
Please use the issue template.
