### ISSUE TITLE
Improving the coverage

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#368]
The coverage is low. @smarshy can you please document how we can improve it? What are the issues you are facing in doing the required changes?

cc @nidhimj22 @amruthasangeeth  @nida.

**Comment by smarshy** [comment]
Coverage is providing the number of missed lines, but not listing them. So, it is getting challenging to figure out which those lines are.

To increase coverage, tests for views and models need to be added

**Comment by tapasweni-pathak** [comment]
Coverage right now looks fine, so I am closing this. Still we need to add tests for views and models @smarshy?

**Comment by smarshy** [comment]
yes the tests still have to be added @tapasweni-pathak

**Comment by tapasweni-pathak** [comment]
Can you please open separate issues for these then? Do you know for which the tests have to added?
