### ISSUE TITLE
Update VMS Wiki

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#377]
Currently [VMS wiki](https://github.com/systers/vms/wiki) is blank. It will be useful to have information about VMS in the wiki.

**Comment by mehak6669** [comment]
Hey! Mehak this side. I see the VMS Wiki page leading to some description. I fail to understand what more needs to be added. If I could now the requirement, I am willing to take this up.

**Comment by tapasweni-pathak** [comment]
Closes as we have [this](https://github.com/systers/ossprojects/wiki/Volunteer-Management-System).
