### ISSUE TITLE
Remove all 'import *' from code

### ISSUE THREAD

**Issue by rituranjna** [systers/vms#379]
In  my opinion using `from module import *` is not good.

> ```
> Because it puts a lot of stuff into your namespace (might shadow some other object from previous import and you won't know about it).
> 
> Because you don't know exactly what is imported and can't find place from what module certain thing was imported easily (readability).
> 
> Because you can't use cool tools like pyflakes to detect statically errors in your code.
> ```

Source: http://stackoverflow.com/questions/2386714/why-is-import-bad
https://pythonconquerstheuniverse.wordpress.com/2011/03/28/why-import-star-is-a-bad-idea/

Few examples in vms code:
https://github.com/systers/vms/blob/aa75b55bca85196a270e5f697d10b26b85defdf5/vms/shift/views.py#L7

aa75b55bca85196a270e5f697d10b26b85defdf5

**Comment by rituranjna** [comment]
cc @tapasweni-pathak @smarshy

**Comment by tapasweni-pathak** [comment]
@rituranjna Thanks for the issue. :star:

**Comment by Ads7** [comment]
@tapasweni-pathak  what are your views regarding be the best way to remove such imports 

- option1: import individual functions and classes
`from module import a,b,c`
this would create long import statements and won't help in readability much.

- option 2: import the whole module and use classes 
 ```
 import module
 module.a, module.b
 ```
 this one would have shorter import statements along with more readability but the whole module would be imported.

**Comment by josejibin** [comment]
if nobody started on this, I would like to work on it

**Comment by smarshy** [comment]
@josejibin Sure, please go ahead

**Comment by josejibin** [comment]
@smarshy  Can I remove unused imports in this PR?

**Comment by smarshy** [comment]
While resolving this, please add commits for an entire app, or say all views/models/form/tests/urls; do not add a commit for every file you change.

**Comment by tapasweni-pathak** [comment]
@josejibin Please, go ahead with the changes. In the description of the pull request explain with few lines why your change is better than what VMS has right now.

**Comment by tonythomas01** [comment]
Also, the imports needs to be improved more. Check https://github.com/systers/vms/issues/509#issue-269311137 

`from pom.xx.yyy` should become 
`from vms.pom.xx.yyy`

**Comment by MeepyMay** [comment]
PR Merged. Closing Issues.
