### ISSUE TITLE
Add full stop at the end of statements

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#381]
[Where?](https://github.com/systers/vms/blob/develop/vms/registration/views.py#L22)

**Comment by tapasweni-pathak** [comment]
[Are there any more lines?](https://github.com/systers/vms/blob/develop/vms/registration/views.py#L27)

**Comment by RP99** [comment]
Hi, I would like to resolve this issue if nobody is working on it. Since, I am a newbie would like to know the process of resolving the issue that you guys follow for this project.

**Comment by tapasweni-pathak** [comment]
@RP99  Steps you need to follow :

1. Fork VMS.
2. Add a full stop at the linked lines.
3. Submit a pull request.

If you get stuck while doing any of the above, let us know.
