### ISSUE TITLE
Show event suggestion as dropdown

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#382]
volunteer/report/

**Comment by smarshy** [comment]
@tapasweni-pathak are the event and jobs not being showed in the dropdown?

**Comment by tapasweni-pathak** [comment]
Yes, I checked in volunteer/report/, events were not coming in a dropdown. I'll see it again and attach a screenshot.

**Comment by anweshknayak** [comment]
I have created a pull request. #400 
Please check

**Comment by smarshy** [comment]
@tapasweni-pathak Currently the event and jobs dopdown only shows events/jobs the volunteer has signed up for. Does this need to be extended to include all events/jobs?

**Comment by tapasweni-pathak** [comment]
@smarshy No.

**Comment by Himanshi-Khandelwal** [comment]
solved this issue and has created pull request.

**Comment by arunikayadav42** [comment]
I want to get started with this issue.Can somebody please help me out?

**Comment by tapasweni-pathak** [comment]
Sure,@arunikayadav42. Did you open the page volunteer/report/, how do you see the event field?
