### ISSUE TITLE
Show job name suggestion as dropdown

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#383]
/volunteer/report/ 

Let the user first select and event
|__ show related jobs
|__ Otherwise keep it blank

**Comment by anweshknayak** [comment]
I have created a pull request. #400 
Please check

**Comment by Himanshi-Khandelwal** [comment]
I wish to solve this issue . Can anyone help where can I find reports option for creating the report so that I can make dropdown box.

**Comment by Himanshi-Khandelwal** [comment]
I wish to know whether the drop down box contains events for the volunteer who has signed up or all the events listed till now?

**Comment by anweshknayak** [comment]
I actually tried solving this. Job name and event name (#382)  are not showing up in the drop down menu.

**Comment by Himanshi-Khandelwal** [comment]
I tried and it is showing names in the drop down box after some changes for the event name.

**Comment by Himanshi-Khandelwal** [comment]
I tried and it is showing names in the drop down box after some changes for the event name.

**Comment by anweshknayak** [comment]
events for which the volunteer has signed up for. if it is the case create a PR.

**Comment by Himanshi-Khandelwal** [comment]
@smarshy I have solved this issue and have submitted pull request #429 , please review.

**Comment by arunikayadav42** [comment]
I want to get started with this issue.Can somebody please help me out?

**Comment by tapasweni-pathak** [comment]
ref https://github.com/systers/vms/issues/382#issuecomment-352006318, @arunikayadav42.

**Comment by anjali-dhanuka** [comment]
Please use the issue template.
