### ISSUE TITLE
New release after GSOC 2016

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#385]

**Comment by tapasweni-pathak** [comment]
@smarshy Are you planning to submit that BrowserStack related work now? If it will take time, I will release a semantic version of VMS. I have no issues in you submitting it later.

**Comment by smarshy** [comment]
@tapasweni-pathak It would take some time. Travis integration is still pending and  the setup has to be done for more files now. I will open a related issue for that

**Comment by tapasweni-pathak** [comment]
[Done](https://github.com/systers/vms/releases/tag/v0.3.2). Closing this.
