### ISSUE TITLE
Test for simplify job failing

### ISSUE THREAD

**Issue by smarshy** [systers/vms#386]
In this [test](https://github.com/systers/vms/blob/develop/vms/administrator/tests/test_formFields.py#L422), the event dates are not displayed as expected even after selecting an event which results in a test failure. The reason behind this is still unclear.

**Comment by bob-the-buildr** [comment]
If nobody is working on this, I would like to work on this issue.

**Comment by anjali-dhanuka** [comment]
Please  use the issue template
