### ISSUE TITLE
Add comments for failing tests

### ISSUE THREAD

**Issue by smarshy** [systers/vms#387]
Few of the tests/parts of tests are commented out in the test scripts. However, the reason or related issue/bug is not mentioned clearly for some of these tests. For eg. [Test 1](https://github.com/systers/vms/blob/develop/vms/administrator/tests/test_formFields.py#L422), [Test 2](https://github.com/systers/vms/blob/develop/vms/administrator/tests/test_formFields.py#L341) etc.

Add appropriate comments to link these commented out tests in the scripts to correct bug numbers. For any help, you can refer to [this](https://github.com/systers/vms/blob/develop/aut_docs/Documented_failures.md) file

**Comment by Monal5031** [comment]
already done. in #779
