### ISSUE TITLE
Installation using virtual environment

### ISSUE THREAD

**Issue by anweshknayak** [systers/vms#388]
As I went through the installation guide there was no mention of virtual environments like virtualenv being used. I think it should be mentioned in the guide as the installation process is quite simple. Without the virtual environment which I tried it created many package conflicts. 
So you may consider virtualenv or some other alternative.

**Comment by tapasweni-pathak** [comment]
We use one vagrant VM per project, so there is no direct reason that we should use virtualenv. 

>Without the virtual environment which I tried it created many package conflicts. 
Did you follow all the instructions in the installation guide? Did you setup the VM?

**Comment by smarshy** [comment]
@anweshknayak virtual environment is optional, you could use it or install everything on the VM itself. Were there issues with installation without virtual environments?

**Comment by anweshknayak** [comment]
Yes I did follow the instructions as provided in the installation guide but the process took quite a long time and over that faced some issues too even that took some time. Alternatively I used virtualenv which took like less than 10 minutes to setup the whole thing.

**Comment by tapasweni-pathak** [comment]
There are lot of other advantages of using vagrant per VM over virtualenv. 

Thanks for the finding. I will try it myself, discuss and open an issue if that makes it easier for contributors to get started with the project.

Closing this one.
