### ISSUE TITLE
Unwanted lines of code

### ISSUE THREAD

**Issue by amruthasangeeth** [systers/vms#389]
There are [unwanted lines](https://github.com/systers/vms/blob/bfdb72bd6a9ffa07fa8209498fea4f227e392823/vms/job/views.py#L35-L99) of code in job/views.py. There is still a function based  view for creating a job remaining in the code. It needs a code clean up. Removal of extra spaces between functions are also needed.
Reference #365

**Comment by kaleoh** [comment]
I've forked and removed some spaces... but what do you mean "there is still a function based view for creating a job remaining in the code?"
I am new to contributing to projects in general (this is my first), and obviously new to VMS, sorry if this is a stupid question.

**Comment by amruthasangeeth** [comment]
@kaleoh There was a migration for VMS from **function based views** to **class based views.** The lines I have linked is a function based view to create a Job which is not needed for the present code. The same function has been migrated to class based view **CreateJobView**.

**Comment by kaleoh** [comment]
I see, so clean entire file, remove what was linked. Thanks.

**Comment by amruthasangeeth** [comment]
@kaleoh Yes, we need to remove those linked lines.
