### ISSUE TITLE
Test for view `/registration/signup_volunteer/` failing

### ISSUE THREAD

**Issue by jayesh92** [systers/vms#39]
- This view is to register a new volunteer into the system
- When I was testing this view, It gives `500 Server Error`. After struggling a lot to find if the reason is due to wait for page load or any other selenium issue, I found that the problem is in the view itself
- Problem is at https://github.com/systers/vms/blob/develop/vms/registration/views.py#L67 . `organization_list` is output of list of organization from `services.py` . 
- If it's empty (like in my case), view redirects to `organization/add_organizations.html` . There is no such template corresponding to this. There is a create template.
- There is no need to check for `organization_list`. Since, we already have a field for other-organization if it's not in the dropdown. We can use the logic for inserting this organization first and then get the id of this newly inserted org and use it for the foreign_key relationship of newly created volunteer object.

@Nerdylicious @willingc @vubo

**Comment by willingc** [comment]
@jayesh92 @vubo Is this resolved or are tests still failing?

**Comment by vubo** [comment]
@jayesh92 could you please show your unit test?

**Comment by jayesh92** [comment]
@vubo https://github.com/jayesh92/vms/blob/master/vms/registration/tests/test_functional_volunteer.py tests corresponding to this issue.
You can see the hack in setUp method.
@willingc I haven't tested it again after fetching vubo's changes. I'll let you know after doing this

**Comment by vubo** [comment]
@jayesh92 you can find in the installation guide http://vms.readthedocs.org/en/latest/Installation%20Guide/:

>There needs to be at least one organization in the organization_organization table in order to register for an account (this be changed later). Add Google as an organization:

>insert into organization_organization values (1, 'Google');

So, if you follow the instructions, the error should not occur.

**Comment by jayesh92** [comment]
@vubo I have read this instruction earlier but my point is since we are already having an unlisted org field, why do we force to add one org earlier ?

**Comment by vubo** [comment]
@jayesh92 I think it does not matter how we add the first organization. If we set up the database, why not just add the first organization, as described in the installation guide?

**Comment by jayesh92** [comment]
as everyone suggests, I just pointed out the case. We can consult @willingc for more clarity on this issue

**Comment by willingc** [comment]
@vubo and @jayesh92: I can think of another edge case where the database may contain no organizations. The case where an admin deletes all the organizations in the database. I wonder what happens if we try that since I honestly don't know if a) we could do it as an admin; b) if the results would be the same as starting with an empty organization table.

I'm going to let you both think about what would be best for the end user. I would like you to reach a consensus on the best approach. Try to agree on a reasonable approach now and file an issue for a future enhancement if needed.

Happy to answer more questions as needed. I will be on vacation most of this week so I may be slow to respond. My husband's 50th birthday :cake:

**Comment by vubo** [comment]
@willingc congratulations, have a great week :bouquet:

a) - no, an admin can not delete all the organizations in the database. The error will be displayed:

![image](https://cloud.githubusercontent.com/assets/7673323/8972775/5db8f632-365d-11e5-8d6b-9d8948f9fe14.png)

**Comment by smarshy** [comment]
@tapasweni-pathak The hack has been included and the test is passing. The issue does not seem to exist now.
