### ISSUE TITLE
Max volunteers field can be edited with invalid number

### ISSUE THREAD

**Issue by smarshy** [systers/vms#392]
After a shift is assigned to multiple volunteers, it is possible to update the max volunteers field for that shift with a number lesser than that of the assigned volunteers. While editing the field, there should be a check to ensure that number of assigned volunteers is not out of range

**Comment by tapasweni-pathak** [comment]
It is good to even label the issue at the of opening it. It helps contributors. You already know this, I guess. :)

Let me know if you don't have the authorization for this.

**Comment by smarshy** [comment]
I don't seem to have the permission for this, unable to select issues from the list

**Comment by smarshy** [comment]
+ probable gci
