### ISSUE TITLE
Test for phone validation

### ISSUE THREAD

**Issue by smarshy** [systers/vms#394]
Test for phone validation is missing, the functionality was added - [here](https://github.com/systers/vms/blob/develop/vms/registration/phone_validate.py)

**Comment by mehak6669** [comment]
@smarshy : Hey! I fail to understand what is meant by the issue. Can you please elaborate a bit?

**Comment by anweshknayak** [comment]
You need to write unit tests for registration view. (http://toastdriven.com/blog/2011/apr/10/guide-to-testing-in-django/)  See (https://github.com/systers/vms/tree/develop/vms/registration/tests) for more.

**Comment by anweshknayak** [comment]
@mehak6669 you working on this ? @smarshy I can do this

**Comment by anweshknayak** [comment]
@smarshy as you see tests for cities_lights(https://github.com/yourlabs/django-cities-light/tree/master/cities_light/tests)  and phone-numbers (https://github.com/daviddrysdale/python-phonenumbers/tree/dev/python/tests) are  there already any need of testing required in this too ? If Yes upto which part I need to put checks as in to test. Certainly the library has been tested so how exactly to proceed ?

**Comment by smarshy** [comment]
@anweshknayak Well, you don't have to test the library but write a unit test for the validate_phone(my_country, my_phone) function. 
First, try to understand what the function does - what its inputs and expected outputs are. _You don't have to test this for every country in the database._ Think of the possible edge cases and possible argument value types here (I can think of 4 but maybe you will find more)

**Comment by anjali-dhanuka** [comment]
closed #826
