### ISSUE TITLE
Badge doesn't show exact coverage

### ISSUE THREAD

**Issue by smarshy** [systers/vms#395]
The coverage does not show exact coverage; While running tests, files which don't need tests need to be removed from the configuration

**Comment by tapasweni-pathak** [comment]
Did you get the chance to submit these issues on the spreadsheet which May and Kesha shared?

**Comment by italo-batista** [comment]
Hi, I would like to help. :)
I see */tests/* are already out from coverage run. I added few lines at .coveragerc. Please check my pull request! {:
