### ISSUE TITLE
Simplify editing of job

### ISSUE THREAD

**Issue by smarshy** [systers/vms#396]
While editing a job, there is a check to ensure that the included shifts are not falling outside the new date range. It may be helpful to show the range of dates while allowing the user to edit the form.

**Comment by smarshy** [comment]
++gci

**Comment by PhoeniXkrypT** [comment]
I hadn't realised that this was a task for GCI. It did not have the "GCI" tag in the issues page, so I went ahead with writing a patch for it.

**Comment by anjali-dhanuka** [comment]
Please use the issue template.
