### ISSUE TITLE
Notifications for volunteers

### ISSUE THREAD

**Issue by smarshy** [systers/vms#399]
Whenever an admin enters or edits hours for the volunteer, an alert can be sent (via text/sms) to the volunteer

**Comment by anweshknayak** [comment]
Can you specify a bit more ? How actually to proceed ? which library to use

**Comment by smarshy** [comment]
@anweshknayak There are many possible ways of doing this - Twilio/django.core.mail etc. However, please don't restrict yourself to these. You can research libraries/APIs used by existing projects and software. If you feel they are suitable and well-maintained, do post your suggestions here first.
@tapasweni-pathak Do you have any suggestions?

**Comment by tapasweni-pathak** [comment]
@smarshy Twilio API is the only one which came into my mind. I have tried it. It makes it very easy to send messages or calls on phones. They have a free trial period but then it is charged, for more also users it is charged. We need to find some open source alternative with good documentation and support. How we will be using that in our code for our conditions also needs to be analyzed. 

Feel free add your suggestions whoever plans to implement this.

**Comment by Anh3h** [comment]
Can i take up the task??? i want to use django-simple-sms to implement it. Twilio would have been better or easier but it comes at a cost ...

**Comment by Anh3h** [comment]
So django-simple-sms still want me to implement the sms gateway with twilio so i decided to implement the entire sms notification with twilio. All you need is a twilio account so u can by a valid number (sender's number), well am using a trial account for the main time. Hope its ok!!!

**Comment by mish24** [comment]
In case of sending the notification via email, the Sparkpost API is quite good. You'll just need to alter some setiings by adding a SPARKPOST_API_KEY. I will try to resolve the issue using Sparkpost! Hope it's okay @tapasweni-pathak

**Comment by anweshknayak** [comment]
anyone doing this ? @smarshy ?

**Comment by anjali-dhanuka** [comment]
closed #714
