### ISSUE TITLE
volunteer model regex does not match with volunteer form regex

### ISSUE THREAD

**Issue by jayesh92** [systers/vms#40]
- Volunteer model view allows `-` as a valid character. https://github.com/systers/vms/blob/develop/vms/volunteer/models.py#L11
- Volunteer form does NOT allow `-` as a valid character. https://github.com/systers/vms/blob/develop/vms/volunteer/forms.py#L12
- As a result, during a test I can register a volunteer with a `-` but cannot enter a `-` in the form for `Volunteer Search` functionality
- Test fails

@Nerdylicious @vubo @willingc

**Comment by willingc** [comment]
@jayesh92 good catch :) Thanks for filing the issue

**Comment by vubo** [comment]
@jayesh92 thank you! I fixed it.

**Comment by tapasweni-pathak** [comment]
This can be closed now, I think.
