### ISSUE TITLE
Implement the about page

### ISSUE THREAD

**Issue by smarshy** [systers/vms#403]
Currently , the about tab link does not lead anywhere. Direct it to a new page where you can describe the project features and also include details about the development history of VMS through GSOC, GCI and other contributors.

Related to [#241](https://github.com/systers/vms/issues/241)

**Comment by tapasweni-pathak** [comment]
Whoever picks this please use closes for #241 and this, both.

**Comment by Kashyap12** [comment]
Hi @tapasweni-pathak , can I take this up, and I am quite new to opensource.. and also I read ur answers on quora :)

**Comment by tapasweni-pathak** [comment]
Thanks for showing interest @Kashyap12. Issues tagged as first-timers-only are for people who haven't submitted any pull request till now.  

You can pick other easy issues. Let us if you get stuck or need help in resolving any.

**Comment by Anh3h** [comment]
OK.. Am new to systers .. Haven't been well went i joined about some weeks ago but am fine now and i will take up the task please

**Comment by febinmoideen** [comment]
I've created a pull request for this issue. Please review.

**Comment by ihsavru** [comment]
Hi! Can I work on this?

**Comment by tapasweni-pathak** [comment]
Please feel free to work on any open issue. Issues are not assigned, pull request will be reviewed in the order they were created.

**Comment by anjali-dhanuka** [comment]
Do we need to remove the about page link?

**Comment by tapasweni-pathak** [comment]
Yes, removing the about would be 👍

**Comment by tapasweni-pathak** [comment]
closed w/ 305af22622ad3b07e92ed3cebd30e18e67fa06b0.

**Comment by anjali-dhanuka** [comment]
closes #241
