### ISSUE TITLE
Simplify logging of hours

### ISSUE THREAD

**Issue by smarshy** [systers/vms#409]
While entering/editing hours in the log hours form, there is no helper information provided about the start and end time of the shift.

**Comment by smarshy** [comment]
+probable gci

**Comment by PhoeniXkrypT** [comment]
I hadn't realised that this was a task for GCI. It did not have the "GCI" tag in the issues page, so I went ahead with writing a patch for it.

**Comment by tapasweni-pathak** [comment]
No issues, @PhoeniXkrypT. We will review them in a while. Thank you!
