### ISSUE TITLE
Refactor Job unit tests

### ISSUE THREAD

**Issue by willingc** [systers/vms#41]
Let's refactor the following:

- [ ] Import statements - I would like to be conservative on importing the libraries needed for testing. Avoid * imports. Do not import libraries that are not used (I don't think the auth import is needed currently; let's not add until needed). General style: python standard library imports - blank line - django imports - blank line - application specific imports.
- [ ] Docstring - One line describing individual unit tests
- [ ] File - spaces vs. tabs - double check that all tabs are converted to spaces before check in (there is usually an editor setting for this
- [ ] DRY - don't repeat yourself - a reasonable goal which may or may not apply to these tests but important to recognize when developing

**Comment by vubo** [comment]
https://github.com/systers/vms/pull/44

**Comment by willingc** [comment]
@vubo Please double check the import *.

**Comment by vubo** [comment]
@willingc I think that this issue can be closed: https://github.com/systers/vms/blob/develop/vms/job/tests.py What do you think?

**Comment by willingc** [comment]
@vubo Thank you! Yes, this can be closed :+1:
