### ISSUE TITLE
Update Vagrant

### ISSUE THREAD

**Issue by smarshy** [systers/vms#419]
VMS now runs on 1.7.1. Update vagrant to use django 1.7.1 instead of 1.6

**Comment by anweshknayak** [comment]
I can work on this

**Comment by mish24** [comment]
Hi @smarshy! I just had a doubt. The project currently uses django 1.7.1. Would it be wise to update it to use >1.8? I had to remove all the initial migrations as they were causing build failure.

**Comment by anweshknayak** [comment]
@smarshy can you tell me where to make the changes ? I couldn't find the respective file
