### ISSUE TITLE
Refactor event unit tests

### ISSUE THREAD

**Issue by willingc** [systers/vms#42]
Similar to issue #41, let's refactor the event unit tests:

- [ ] Import statements
- [ ] Docstring
- [ ] File - spaces vs. tabs
- [ ] DRY - don't repeat yourself - a reasonable goal which may or may not apply to these tests but important to recognize when developing

**Comment by tapasweni-pathak** [comment]
Shouldn't this be closed?

**Comment by willingc** [comment]
Yes, good catch. PR #46 closes this issue.
