### ISSUE TITLE
Shift duration shows error

### ISSUE THREAD

**Issue by mish24** [systers/vms#439]
When we are trying to create shifts, if shows an error when I put the start_time at 23:00 and end_time at 00:00. But a shift can run that time too I suppose? How do we compare times exactly in this case?

**Comment by bob-the-buildr** [comment]
This is because 00:00 represents the start of the date, so it is a time before 23:00. We would probably need to have a provision for an end-date of the shift, for shifts spanning the night. Or it could simply be logged in two different shifts from 23:00 to 23:59, and the 00:00 on the next date to whatever is the end-time.

**Comment by mehak6669** [comment]
In this case. we can still help by using start_time as 23:00 and end_time as 24:00. However, let it start at 23:00 and end midnight, then date of the shift shall play important role. I will add the date option for shift end, if you allow.

**Comment by mish24** [comment]
@mehak6669 Umm, I'm no one to allow or disallow. I'm not a member! However, I think the best way to approach this is to convert timings to 12 hour format. In what you're saying, what would we do if the shift is to take place from 11 pm to 1 am? Or maybe adding the date along with the time may seem more logical, right?

**Comment by mehak6669** [comment]
Hey! That's what I meant to mention date. But as i ponder on your thought
of having a 12 hrs. clock, it seems simpler and a better approach. Thanks
for the idea.

**Comment by necessary129** [comment]
@mish24 If the shift was from 11 pm to 1 am, in the 24-hour format it would be from 11:00 to 13:00. It is also good.

**Comment by mehak6669** [comment]
No. The shift we are talking about is from 11 PM to 1 AM. In 24hr format,
it will be from 23:00 to 13:00.

*Regards*

*Mehak Goyal*
*Undergraduate Student, Class of 2018*
*Department of Computer Science and Engineering*
*Indian Institute of Technology (BHU), Varanasi*
*Varanasi - 221005*
+918127032541 <https://in.linkedin.com/pub/mehak-goyal/ab/327/437>


On Mon, Jan 23, 2017 at 7:03 PM, Shamil K Muhammed <notifications@github.com

**Comment by necessary129** [comment]
Oh! My fault then! 😅

**Comment by smarshy** [comment]
@mish24 @mehak6669 No, the shift cannot run in that time. Shift timings from 11PM to 1AM (which would be 23:00 to 01:00) are not possible as the date changes in that case. Same logic goes for 11PM to 12AM - the date would change as soon as it strikes 12.
The shift runs only for one day; the create/edit shift form will allow you to add details for a shift on a specific date. (This is decided as the current behaviour. If there is a need to allow shifts to span across multiple dates in future, then these timings are possible.)

**Comment by mish24** [comment]
@smarshy Oh alright! It wasn't mentioned anywhere so I had no idea. Thanks for clarifying!

**Comment by mish24** [comment]
@smarshy Yeah after your clarification I guess it is. Maybe we can display a better error message I suppose?

**Comment by mish24** [comment]
#440 Just a small edit to display the correct message
