### ISSUE TITLE
basePage imported incorrectly

### ISSUE THREAD

**Issue by bob-the-buildr** [systers/vms#441]
In all the pages in pom/pages/ the line 
`from basePage import *`
is throwing an error during tests. It should be 
`from pom.pages.basePage import *`

**Comment by Himanshi-Khandelwal** [comment]
@bob-the-buildr in my case it is giving error when from pom.pages.basePage import *
(.venv)himanshi@himanshi-HP-Notebook:~/vms/vms/pom/pages$ python administratorReportPage.py 
Traceback (most recent call last):
  File "administratorReportPage.py", line 2, in <module>
    from pom.pages.basePage import *
ImportError: No module named pom.pages.basePage

**Comment by bob-the-buildr** [comment]
Is it not giving errors when you don't change it to pom.pages.basePage? I gave me errors for other pages such as eventsPage, homePage etc.

I couldn't test it after making the changes since I got problems due to proxy in my hostel. I'll check this once again once I fix those problems.

**Comment by smarshy** [comment]
@bob-the-buildr Closing the issue for now. Please reopen if you are still facing problems
