### ISSUE TITLE
Dates hardcoded in tests

### ISSUE THREAD

**Issue by payal97** [systers/vms#443]

**Comment by mish24** [comment]
@payal97 Can I work on this?

**Comment by bob-the-buildr** [comment]
@mish24  I've already done half the work. I'll submit a pull request soon. :)

**Comment by payal97** [comment]
@mish24 I've already done half the work. I'll submit a pull request soon. :)

**Comment by tapasweni-pathak** [comment]
@payal97 Thanks for the issue Payal. You contributed to VMS by creating the issue.

Once you open a issue anyone can pick and work on it.

@mish24 @payal97 Both of you can work on this. One who submits a pull request first will get the review first. Anyone is free to pick issues opened on VMS project.

**Comment by bob-the-buildr** [comment]
@tapasweni-pathak @payal97  If no one else is working on it, can I submit a PR?

**Comment by Himanshi-Khandelwal** [comment]
is anyone working on it?

**Comment by tapasweni-pathak** [comment]
Thanks for showing interest to work on the issue. Issues are not assigned. Feel free to submit a pull request. Pull requests will be reviewed/merge in order they are submitted.

**Comment by anjali-dhanuka** [comment]
Please use the issue template
