### ISSUE TITLE
Logged hours not shown properly in the Report View

### ISSUE THREAD

**Issue by mish24** [systers/vms#444]
![screenshot from 2017-02-01 13-55-29](https://cloud.githubusercontent.com/assets/24610197/22483089/c0ceac22-e821-11e6-8d26-655c2e0bb735.png)

There is an error in the logged hours and total hours generation in the report view. I've made the sufficient changes. Can I send a PR for the same?

**Comment by mish24** [comment]
@smarshy This is an error, right? I've resolved this anyway, shall I submit a pull request?

**Comment by smarshy** [comment]
@mish24 I cannot understand the error from the snapshot. The duration is properly summed up to give the total hours.
please define and elaborate the steps to recreate this error

**Comment by mish24** [comment]
@smarshy Actually I think it's a mistake on my part. I forked the repo and cloned it. But I think it wasn't updated with the development branch and the issue was already resolved there. Can you please guide me on how to actually update the forked repository? 
Also, apart from this, I don't think there's any problem. Sorry! You can close this issue.

**Comment by smarshy** [comment]
@mish24 You can refer to [this]( https://help.github.com/articles/syncing-a-fork/) for updating your fork. 
I think the bug you are referring to had been fixed by #404  around 2 weeks back.
If it is not the same thing, feel free to open an issue. Please include steps to replicate the bug in it.
