### ISSUE TITLE
Texts are Overflowing in shift/volunteer_search view 

### ISSUE THREAD

**Issue by anweshknayak** [systers/vms#445]
![error4](https://cloud.githubusercontent.com/assets/8139783/22610063/a61de48c-ea89-11e6-8add-3d547d39b93f.png)

Related to #161 
This view has been tested in Tablet view. The same error can be reproduced for tablet screen size.

**Comment by tapasweni-pathak** [comment]
@anweshknayak Thanks for this issue!

**Comment by swekshajha12** [comment]
Hey  Swechha here! Can I take up this issue?

**Comment by swekshajha12** [comment]
I went through the codebase and the corresponding css files for the volunteer_search.html file seems missing. I need to create a css file and link it to this html for this issue . Kindly tell me if I am wrong or if you have anytthing else on your mind ? 
Thanks !

**Comment by anweshknayak** [comment]
Use Inspect element. Find the corresponding css element. Make changes accordingly.

**Comment by swekshajha12** [comment]
I did , but the no css elements are shown.
![volunteer_search](https://user-images.githubusercontent.com/22135941/31072510-d4c9a79e-a785-11e7-806d-762eb655fe48.png).

**Comment by anweshknayak** [comment]
No.  Not on the html page. You see the screenshot I have posted above. Go to that section. Do inspect element on that. Not on the html page. Hope you get it

**Comment by swekshajha12** [comment]
Sorry! You mean in the development environment right?

**Comment by anweshknayak** [comment]
Yup.

**Comment by swekshajha12** [comment]
Thanks !

**Comment by anjali-dhanuka** [comment]
Please use the issue template.
