### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Himanshi-Khandelwal** [systers/vms#448]
import error coming when performing python manage.py migrate
ImportError: No module named cities_light  

this was coming even after installing requirements.txt

**Comment by tonythomas01** [comment]
-1. Should not happen. Can you paste the output of: 

`pip install -r requirements.txt` from the right location, 

and then the output of 

`pip freeze | grep "django-cities-light"`

**Comment by tapasweni-pathak** [comment]
@Himanshi-Khandelwal Is this issue resolved for you?
