### ISSUE TITLE
Add a project style guide to documentation

### ISSUE THREAD

**Issue by willingc** [systers/vms#45]
It would be helpful to have a short style guide for the vms project.

I am assigning this to myself to pair with Vanda on creating this document.

**Comment by willingc** [comment]
One resource to reference: https://docs.djangoproject.com/en/1.8/internals/contributing/writing-code/coding-style/#

**Comment by vubo** [comment]
It's a great idea, I like it :+1:

**Comment by willingc** [comment]
@vubo Thanks. I will keep you posted when I have Vanda start on this later in the week.

**Comment by willingc** [comment]
@vubo I have set milestone for 'GHC' Grace Hopper Celebration. The issues that I am putting in this are ones that may be suitable for attendees of Open Source Day. You are free to work on them but I don't expect that they will be completed for GSoC :smile:

**Comment by tapasweni-pathak** [comment]
@willingc Are we in a position to close this?

**Comment by willingc** [comment]
@tapasweni I think we should close it. Since it fell more under nice to have vs. critical path. I will close it now. We can always reopen in the future.
