### ISSUE TITLE
Countries should appear as dropdowns in volunteer search and sign up forms

### ISSUE THREAD

**Issue by namanrjpt** [systers/vms#454]
Right now the users have to manually type the country in the fields. It'd be great if users can select country through a drop down list. In that case, even validation won't be required. Also, this is implemented already in systers/portal which vms is going to be a part of (correct me if i'm wrong :smile:)

more of an enhancement, IMO.

**Comment by tonythomas01** [comment]
Should work by changing the https://github.com/systers/vms/blob/develop/vms/volunteer/forms.py#L42 to a ChoiceField (https://docs.djangoproject.com/en/1.11/ref/forms/fields/#choicefield). 

Feel free to submit a PR.

**Comment by RiaPant** [comment]
@tapasweni-pathak Can I work on this?

**Comment by Himanshi-Khandelwal** [comment]
is anyone working on this one?

**Comment by Namrata96** [comment]
I would like to work on this issue if no one else is. Please let me know.

**Comment by tapasweni-pathak** [comment]
You can work on any open issue. Issues are not assigned. Pull request will be reviewed in the order they were created.

**Comment by anjali-dhanuka** [comment]
What I think is first we should ask the user to fill up his country. Then accordingly valid states will appear in the drop down list. After that he will select his city following the similar procedure. If noone is working on the issue, I would like to take it up.

**Comment by tapasweni-pathak** [comment]
@anjali-dhanuka Sounds good! But all should be in dropdown, no manually typing it.

**Comment by anjali-dhanuka** [comment]
Yeah sure!!

**Comment by anjali-dhanuka** [comment]
I was looking for some django packages for its implementation. I read about django-cities, django-cities-light and many others but they are not compatible with django-1.6.5(vms uses 1.6.5). So I was thinking to do it manually i.e import required database and using jquery for respective choices. Shall I go this way?

**Comment by tapasweni-pathak** [comment]
Yeah, possible for you to work on migrating VMS to latest packages? Let me know if you need any help.

**Comment by anjali-dhanuka** [comment]
Do you mean to say that I start porting vms to some latest django version?

**Comment by pranita-s** [comment]
Can the solution be based on HTML and Javascript ? (not using utilities such as django-cities)

**Comment by anjali-dhanuka** [comment]
@pranita-s we will need to populate our db by cities, countries and states which will require python libraries so it can't just be done by mere HTML and javascript. Well, I have implemented this. You can see https://github.com/systers/vms/pull/545

**Comment by pranita-s** [comment]
@anjali-dhanuka Thank you for the guidance. I will study details of #545 and work accordingly

**Comment by anjali-dhanuka** [comment]
@pranita-s I wanted to tell you that I have already resolved the issue and created a pr for that too.

**Comment by pranita-s** [comment]
Okay! Thanks for informing, I will work on another issue

**Comment by anjali-dhanuka** [comment]
closed #826
