### ISSUE TITLE
Keep the event to last changed value

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#458]
1. Go to /job/create/.
2. Select an event other than first.
3. Add a job with erroneous condition.

Event is reset to first event from the list.

**Comment by namratab94** [comment]
@tapasweni-pathak Can I work on this?

**Comment by tapasweni-pathak** [comment]
Sure, please go ahead.

**Comment by Himanshi-Khandelwal** [comment]
@tapasweni-pathak anyone working on it?

**Comment by namratab94** [comment]
Yes, I am.

**Comment by tapasweni-pathak** [comment]
@Himanshi-Khandelwal @namratab94 Thanks for showing interest to work on this issue both of you. 

Feel free to submit a pull request. Issue is not assigned to anyone. Pull requests are reviewed/merged in order they come.
