### ISSUE TITLE
Installing vms with python 3.6 gives htmlparser error

### ISSUE THREAD

**Issue by bhavya-reddy** [systers/vms#459]
`AttributeError: module 'html.parser' has no attribute 'HTMLParseError'`

When we try to install vms on python 3.6 , we are facing errors with above message, this requires us to upgrade our project to a newer version of Django.

https://stackoverflow.com/questions/34827566/attributeerror-module-html-parser-has-no-attribute-htmlparseerror

**Comment by tonythomas01** [comment]
For a quick fix, setup a virutalenv on python 2.7 -- try https://stackoverflow.com/questions/1534210/use-different-python-version-with-virtualenv -- and work on it. 

But you are right, we should ugprade at some point.

**Comment by tapasweni-pathak** [comment]
Closing as related to #457. Currently VMS runs on Python 2.7 and Django 1.7.4.
