### ISSUE TITLE
Hide secret_key in settings.py

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#460]
- [ ] Update [.travis.yml](https://github.com/systers/vms/blob/develop/.travis.yml); i.e., add secret_key in before script
- [ ] Update [settings.py](https://github.com/systers/vms/blob/develop/vms/vms/settings.py#L14)
- [ ] Update Installation instruction
- [ ] Update Docker instruction in README
- [ ] Test

secret key should be foobarbaz.

**Comment by codejockie** [comment]
Stumbled upon this on Twitter; as a first timer I would like to take work on this.

**Comment by tulikavijay** [comment]
I want to work on this...can you please let me know how to go about this. Do i need to encrypt the key in .travis.yml file? And how should i hide it in settings.py . Any feedback is appreciated!
