### ISSUE TITLE
Add Sphinx documentation to vms/docs

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#461]
- [ ] Add [Sphinx](http://www.sphinx-doc.org/en/stable/) documentation to vms/docs
- [ ] Add instructions to allow the developer to build it in local and view, in README.md

For more information on semantics and builds, please refer to the Sphinx [official documentation](http://www.sphinx-doc.org/en/stable/contents.html).

**Comment by tulikavijay** [comment]
I want to do this. Can you please guide me , how do I add the existing docs  to sphinx ?

**Comment by shreyateeza** [comment]
@tapasweni-pathak I want to work on this. Please assign this issue to me.

**Comment by pranita-s** [comment]
@tapasweni-pathak I read about Sphinx, I understood its a document generator with varied themes available. vms/docs has many .md documents. Does this issue mean, all those documents need to be converted into Sphinx documentation with a certain theme ? Please help !

**Comment by tapasweni-pathak** [comment]
@prachi1210 yes, we would want to have a Sphinx documentation for all.

**Comment by sammy1997** [comment]
@tapasweni-pathak @kamsuri Is this issue still open ? And are the Outreachy tagged issues now available or GSoC or open contributions ?

**Comment by Pranavya** [comment]
Is this issue need to be completed yet? @tapasweni-pathak

**Comment by anjali-dhanuka** [comment]
PLease use the issue template
