### ISSUE TITLE
Password Authentication failed for user vmsadmin

### ISSUE THREAD

**Issue by swekshajha12** [systers/vms#463]
Unable to login to the postgres client with the vmsadmin user 
On using the following command :
psql -U vmsadmin -d postgres -h localhost -W
I get the following error:
![sys](https://user-images.githubusercontent.com/22135941/31237370-69356fae-aa14-11e7-92cc-439b9f483956.jpg)

**Comment by swekshajha12** [comment]
This can be resolved by 
(i) Find all the  pg_hba.conf files using  sudo find / -type f -iname pg_hba.conf
(ii) Make the following changes in only the files which are being used by VMS 
Change the line local all postgres peer to local all postgres md5
change the line local all all peer to local all all md5
(iii) Restart the postgresql client and then login to the postgres client with the vmsadmin user
 This error may arise when there are other projects which have pg_hba.conf files and you are making changes to them.

**Comment by tapasweni-pathak** [comment]
@swekshajha12 Please add your system/environment details.
