### ISSUE TITLE
Create custom 404, 403, 500 error pages

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#465]
[Django documentation](https://docs.djangoproject.com/en/1.11/topics/http/views/#customizing-error-views)

**Comment by swekshajha12** [comment]
Hey! Till I configure the development environment properly on my computer , can I please work on it?

**Comment by tapasweni-pathak** [comment]
Thanks for showing interest to work on this issue. Feel free to submit a pull request. Issues are not assigned to anyone. Pull request are reviewed/merge in order they come.

**Comment by deepikasunhare** [comment]
if @swekshajha12 is no longer working in this issue, can I work in this??

**Comment by swekshajha12** [comment]
Hey! I have already submitted a pr for this! If you want to , you can work!
