### ISSUE TITLE
Integrate flake8 on travis

### ISSUE THREAD

**Issue by tapaswenipathak** [systers/vms#478]
## Description
As a developer,
I need to ensure that the project has some code checker enabled,
so that it can follow standard code style guidelines

## Mocks
N/A

### Update [Required]
- [x] Modify setup.cfg for flake8 settings
- [x] Add command in .travis.yml to run flake8 on repo
- [ ] Make necessary changes
- [ ] Document the flake8 run in docs.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
First two task will take approx 30 mins.
third task will take 2-3 hours

**Comment by Prakharsvnit** [comment]
I am working on this issue.I am not sure about travis implementation,but i would like to give it a try.

**Comment by kriti21** [comment]
flake8 is already added in requirements.txt 
Only command for running it needs to be included in .travis.yml
Please correct me if I am wrong. @tapasweni-pathak

**Comment by Ayukha** [comment]
@tapasweni-pathak  Can i work on it ?

**Comment by anjali-dhanuka** [comment]
@Ayukha as u can see @kriti21 has already made a pr. You should refer some other issue.

**Comment by Monal5031** [comment]
@tapasweni-pathak Can I please work on this issue, the latest commit or comment on the PR made by @kriti21 was of Jan 15.

**Comment by utkarsh2102** [comment]
Hi @anjali-dhanuka, @tapasweni-pathak,
I'm willing to take up the task as I'm a new comer here.
It'd be great to solve this issue and get going.
Could you please assign the same to me?

**Comment by Monal5031** [comment]
Completed in #754
