### ISSUE TITLE
Import error : No module named phonenumbers

### ISSUE THREAD

**Issue by swekshajha12** [systers/vms#482]
While running the development server , I get this error! While trying to install it , I get  
![installing](https://user-images.githubusercontent.com/22135941/31621116-94b44e2a-b2b6-11e7-9432-bb17eb1d8493.png)
(System: Ubuntu 16.04 Environment: Ubuntu 14.04 in virtualenv ,Vagrant 1.8.6 )

**Comment by swekshajha12** [comment]
I was able to resolve it by following
1)Download source from https://github.com/daviddrysdale/python-phonenumbers 
2)install phonenumbers using python setup.py install
Remove the broken packages by using sudo rm <broken packages>

**Comment by tapasweni-pathak** [comment]
This should have been installed when you ran requirements.txt, it didn't?

**Comment by swekshajha12** [comment]
No , it didn't!

**Comment by tapasweni-pathak** [comment]
😕
