### ISSUE TITLE
Add captcha on registration page to ensure security from bots

### ISSUE THREAD

**Issue by kamsuri** [systers/vms#484]
Adding captcha will help to achieve following:-
1) Prevent spambots/adbots from signing up
2) Protecting downloads from automated access by bots (which is not a security risk in itself, but a bandwidth drain)
3) Secure information of volunteers
We can use Google's invisible captcha to give users a hassle free experience and simultaneously ensure security from bots. 
Suggestions are welcomed.

**Comment by swekshajha12** [comment]
https://developers.google.com/recaptcha/docs/invisible
Are you talking about this? This will need an https connection . Correct me if I am wrong .

**Comment by kamsuri** [comment]
@swekshajha12 Yes, i am talking about this only.
As mentioned in the docs(https://developers.google.com/recaptcha/docs/invisible) it needs to be loaded using HTTPS protocol. We can use No Captcha but Invisible one is more secure and uses Artificial Intelligence which is a more advanced technique. Moreover, it provides a hassle free experience to users and a tough time for bots. 
@tapasweni-pathak your views on this?

**Comment by swekshajha12** [comment]
I'll take up this issue ! Shall we use Google's no captcha recaptcha? What do you suggest @tapasweni-pathak :)

**Comment by ikbalsingh** [comment]
Is this still open?
@swekshajha12  are you still working on this?

**Comment by anjali-dhanuka** [comment]
@ikbalsingh Do u want to work on it?  If yes, go ahead.

**Comment by ayushgarg1804** [comment]
@ikbalsingh Yes, please go ahead. Just comment here if you start working on this

**Comment by ikbalsingh** [comment]
@anjali-dhanuka Kind of busy on something else. You can go ahead and assign it to someone else.

**Comment by kamsuri** [comment]
As this issue doesn't follow the standards, i'm closing it as of now. I'll reopen it if someone wishes to work on this or if i'll get time to fix this.
