### ISSUE TITLE
 links mentioned in vms/docs/ProjectSettings.md seems broken.

### ISSUE THREAD

**Issue by swekshajha12** [systers/vms#488]

**Comment by tapasweni-pathak** [comment]
Please mention the links which are broken.

**Comment by swekshajha12** [comment]
The following are the links:
https://docs.djangoproject.com/en/1.6/topics/settings/
https://docs.djangoproject.com/en/1.6/ref/settings/
https://docs.djangoproject.com/en/1.6/ref/settings/#databases
https://docs.djangoproject.com/en/1.6/topics/i18n/
 https://docs.djangoproject.com/en/1.6/howto/static-files/

I'm getting the following error
![link](https://user-images.githubusercontent.com/22135941/31824474-c771994e-b5cc-11e7-923b-b3c8c3de2406.png)

System details: Ubuntu 16.04 browser: Mozilla Firefox

**Comment by tapasweni-pathak** [comment]
Thanks! The task to fix this issue is to [remove the settings.py code](https://github.com/systers/vms/blob/develop/docs/Project%20Settings.md#source-code-for-settingspy) completely from this file.

**Comment by swekshajha12** [comment]
The name of the file has space in it and generates problem when trying to use in command line. Can I change the names with space replaced by underlines?

**Comment by tapasweni-pathak** [comment]
Can you please share few examples?

**Comment by swekshajha12** [comment]
For e.g while trying to git add you need to use backslash like Project\ Settings.md , this can be bad for someone who is completely new to command line in ubuntu etc. We can use underscores instead of space.And there are many files with space in their names. What do you suggest?

**Comment by tapasweni-pathak** [comment]
Please go ahead.
