### ISSUE TITLE
Anyone can signup as an admin

### ISSUE THREAD

**Issue by swekshajha12** [systers/vms#494]
Anyone can signup as an admin in the current scenario , we can add a validation system where when a person tries to sign up as an admin , an email is sent to an already admin to confirm that person's signup. Is my understanding correct?

**Comment by tapasweni-pathak** [comment]
Can you please detail this a bit more?

**Comment by swekshajha12** [comment]
Currently anyone who wishes to use vms is free to signup as an admin or a volunteer regardless of the fact that he/she is  a volunteer or admin actually. This can become baffling on later stages . What we can do is create an authentication system where only an actual admin of an organization can signup as an admin . What do you suggest?

**Comment by tapasweni-pathak** [comment]
Currently how it works is anyone would be able signup as admin, so ideally who wish to use VMS and have a person authorized to be a admin will signup as admin. Then they can use the features provided only for admin. How do you plan to change this and verify, can you please write it in steps?

**Comment by swekshajha12** [comment]
Can two person of the same org , sign up as an admin?

**Comment by kamsuri** [comment]
Yes @swekshajha12, an organization can have multiple admin as organization to administrator is a one to many relation.

**Comment by swekshajha12** [comment]
So , what we can do is add a validation system where when someone else of the same organization sign's up as an admin , we can notify the previous admin via email and if required can ask for his confirmation of that person being authorized to be an admin. What do you suggest?

**Comment by tapasweni-pathak** [comment]
Thanks for thinking about this, but it works with the correct approach correctly, so closing this one. We take all the information for volunteer and admin to let them signup.
