### ISSUE TITLE
Create better looking buttons for Login , signup on home page.

### ISSUE THREAD

**Issue by swekshajha12** [systers/vms#496]
Current scenario: There is a lot of space on the home page and the buttons are aligned horizontally.
Suggested : We can instead create longer buttons and align them vertically , this way even the space can be used effectively. Something like these with a non white background?
![buttons](https://user-images.githubusercontent.com/22135941/31858027-1d64fc1c-b70b-11e7-86c5-c87ad71fb922.png)

**Comment by tapasweni-pathak** [comment]
Are you referring to the buttons on this page? [![Screenshot from Gyazo](https://gyazo.com/b6bb33c71b7ee4b350494420edcd6d6f/raw)](https://gyazo.com/b6bb33c71b7ee4b350494420edcd6d6f) The newer design on how Portal has it?

**Comment by swekshajha12** [comment]
Yes , and aligned one below the other. What do you suggest?

**Comment by tapasweni-pathak** [comment]
This should remain as is. Also we won't enable login with social accounts for admins or volunteers as we need a lot of information other than there email id, first name, last name, you can see that in signup form for VMS. For portal we don't need all such information.

Thanks for the suggestion, at least we thought about why we can't change it. Let me know if you have any questions. Closing this one.
