### ISSUE TITLE
Job corresponding to Event

### ISSUE THREAD

**Issue by jayesh92** [systers/vms#5]
In creation of shift, currently we provide to add Event & Job through forms, and if the corresponding event of job selected is not equal to event selected, an error is raised. However, it should be like the user should be given to select event and then on the basis of event selected job fields should be displayed using AJAX

**Comment by GeetikaBatra** [comment]
Greetings!
I am willing to contribute to this issue.Could you please make me aware how can I help.
Regards
Geetika Batra

**Comment by jayesh92** [comment]
Hi,
 You can probably have a look at Coding Task, Point 2 at https://docs.google.com/document/d/11HCkajUrd3hHgZmWJ9ehNeca7pR8njSNuocOks097l8/edit to get more idea on this issue.
