### ISSUE TITLE
Error in running event, shift tests in VMS

### ISSUE THREAD

**Issue by vemurisowjanya** [systers/vms#501]
$`python manage.py test event.tests`
![event_error](https://user-images.githubusercontent.com/16240863/31861986-16b74732-b754-11e7-9d03-f022799aa806.png)

$`python manage.py test shift.tests`
![shift_error](https://user-images.githubusercontent.com/16240863/31861992-1d778b54-b754-11e7-9b95-0c38067403fe.png)

Encountered NoSuchElementException for firefox driver in shift, event tests in VMS

**Comment by MeepyMay** [comment]
Please use the issue template.
