### ISSUE TITLE
Shift hours can be logged before shift

### ISSUE THREAD

**Issue by kamsuri** [systers/vms#502]
Volunteer can log shift hours before the date and time of shift. Once shift hours are logged that shift is marked as completed shift. There should be a check whether the shift date and shift hours have been passed or not before hour logging is permitted.
![screenshot from 2017-10-23 00-20-36](https://user-images.githubusercontent.com/14004808/31865197-51c9dd2e-b788-11e7-8879-7902b2d63d98.png)

**Comment by kriti21** [comment]
@tapasweni-pathak @kamsuri Please review my PR above. Thanks :)

**Comment by MeepyMay** [comment]
Please use the issue template.
