### ISSUE TITLE
Multiple jobs with same name for one event shouldn't be permitted

### ISSUE THREAD

**Issue by kamsuri** [systers/vms#503]
Current sytstem permits same job names for a particular event, but it shouldn't be allowed because there can be multiple shifts for one job rather than multiple jobs.
![screenshot from 2017-10-23 00-25-33](https://user-images.githubusercontent.com/14004808/31865228-f798ffc8-b788-11e7-9419-9a433156c80d.png)

**Comment by tapasweni-pathak** [comment]
Can you please check there is already an issue raised for this?

**Comment by kamsuri** [comment]
Yes @tapasweni-pathak, It is duplicate of #330. Sorry for opening this.
Closing this one.
