### ISSUE TITLE
Search jobs based on region/city/country

### ISSUE THREAD

**Issue by swekshajha12** [systers/vms#504]
This would make it very feasible for users to search for jobs since many a times , people want it to be nearer.
Approach 
1)Current scenario : Users can search jobs/events on the basis of dates only
2)We can add a location field , where the user can select the location and the result thus would be the list of events in that location on the selected dates.

**Comment by kriti21** [comment]
I have made changes that add these features. Please consider my PR https://github.com/systers/vms/pull/546

**Comment by MeepyMay** [comment]
Please use the issue template.
