### ISSUE TITLE
Add validation to resume field (below the upload resume field).

### ISSUE THREAD

**Issue by swekshajha12** [systers/vms#505]
![resume](https://user-images.githubusercontent.com/22135941/31897731-e1edda34-b834-11e7-9903-b5824fd449f8.png)

We can either add a proper regex here or use link validators like URLValidatior provided by Django.
What do you suggest?

**Comment by kriti21** [comment]
Resume is uploaded in file format which can be doc. or pdf or anything else. What kind of verification can be done to such file uploads?
Another option is to use URL to link to resume uploaded on the internet like google drive link or something. That way user does not even need to upload a new resume every time a change is made. What are your thoughts about this @swekshajha12

**Comment by MeepyMay** [comment]
Please use the issue template.
