### ISSUE TITLE
Job should be defined with unique id 

### ISSUE THREAD

**Issue by kamsuri** [systers/vms#507]
Referencing #383 
Each job should be defined by using a unique id or using combination of event and job name because different events can have a job of same name, which leads to problem. As below function will not display those jobs as different jobs, it will consider them as same.
`def get_signed_up_jobs_for_volunteer(volunteer_id):
    """ Gets sorted list of signed up jobs for a volunteer """

    unsorted_jobs = []
    job_list = []
    shift_list_without_hours = get_unlogged_shifts_by_volunteer_id(volunteer_id)
    shift_list_with_hours = get_volunteer_shifts_with_hours(volunteer_id)

    for shift_with_hours in shift_list_with_hours:
        job_name = str(shift_with_hours.shift.job.name)
        if job_name not in unsorted_jobs:
            unsorted_jobs.append(job_name)
    for shift in shift_list_without_hours:
        job_name = str(shift.job.name)
        if job_name not in unsorted_jobs:
            unsorted_jobs.append(job_name)

    #to sort jobs as per name
    for job in sorted(unsorted_jobs, key=str.lower):
        job_list.append(job)
    return job_list`
![screenshot from 2017-10-24 16-47-26](https://user-images.githubusercontent.com/14004808/31940287-2ff3ad16-b8db-11e7-81e1-25ccf7c1f579.png)
![screenshot from 2017-10-24 16-50-52](https://user-images.githubusercontent.com/14004808/31940372-85cc8ce4-b8db-11e7-8dff-2dc5f6a2268b.png)

**Comment by tonythomas01** [comment]
The basic problem here is that we are listing all events on first, and all jobs for all events on the second dropdown. Essentially - there is no filtering happening :/ Someone should introduce some filtering at the frontend, and this should be okey.

**Comment by tonythomas01** [comment]
Well, I found a cleaner solution in https://github.com/systers/vms/pull/506. Just use the id for option on the HTML - and show the dropdown like it was before (and we have all the repeated jobs in the list).

**Comment by kamsuri** [comment]
#511  This seems good but we need to do real time filtering when adding a dropdown for jobs.

**Comment by tonythomas01** [comment]
Well - to do - that I will have to fix the context passing to the templates first. This is fully messed up currently (like the context gets passed only after an initial click on generate_report - a POST). I can give it a try though.

**Comment by tonythomas01** [comment]
Check https://github.com/systers/vms/pull/511#issuecomment-340272936 -- implemented actually.

**Comment by anjali-dhanuka** [comment]
@tapasweni-pathak @tonythomas01 job id has been added in models. can we close this issue or is there anything more to work upon?
