### ISSUE TITLE
Fix relative imports on files

### ISSUE THREAD

**Issue by tonythomas01** [systers/vms#509]
Ugly imports are not allowed in Python 3.x. Like 

```
from shift.services import *
``` 
should become 
```
from vms.shift.services import <whatever>
``` 

We need a `__init__.py` in vms/ to start with. Also, unimported service functions like `calculate_total_report_hours()` are not allowed. These things should be properly imported like: 

```
from vms.shift.services import calculate_total_report_hours

```

**Comment by tonythomas01** [comment]
I can fix the imports for `administrators/` and someone else can complete the same.

**Comment by tonythomas01** [comment]
#510 fixes this partially. Well - to get it merged, we have to change it for every module inside.

**Comment by tapasweni-pathak** [comment]
Thanks for the issue! 

Sure! please go ahead. :star: 

 #379 talks about it, so closing this one.
