### ISSUE TITLE
Upgrade Psycopg2 to version 2.7

### ISSUE THREAD

**Issue by pradeepgangwar** [systers/vms#516]
During installation i faced a error as `Error: could not determine PostgreSQL version from 10.0`. On searching over the internet i found that it is a known issue and has been resolved in version 2.7 of Psycopg2. Upon changing psycopg2 to version 2.7. Installation completed successfully. 

See this - https://github.com/psycopg/psycopg2/issues/594

Since we need **version >= 9.3.4** for **postgres**. Why not upgrade pycopg2 version to 2.7 to enable support for postgres version > 10.

- I am not sure if this will affect any part of website. Please help if upgrading is not feasible here.

**Comment by tapasweni-pathak** [comment]
covering this in #457, so closing this one.
