### ISSUE TITLE
Allow admin to select from dropdown for volunteer search and reports

### ISSUE THREAD

**Issue by pradeepgangwar** [systers/vms#520]
## Description
- For now in admin account if you go for volunteer/search we see that we need to manually enter organization name which are limited and entering manually increases chances of mistake. 
- In administrator/report dropdown for job name and organization name is not displaying available job names and organization names.

**Comment by pradeepgangwar** [comment]
I am working on this

**Comment by tapasweni-pathak** [comment]
> In administrator/report listing job name and organization name was not working properly. Now it is fixed.

👋 thanks for the issue, please update the description of this issue w/ what was not working properly before?
