### ISSUE TITLE
Installation of environment issue. 

### ISSUE THREAD

**Issue by manmeet0307** [systers/vms#536]
I want to contribute to vms but facing problem in setting up environment. Please guide me which package of python I should install?
I am working on windows 10 
Done with installation of virtualbox and vagrant. 
[
![img_20171225_132634](https://user-images.githubusercontent.com/32425680/34346365-dc6ea6d2-ea1c-11e7-875c-8b149d224b99.jpg)
](url)

**Comment by anjali-dhanuka** [comment]
@manmeet0307 I think that you have not followed the installation guidelines correctly. I would suggest you that rather than opening an issue you should ask your doubts on slack #vms channel.

**Comment by tapasweni-pathak** [comment]
👋 @manmeet0307 this may be because of some `PATH` issues in your setup, did you find something useful when you searched it on web?

**Comment by kriti21** [comment]
@manmeet0307 you can also try to not use vagrant and instead setup the development environment locally. That might provide ease to installing dependencies individually and according to your system requirements. Instructions for doing so are also given in the installation guidelines.

**Comment by MeepyMay** [comment]
Please use the issue template.
