### ISSUE TITLE
Setup, run and execute automatic python code formatting on the codebase

### ISSUE THREAD

**Issue by tonythomas01** [systers/vms#537]
## Description
Look at the output of https://dpaste.de/KP3L/raw  - the entire thing is not following PEP8 or any codestyle failing the pipelines on each run. 

## How to fix this 
https://github.com/google/yapf tool by Google can autoformat the entire codebase 

### Update [Required]
- [ ] Install pep8 to requirements.txt 
- [ ] Commit changes on running `yapf` on codebase 
- [ ] Make sure `flake8` gives better result. 

## Definition of Done
same as above. 

## Estimation
5 hours

**Comment by krysopath** [comment]
If that code would be more clean, one might even think about contributing.

**Comment by tonythomas01** [comment]
this would be pretty trivial actually - feel free to create a PR - or I can do that later.

**Comment by Monal5031** [comment]
@naman1901 @pavankm @ayushgarg1804 Issue is related to pep8 standardization.

**Comment by Monal5031** [comment]
@anjali-dhanuka this will be in discussion in the next combined meeting of infra, vms and portal. So maybe add a label `status: blocked` or `needs discussion`for now?

**Comment by naman1901** [comment]
Are we doing flake8 or coala for this? The requirements mention flake8.

**Comment by m-murad** [comment]
@Monal5031 @naman1901 
this will create extra commits in the repo. I don't think this is a good idea. Codacy is already telling us what issues are there in a PR, the user can always improve the PR.
Adding a commit every time there is a formatting issue in the PR doesn't make sense. Instead, before merging a PR the mentors/maintainers should make sure that the PR is following the community code style guidelines.

**Comment by Monal5031** [comment]
@m-murad codacy can get messy sometimes and make the PR look too much messy too with its messages,
this new enhancement issue aims to integrate flake8 or coala on travis itself. So if there were any syntactic issues the travis will fail.
Though I'm confused over what you are trying to say by `Adding a commit every time there is a formatting issue`.

**Comment by m-murad** [comment]
Failing Travis if the PR has style issues is fine.

According to the PR title "run and execute automatic python code formatting on the codebase"
it looks like the author was suggesting automatically formatting the code every time there is a faulty PR. This would create a commit. My concern was regarding that.

**Comment by Monal5031** [comment]
Oh I get it. Yes that is not feasible and neither good.
But I'd have to create a commit to fix existing issues that might get raised by coala or pep8 if i integrate them.

**Comment by m-murad** [comment]
One time commit is fine.

**Comment by Monal5031** [comment]
#478 will do this.
