### ISSUE TITLE
The login system has no forgot password/forgot username feature

### ISSUE THREAD

**Issue by arunikayadav42** [systers/vms#539]
## Description
As a [USER],
I need [TO DO THIS],
so that I can [ACCOMPLISH THAT].

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 week
![screenshot from 2017-12-31 13-02-25](https://user-images.githubusercontent.com/28708494/34462372-80ff7ace-ee68-11e7-99e6-c15b9999a561.png)

**Comment by arunikayadav42** [comment]
Can I start working on this issue?

**Comment by tapasweni-pathak** [comment]
Yes, this sounds good. 👍 I would suggest completing the open pull request first than moving ahead w/ new ones.

**Comment by arunikayadav42** [comment]
I am sorry but can you please tell me what did you mean by saying " I would suggest completing the open pull request first than moving ahead w/ new ones."--like should I work on this issue or not?Please be more precise.

**Comment by tapasweni-pathak** [comment]
> I am sorry but can you please tell me what did you mean by saying " I would suggest completing the open pull request first than moving ahead w/ new ones."--like should I work on this issue or not?Please be more precise.

You have open pull request where few corrections are needed. Completing them and than moving ahead on new issues is what I suggest. Hope this clarifies, let me know if it doesn't.

**Comment by arunikayadav42** [comment]
Alright so you mean is to first complete the details of the issue prior to start working on the same,right?

**Comment by arunikayadav42** [comment]
Actually I know the issue to work on but have no idea how to get started on the issue.

**Comment by anjali-dhanuka** [comment]
@tapasweni-pathak I have already opened a pull request for forgot password 
 https://github.com/systers/vms/pull/528. We were discussing on it too. I wanted to know if there are any other changes you wanted me to make.

**Comment by arunikayadav42** [comment]
@anjali-dhanuka your pull request only covers the forgotten password feature while mine covers the forgotten username too ,so do i reframe my issue statement?

**Comment by MeepyMay** [comment]
Please fill out the information in the template. Thanks!
