### ISSUE TITLE
Adding the "ABOUT" page to the VMS Site

### ISSUE THREAD

**Issue by arunikayadav42** [systers/vms#542]
## Description
I need add the about page as of now the home page and the about page are both same,I wish to make them separate identities.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 week
![screenshot from 2018-01-01 09-10-57](https://user-images.githubusercontent.com/28708494/34467233-51db316c-ef11-11e7-976e-b27d4deb7a89.png)

**Comment by arunikayadav42** [comment]
@tapasweni-pathak  can I start working on this issue?

**Comment by tapasweni-pathak** [comment]
closed with 305af22622ad3b07e92ed3cebd30e18e67fa06b0, ideally you should not see the about page, can you see it with fresh fetch of develop?

**Comment by kriti21** [comment]
@tapasweni-pathak @arunikayadav42 the development version of vms does not have the ABOUT page. This issue can be closed in that case.

**Comment by anjali-dhanuka** [comment]
Yes @arunikayadav42 tepasweni pathak mentioned that integration of vms will be done with portal so there is no need of about page. I would also suggest closing the issue.
