### ISSUE TITLE
Highlighting the active page of the site in the breadcrumb

### ISSUE THREAD

**Issue by arunikayadav42** [systers/vms#543]
## Description
I want to work on highlighting the name of the active page in the navigation bar which does not exist as of now.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 week
![screenshot from 2018-01-01 09-14-48](https://user-images.githubusercontent.com/28708494/34467262-f90c8f6c-ef11-11e7-883b-d38d879092b0.png)

**Comment by arunikayadav42** [comment]
@tapasweni-pathak can I start working on this project please?

**Comment by MeepyMay** [comment]
Please fill out the information in the template. Thanks!
