### ISSUE TITLE
Error in running django admin panel

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#544]
## Description
Programming Error in running django admin panel

## Mocks
![screenshot from 2018-01-03 06-08-41](https://user-images.githubusercontent.com/22369767/34653871-f6a967b6-f418-11e7-82ad-fd271223dadb.png)

### To be done:
- [x] manually add a field `name` to `django_content_type`

Steps to resolve:
->\c database
->ALTER TABLE django_content_type ADD COLUMN name VARCHAR DEFAULT 0; 

Estimation
5 minutes

**Comment by MeepyMay** [comment]
Missing time estimation. Please update this @anjali-dhanuka

**Comment by anjali-dhanuka** [comment]
Done @MeepyMay
