### ISSUE TITLE
Error in sign up form and accessing volunteer field of admin view

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#550]
## Description
Programming Error at sign up view

## Mocks
![screenshot from 2018-01-16 22-50-43](https://user-images.githubusercontent.com/22369767/35008991-55b143de-fb24-11e7-837f-cfe953b3ec8a.png)

## Acceptance Criteria
To be done
- [x] Manually add city, state and country fields to volunteer_volunteer table

Steps:
Steps to resolve:
->\c database
->ALTER TABLE volunteer_volunteer ADD COLUMN city VARCHAR DEFAULT 0;
->ALTER TABLE volunteer_volunteer ADD COLUMN state VARCHAR DEFAULT 0;
-> ALTER TABLE volunteer_volunteer ADD COLUMN country VARCHAR DEFAULT 0;
->ALTER TABLE administrator_administrator ADD COLUMN country VARCHAR DEFAULT 0;

## Estimation
5 minutes

**Comment by MeepyMay** [comment]
Missing time estimation. Please update this @anjali-dhanuka

**Comment by anjali-dhanuka** [comment]
Done @MeepyMay

**Comment by tapasweni-pathak** [comment]
If you port cities_light this would work. Let us know if it doesn't work.
