### ISSUE TITLE
List Sign Up view does not display all the events created by the admin

### ISSUE THREAD

**Issue by kriti21** [systers/vms#552]
## Description
I have created an admin account in the develop version of vms and some new events. When I sign in with user account, the list sign up view shows only some of the events created. It should display all the events created by any admin.

## Mocks
![vms_issue11](https://user-images.githubusercontent.com/19872082/35048053-ec7fc0ae-fbc1-11e7-85f9-2da97f2010f4.png)
![vms_issue12](https://user-images.githubusercontent.com/19872082/35048067-fbc7b6c0-fbc1-11e7-8f19-0999d49536ee.png)

**Comment by rohan033** [comment]
@kriti21 The events which have no jobs/shifts are not shown to the volunteers by default. @tapasweni-pathak @tonythomas01 Please review this , if there is a need to show other events too.

**Comment by kriti21** [comment]
IMO all **upcoming** events should be displayed on the main page. This would help the volunteers to keep regular checks on the shifts/jobs for the events in which they might be interested. The system could display a proper message like - "Shifts/jobs for this event will soon be available" in the meantime. What do you suggest @tonythomas01 @tapasweni-pathak

**Comment by MeepyMay** [comment]
Please use the issue template. We're missing Acceptance Criteria and Time Estimation.
