### ISSUE TITLE
Add edit/view profile option for the admin

### ISSUE THREAD

**Issue by kriti21** [systers/vms#554]
There is option for the volunteer to view its profile as well as edit it. For the admin, no such option is available.

## Mocks
![vms_issue4](https://user-images.githubusercontent.com/19872082/35102517-2916fb82-fc89-11e7-997c-ac75c7cebdb5.png)
![vms_issue42](https://user-images.githubusercontent.com/19872082/35102541-36ffbc48-fc89-11e7-8341-08bf85bf9717.png)

## Acceptance Criteria
Admin user should be able to view profile as well as edit is just like the volunteers.

**Comment by sammy1997** [comment]
@kriti21 @tapasweni-pathak I am on this

**Comment by kriti21** [comment]
Sure. Go ahead @sammy1997  :+1:

**Comment by sammy1997** [comment]
![admin_profile_edit](https://user-images.githubusercontent.com/24635701/35458961-6703304c-0304-11e8-9406-15411212df34.png)

**Comment by kriti21** [comment]
Yes for now just the options filled by admin while signing in are sufficient for its profile. Any suggestions @tapasweni-pathak

**Comment by sammy1997** [comment]
![screenshot from 2018-02-01 16-04-45](https://user-images.githubusercontent.com/24635701/35674194-d973819a-0769-11e8-91ed-e07ba598bbc1.png)
![screenshot from 2018-02-01 16-04-59](https://user-images.githubusercontent.com/24635701/35674195-d9c765f8-0769-11e8-881e-9dfa33650b5e.png)
![screenshot from 2018-02-01 16-05-05](https://user-images.githubusercontent.com/24635701/35674196-da797586-0769-11e8-8609-e1487d4e0d1b.png)

Here are the final edit and view Profile screens. @kriti21 @tonythomas01 @tapasweni-pathak please review this
