### ISSUE TITLE
Upload updated resume field in edit profile form returns error.

### ISSUE THREAD

**Issue by kriti21** [systers/vms#555]
## Mocks
![vms_issue3](https://user-images.githubusercontent.com/19872082/35102902-4afa55fe-fc8a-11e7-98ee-df7038760f81.png)

**Comment by Astrophilic** [comment]
Hello @kriti21  !!! I would like to work on this issue ! if you could please assign me!!!
I have built the project on my local machine !!! and i tried generating the same output as above!!
but it appears different!!!
![chk](https://user-images.githubusercontent.com/25284819/35199103-0bc8a222-ff1f-11e7-854f-9ef743eb224a.png)

Please help me generate the real error so that i could work it out!!
Regards!!!

**Comment by anjali-dhanuka** [comment]
@Astrophilic  Login as an administrator
![screenshot from 2018-01-22 09-30-03](https://user-images.githubusercontent.com/22369767/35204842-d6a464ae-ff56-11e7-96f6-3093ef11ecdd.png)
Select any volunteer's profile
![screenshot from 2018-01-22 09-30-49](https://user-images.githubusercontent.com/22369767/35204856-035e6e4a-ff57-11e7-8331-7e3176bf484a.png)
Click on Edit profile option
![screenshot from 2018-01-22 09-31-47](https://user-images.githubusercontent.com/22369767/35204874-1bb7f6d2-ff57-11e7-8718-3ad8df6d16fd.png)
Upload a resume
![screenshot from 2018-01-22 09-32-38](https://user-images.githubusercontent.com/22369767/35204893-398b5122-ff57-11e7-85d8-fa6b13229abc.png)
When u save u get the error
![screenshot from 2018-01-22 09-33-49](https://user-images.githubusercontent.com/22369767/35204914-5ddf2d5a-ff57-11e7-9bd1-306d398d72d9.png)

**Comment by kriti21** [comment]
@Astrophilic I hope you have generated the error using above process. There is no need for you to get assigned. Just go ahead with the work and submit pull request. :)

**Comment by Astrophilic** [comment]
@anjali-dhanuka  my admin page doesn't show the option to edit volunteers' profile!
![edit](https://user-images.githubusercontent.com/25284819/35207385-ab5ad2b2-ff68-11e7-84a8-f5a07496fcfc.png)
I also verified that i had clonned the 'develop' branch.
![ed](https://user-images.githubusercontent.com/25284819/35207431-ffe00668-ff68-11e7-8c7a-705f10d97962.png)

**Comment by anjali-dhanuka** [comment]
@astrophilic you need to create a volunteer account first then it will show u the volunteer in ur nav bar.

**Comment by anjali-dhanuka** [comment]
https://user-images.githubusercontent.com/22369767/35204856-035e6e4a-ff57-11e7-8331-7e3176bf484a.png
You can then edit his profile

**Comment by Astrophilic** [comment]
@anjali-dhanuka  I have created 2 volunteers and 1 admin , and when i search them using "volunteer search",
They appear!!!
here is the the snap
![anjj](https://user-images.githubusercontent.com/25284819/35207773-e11a9066-ff6a-11e7-8c23-c3b304a44b57.png)

**Comment by Astrophilic** [comment]
@anjali-dhanuka  And when i switch to **Manage Volunteer Shifts** tab.
This list appears!
![f1](https://user-images.githubusercontent.com/25284819/35207956-b1c77558-ff6b-11e7-8aa7-46dcc85e7fd1.png)

**Comment by Astrophilic** [comment]
@anjali-dhanuka  , it doesn't show !! i tiried syncing db! but it says there are no migrations to apply!!
What could possibly be the reason for this to happen??
Why is the tab not visible in my case!
I tried running this command 
_python manage.py sqlall app_name_here_
with vms etc, is the usage of **sqlall app specific**?? Please do clarify!
and then syncing the db 
Incongnito as well!
But the tab doesn't appear!
What could possibly be the reason for this to happen??

**Comment by anjali-dhanuka** [comment]
@astrophilic you can check in the admin panel if the objects are really created or not.

**Comment by kriti21** [comment]
@Astrophilic Please show the screenshot of window which appears when you are signed in as a volunteer along with the options that appear when you click on your name in the top right corner. All you need to do is create a volunteer account and try editing your profile. When you upload a file in the resume field, it shows this error.

**Comment by anjali-dhanuka** [comment]
@Astrophilic may be your administrator does not have permissions to access the volunteers profile. You should check the permissions in your django admin panel.

**Comment by kriti21** [comment]
@Astrophilic @anjali-dhanuka I think you have misunderstood this a little. This thing does not require admin at all.

**Comment by Astrophilic** [comment]
@kriti21  I did the steps you mentioned at the very beginning and it was a different error which was encountered ***"NameError "***
Here are the snaps!
snap 1 : here i edit after logging in as a volunteer.
![c1](https://user-images.githubusercontent.com/25284819/35222006-59a488d4-ffa2-11e7-8601-84c22a9dc2cf.png)
snap 2 : Here i upload a resume with extension .od
![c2](https://user-images.githubusercontent.com/25284819/35222029-745328d4-ffa2-11e7-8168-a5d4c503d586.png)
snap 3: I click on save button and this appears!
![c3](https://user-images.githubusercontent.com/25284819/35222085-a5a8b232-ffa2-11e7-8784-a67a01181d88.png)

**Comment by kriti21** [comment]
@Astrophilic I would suggest you to do some Google search for this error. Please try some solutions available on stackoverflow.com regarding this error. If nothing helps, you can always get back to us. ;)

**Comment by anjali-dhanuka** [comment]
@Astrophilic u didn't get what I told you. I asked you to check in django admin panel
![screenshot from 2018-01-22 19-03-30](https://user-images.githubusercontent.com/22369767/35223356-15d1dcd8-ffa7-11e7-873b-c725ad5b6e49.png)
Then check if volunteers are shown here
![screenshot from 2018-01-22 19-04-17](https://user-images.githubusercontent.com/22369767/35223364-22b5db0c-ffa7-11e7-9c96-46d469635c43.png)
If yes, Check if the administrator has permissions or administrator is created


.

**Comment by Astrophilic** [comment]
@anjali-dhanuka  Here is what i see !
![hre](https://user-images.githubusercontent.com/25284819/35224961-ef733ab8-ffac-11e7-87d6-1671d83fc284.png)
How can use create an admin??
first way : using the signup page
second way : using python manage.py createsuperuser
Do correct me wherever i go wrong because I 'm learning as i am doing!!
that's an obvious reason why i'm having so many issues :sweat_smile:
Please do recommend sources to study!! wheresoever required, i am always willing to learn and apply! :blush:

I encounter two different behaviours with these two types of admin.

**admin created through signup interface** when logged in shows a interface like this
![ad1](https://user-images.githubusercontent.com/25284819/35225390-33ffd906-ffae-11e7-996d-0e480a5e8823.png)

and admin created through  python manage.py **createsuperuser**
shows like this
![ad2](https://user-images.githubusercontent.com/25284819/35225416-4c71a726-ffae-11e7-86f0-1076104113c2.png)

This doesn't show any tabs to select!!

**Comment by anjali-dhanuka** [comment]
@Astrophilic to learn you can refer https://docs.djangoproject.com/en/2.0/intro/tutorial01/  or
https://tutorial.djangogirls.org/en/  These will help you to get an idea of django.

**Comment by Astrophilic** [comment]
@anjali-dhanuka what about the issue i mentioned above , regarding the weird behaviour of the admins.
and thanks for mentioning the links!

**Comment by anjali-dhanuka** [comment]
@Astrophilic I also get the same error sometimes. I too don't know the reason. You can refer the mentor @tapasweni-pathak for this.

**Comment by tapasweni-pathak** [comment]
Thanks for discussing the issue you'all! @Astrophilic please feel free to create a new issue for your finding.

@kriti21 do you still see this?

**Comment by kriti21** [comment]
@tapasweni-pathak Yes I do see the OS error still. This error is related to permission/access. If I start my development server by `python manage.py runserver` this error occurs on uploading new resume but if do `sudo python manage.py runserver` then it does not show this error. This needs to corrected  
And a separate issue for Name error has been already been opened.

**Comment by anjali-dhanuka** [comment]
@kriti21 no, it has been resolved. You need to create a folder named srv and change its permissions. This is not an error. Resume files are kept in a folder and only sudo has access to it that you need to provide manually in your pc. Hope this helps.

**Comment by kriti21** [comment]
@anjali-dhanuka that is fine at developer's end but not very ideal for any user of the website IMO. The process should be more automated and easier. What do you think ? This occurs even in the currently live version of vms.

**Comment by MeepyMay** [comment]
Please use the issue template.
