### ISSUE TITLE
Migrate to python 3.6 and django 1.11

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#557]
## Description
As a user, I need to migrate the project to python 3.6 and django 1.11 from django 1.7.4 and python 2.7.12 so that I can make the code future proof.

### Update [Required]
- [ ] Updation of code

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by kriti21** [comment]
This issue is already opened https://github.com/systers/vms/issues/457 @anjali-dhanuka and in fact you have made a PR too ;)

**Comment by anjali-dhanuka** [comment]
@kriti21 that's django 2.0 this one is django 1.11

**Comment by kriti21** [comment]
Why django 1.11 ? Why not to django 2.0 directly? @anjali-dhanuka

**Comment by anjali-dhanuka** [comment]
Django 2.0 compatible versions of python packages have not been relaxing
yet.

**Comment by sammy1997** [comment]
@anjali-dhanuka @tapasweni-pathak @tonythomas01 I think the previous PR to this issue failed CI and Codacy checks. I would like to work on this and send a new PR.

**Comment by MeepyMay** [comment]
Please use the issue template.

**Comment by anjali-dhanuka** [comment]
@MeepyMay Done.

**Comment by anjali-dhanuka** [comment]
Closing https://github.com/systers/vms/pull/694
