### ISSUE TITLE
Error in editing profile of a volunteer

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#561]
## Description
get_volunteer_by_id needs to be imported from services file. 

## Mocks
![screenshot from 2018-01-26 13-52-03](https://user-images.githubusercontent.com/22369767/35430935-7b2218a4-02a0-11e8-8e38-366d1fae4a7c.png)
![image](https://user-images.githubusercontent.com/22369767/35431457-91a8d958-02a2-11e8-99a6-c91d663ccf87.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by sammy1997** [comment]
@anjali-dhanuka I am not able to reproduce this error. Can you tell me how you got this error?

**Comment by anjali-dhanuka** [comment]
@sammy just select a volunteer and try editing his profile. You will get the errorm

**Comment by sammy1997** [comment]
@anjali-dhanuka I am not getting any such error. My edit is working fine.

**Comment by anjali-dhanuka** [comment]
@sammy1997 Have u pulled all the stuff? May be this error is arising due to some latest commits in the project.

**Comment by sammy1997** [comment]
@anjali-dhanuka No. I didn't pull the code. I think its due to some recent merge. @tonythomas01 @tapasweni-pathak what should we do? I have completed the issue #554 . Pulling the code will introduce this error.

**Comment by sammy1997** [comment]
I am on this @anjali-dhanuka @tonythomas01 @tapasweni-pathak
