### ISSUE TITLE
Non uniform behaviour after logging in

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#567]
## Description
As a user, I must find nav bar every time after log in so that I can use the app.

## Mocks
![jsxns](https://user-images.githubusercontent.com/22369767/35476798-3c6f52d8-03dc-11e8-88d9-7549eb479250.png)

### Update [Required]
- [ ] Separate view for superuser

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by rohan033** [comment]
This also occured to me. I think this happens when some one logs in as **django-admin** and not as volunteer or the VMS admin.

**Comment by anjali-dhanuka** [comment]
No @rohan this occurs to both

**Comment by rohan033** [comment]
[https://github.com/systers/vms/blob/develop/vms/vms/templates/vms/base.html](url)
User authentication begins.
```
{% if user.is_authenticated %} #can be a django-admin/vms volunteer/vms admin
```
Checking if user is a **VMS admin**
```
  {% if user.administrator %} #if vms admin
    <li><a href="{% url 'volunteer:search' %}">{% trans "Volunteer Search" %}</a></li>
    <li><a href="{% url 'shift:volunteer_search' %}">{% trans "Manage Volunteer Shifts" %}</a></li>
    <li><a href="{% url 'administrator:report' %}">{% trans "Report" %}</a></li>
    <li><a href="{% url 'administrator:settings' %}">{% trans "Events" %}</a></li>
    
    <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
        style="text-transform: capitalize; text-decoration: none;">{% trans user.administrator.first_name %}
          <span class="caret"></span></a>

      <ul class="dropdown-menu">
              <li><a href="{% url 'registration:signup_administrator' %}">{% trans "Create Admin Account" %}</a></li>
              <li><a href="{% url 'authentication:logout_process' %}">{% trans "Log Out" %}</a></li>
      </ul>
    </li>
    </ul>
  {% endif %} #for vms admin
```
Checking if user is a **VMS volunteer**
```
  {% if user.volunteer %} #if vms volunteer
    <li><a href="{% url 'shift:view_volunteer_shifts' user.volunteer.id %}">{% trans "Upcoming Shifts" %}</a></li>
    <li><a href="{% url 'shift:view_hours' user.volunteer.id %}">{% trans "Completed Shifts" %}</a></li>
    <li><a href="{% url 'event:list_sign_up' user.volunteer.id %}">{% trans "Shift Sign Up" %}</a></li>
    <li><a href="{% url 'volunteer:report' user.volunteer.id %}">{% trans "Report" %}</a></li>

    <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
        style="text-transform: capitalize; text-decoration: none;">{% trans user.volunteer.first_name %}
          <span class="caret"></span></a>

      <ul class="dropdown-menu">
              <li><a href="{% url 'volunteer:profile' user.volunteer.id %}">{% trans "Profile" %}</a></li>
              <li><a href="{% url 'authentication:logout_process' %}">{% trans "Log Out" %}</a></li>
      </ul>
    </li>
    </ul>
  {% endif %} #for vms volunteer
  ```
  **Nothing specified for users who are neither vms volunteer nor admin but authenticated.
    For Eg: Django Admin [ controlling the admin panel] created by the createsuperuser command
    and thus not showing the desired nav bar links.**

Code when user hasn't signed up/logged in.
  ```
  {% else %}  #else condition: if user not authenticated
  <li><a href="{% url 'registration:signup_volunteer' %}">{% trans "Sign Up" %}</a></li>
  <li><a href="{% url 'authentication:login_process' %}">{% trans "Log In" %}</a></li>
  
{% endif %} #ends the if else block.
```
I think this might help.Please correct me if I am wrong.

**Comment by anjali-dhanuka** [comment]
@rohan033 The django admin is not allowed to log in the vms. And this non-uniformity appers for both volunters and vms administrators.

**Comment by sammy1997** [comment]
@anjali-dhanuka If we don't allow django-admin as a user for VMS, so to remove this non Uniformity, do you want to show an error page or message saying that you can't use VMS, and keep a logout button?

**Comment by rohan033** [comment]
@sammy1997 I have kept a simple log out button with a proper message for my local development.

**Comment by sammy1997** [comment]
@rohan033 I think we should take advice from the mentors as to what they want first.

**Comment by rohan033** [comment]
@sammy1997 Yes, waiting for the mentors' review on it.

**Comment by anjali-dhanuka** [comment]
@sammy@rohan the Django admin is not allowed to log in neither as a user nor as vms administrator. The Vms user i.e volunteer can't  log in as administrator and the Vms administrator can't log in as vms volunteer.

**Comment by anjali-dhanuka** [comment]
@sammy@rohan the Django admin is not allowed to log in neither as a user nor as vms administrator. The Vms user i.e volunteer can't  log in as administrator and the Vms administrator can't log in as vms volunteer and log out button is already there so u don't need to add it.

**Comment by sammy1997** [comment]
@anjali-dhanuka what we want to say is lets say we login as a django-admin, we have to show something right? So what do we show? An error page? Or just a logout button for django-admin? Currently It shows nothing other than the Systers description. @anjali-dhanuka @tonythomas01 Please comment on what we shoud do?

**Comment by anjali-dhanuka** [comment]
@sammy1997 I guess we should give the permissions of a vms administrator to django admin.

**Comment by sammy1997** [comment]
Ok. I am on this. @anjali-dhanuka @tapasweni-pathak @tonythomas01

**Comment by rohan033** [comment]
@anjali-dhanuka I have given the permissions of a vms admin to the django-admin [let's call it superuser].So should this super user needs to have other attributes of a vms admin like : email,address,country etc. i.e should it behave like an actual vms admin or just has permissions.

**Comment by MeepyMay** [comment]
Please use the issue template. We're missing Acceptance Criteria and Time Estimation.

**Comment by anjali-dhanuka** [comment]
@MeepyMay Done.

**Comment by anjali-dhanuka** [comment]
Same as #579
