### ISSUE TITLE
TypeError in viewing Completed shifts for a new Volunteer

### ISSUE THREAD

**Issue by sammy1997** [systers/vms#568]
Sing Up as a Volunteer
Try to view Completed Shifts.
Produces a TypeError. A NoneType object is being returned, and that exception hasn't been handled.

![shifts_error](https://user-images.githubusercontent.com/24635701/35604363-f55bb164-0667-11e8-9a66-7c4390f020d4.png)

## Acceptance Criteria
It should show a page similar to Upcoming Shifts, showing you 
dont have any completed shift, instead of a Django Error page 
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

@tapasweni-pathak Please Review this issue

**Comment by sammy1997** [comment]
I tried to print the volunteer objects. And it wasn't None. I think the context is is returning null in shift/views.py in line 607. I am not sure though.

**Comment by sammy1997** [comment]
@tonythomas01 Please review this

**Comment by rohan033** [comment]
![image](https://user-images.githubusercontent.com/17281037/35693446-4374c48e-07a4-11e8-8df8-134300fcdf2c.png)
Working fine. Please correct me @sammy1997 if I  am wrong.

**Comment by sammy1997** [comment]
I am still getting the error. Even after pulling. Can you show the code for shift/views and volunteer/utils files. I think there is an error somewhere in these files.

**Comment by rohan033** [comment]
https://github.com/systers/vms/blob/develop/vms/shift/views.py
```
class ViewHoursView(LoginRequiredMixin, FormView, TemplateView):
    template_name = 'shift/hours_list.html'

    @method_decorator(check_correct_volunteer)
    @method_decorator(vol_id_check)
    def dispatch(self, *args, **kwargs):
        return super(ViewHoursView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ViewHoursView, self).get_context_data(**kwargs)
        volunteer_id = self.kwargs['volunteer_id']
        context['volunteer'] = get_volunteer_by_id(volunteer_id)
        context['volunteer_shift_list'] = get_volunteer_shifts_with_hours(
            volunteer_id)
        return context
```

**Comment by MeepyMay** [comment]
This is almost a complete issue. Please add the headers. @sammy1997

**Comment by sammy1997** [comment]
@MeepyMay Can you please explain what headers to add ? Thanks. :)
