### ISSUE TITLE
Remove extra white space from right hand side of the report template

### ISSUE THREAD

**Issue by kriti21** [systers/vms#569]
## Description
The template for creating report has extra white space on the right side due to which, on scrolling the form shifts towards the left and looks odd.

## Mocks
![vmsissue5](https://user-images.githubusercontent.com/19872082/35667232-e0ab8be0-0752-11e8-85a2-2b7edb94968d.png)

![vmsissue55](https://user-images.githubusercontent.com/19872082/35667239-ea591ce8-0752-11e8-8c3e-11931bdb425e.png)

**Comment by sammy1997** [comment]
@kriti21 I think we will just need to add overflow-x: hidden; to the body. @tapasweni-pathak @tonythomas01. Please review this.

**Comment by tonythomas01** [comment]
+1 LGTM
