### ISSUE TITLE
Volunteer Sign up form does not count organisation provided by volunteer(not selected from list)

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#576]
## Description
As a user, I need the system to update its organization list by my unlisted organization so that the organization list can get updated.

## Mocks
![screenshot from 2018-02-02 14-31-42](https://user-images.githubusercontent.com/22369767/35725176-6e895400-0826-11e8-8a85-6047d4f66f48.png)
![screenshot from 2018-02-02 14-31-52](https://user-images.githubusercontent.com/22369767/35725189-75cc50dc-0826-11e8-9522-b07194935cf5.png)

### Update [Required]
- [ ] Store valid organizations in database.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by sbansal3096** [comment]
Also the organizations provided by the volunteers and not in the list, are not added in the organization list that the admin can view and edit. These two issues seem to be related.

**Comment by sbansal3096** [comment]
Is someone on this issue? I wanted to work on it.

**Comment by MeepyMay** [comment]
Please use the issue template. We're missing Acceptance Criteria and Time Estimation.

**Comment by anjali-dhanuka** [comment]
@MeepyMay Done.

**Comment by anjali-dhanuka** [comment]
@sbansal3096 You can work on the issue. Go ahead.

**Comment by anjali-dhanuka** [comment]
@abhishekarya286 @ayushgarg1804 @kamsuri First we need to solve this issue, then only we can add validations on organisation.

**Comment by anjali-dhanuka** [comment]
closes #859
