### ISSUE TITLE
List of Organizations not showing in sign up form

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#577]
## Description
As a user, I need to see the list of organisations while sign up so that I can select one of them.

## Mocks
![screenshot from 2018-02-02 14-41-34](https://user-images.githubusercontent.com/22369767/35725419-5e160f68-0827-11e8-8c02-5a390ac2131a.png)

### Update [Required]
- [ ] Restart the server

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 minute

**Comment by kriti21** [comment]
@anjali-dhanuka  Organizations can be added by admin only and once added they are shown in the list as well. Please sign in with admin account and create some organizations. They will appear when signing up after that.

**Comment by anjali-dhanuka** [comment]
@kriti21 I added the organizations from Django admin but still they didn't appear

**Comment by kriti21** [comment]
Not django admin.I meant the vms administrator @anjali-dhanuka

**Comment by sammy1997** [comment]
@kriti21 I think @anjali-dhanuka means that if the Org model object exists( be it from django admin or from vms admin) it should show the orgs in the list right?

**Comment by sammy1997** [comment]
@anjali-dhanuka I see the org in the list. Here are the ss.
![orgs](https://user-images.githubusercontent.com/24635701/35753931-95603844-0887-11e8-8138-7ce9f1e8123b.png)
![sign_up](https://user-images.githubusercontent.com/24635701/35753933-95f429f0-0887-11e8-814d-a79c7719d827.png)

**Comment by rohan033** [comment]
Is this organization created by the VMS admin or Django admin? Because those created by Django admin are not being shown

**Comment by sammy1997** [comment]
Yes. Its not showing for those added by django admin

**Comment by sammy1997** [comment]
Should we add that feature? In that case I am on it

**Comment by rohan033** [comment]
But these organisations added by the Django admin can be seen in the Organisations  http://127.0.0.1:8000/organization/list/ for the VMS admin.

**Comment by kriti21** [comment]
@anjali-dhanuka @sammy1997 @rohan033 Well in my case organizations do show up in volunteer as well as vms_admin sign up form. I added two organizations as django admin and two as vms admin. All four show up in the sign up form.

**Comment by anjali-dhanuka** [comment]
@kriti21 @tapasweni-pathak @tonythomas01  They are showing up properly now. Don't know what happened. 
See
![screenshot from 2018-02-03 14-41-18](https://user-images.githubusercontent.com/22369767/35765741-4eb18ccc-08f0-11e8-85f8-ca1a1c1b0cbe.png)

**Comment by sammy1997** [comment]
@anjali-dhanuka @kriti21 In my case changing a single line of code did the job. But before that, it wasn't showing.

**Comment by sammy1997** [comment]
Ok...It's showing now. Even after i reverted the previous change. I think I have understood what happened. We are being able to see the list after starting the development server again. This is because we are using self object to reference the organisation objects. The lifetime of a self instance is as long as the server runs . Here is a link https://stackoverflow.com/questions/41234181/lifetime-and-scope-of-class-and-instance-variables-in-django. So basically restarting the server, or doing the sign up in Incog will work.

**Comment by anjali-dhanuka** [comment]
Yes I too think so @sammy1997

**Comment by sammy1997** [comment]
Yes. So we should close this one.

**Comment by kriti21** [comment]
I think this issue can be closed now @anjali-dhanuka

**Comment by anjali-dhanuka** [comment]
I guess this should be kept here. If anyone else faces the same issue, he/she might get help from it.

**Comment by MeepyMay** [comment]
Please use the issue template. We're missing Acceptance Criteria and Time Estimation.

**Comment by anjali-dhanuka** [comment]
Done @MeepyMay
