### ISSUE TITLE
No check on length of password in sign-up form 

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#578]
## Description
As a user I must keep my password in some text limit so that the security can be improved.

## Mocks
![Uploading Screenshot from 2018-02-02 14-48-55.png…]()
![screenshot from 2018-02-02 14-47-55](https://user-images.githubusercontent.com/22369767/35725676-3897b128-0828-11e8-95d0-0e2bc6eb4234.png)

### Update [Required]
- [ ] Implement min_length and max_length check on password

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by sammy1997** [comment]
@anjali-dhanuka are you asking for a minimum length check?

**Comment by anjali-dhanuka** [comment]
Yes @sammy and I am currently working on it too.

**Comment by sammy1997** [comment]
I have already implemented this feature @anjali-dhanuka . I am sending a PR.

**Comment by sammy1997** [comment]
@MeepyMay  @tonythomas01 @tapasweni-pathak Please review the PR for this issue

**Comment by MeepyMay** [comment]
Please use the issue template. We're missing Acceptance Criteria and Time Estimation.

**Comment by anjali-dhanuka** [comment]
Done @MeepyMay

**Comment by kamsuri** [comment]
We can update this issue to validate passwords for a particular format(some regex) instead of just length. What do you think @sammy1997 @anjali-dhanuka ?

**Comment by anjali-dhanuka** [comment]
This issue already exists https://github.com/systers/vms/issues/644

**Comment by sammy1997** [comment]
Please reassign this issue @anjali-dhanuka @ayushgarg1804. I am not getting time for making the changes.

**Comment by kamsuri** [comment]
I'll submit a PR for the same.

**Comment by anjali-dhanuka** [comment]
@kamsuri Are you working on it or shall I label this issue for first-timers?

**Comment by kamsuri** [comment]
Please mark it for first-timers.

**Comment by anjali-dhanuka** [comment]
closes #861
