### ISSUE TITLE
Add log out option for django admin 

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#579]
## Description
Currently there is no way to log out once a django admin has logged in.

## Mocks
![image](https://user-images.githubusercontent.com/22369767/35725839-c6095eda-0828-11e8-93c1-7c574300dbb5.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by rohan033** [comment]
@anjali-dhanuka Just adding a logout button will do the job.No need of giving Django admin the privileges of VMS admin.? Referring issue #567.

**Comment by anjali-dhanuka** [comment]
@rohan033 I guess the permissions need to be decided by the mentors but at least adding a log out option is mandatory.

**Comment by sammy1997** [comment]
@rohan033 Please mention on the issues you are working on, that you are on it. Just drop a comment.

**Comment by rohan033** [comment]
Sure. @sammy1997
