### ISSUE TITLE
List of organizations not displayed in volunteer profile edit form

### ISSUE THREAD

**Issue by kriti21** [systers/vms#580]
## Description
The list of available organizations should be displayed in the profile edit form for volunteers.

## Mocks
![issue8](https://user-images.githubusercontent.com/19872082/35746600-53823428-086d-11e8-8258-cb30ed4fb2e4.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by rohan033** [comment]
@kriti21 I also encountered the same problem.Would like to fix it.

**Comment by rohan033** [comment]
@kriti21 Please review the PR.
