### ISSUE TITLE
Volunteer's organization automatically set to None on editing profile

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#581]
## Description
As the volunteer clicks on edit profile, his organization is changed to None.

## Mocks
![screenshot from 2018-02-03 04-05-07](https://user-images.githubusercontent.com/22369767/35758035-e0e19442-0897-11e8-9aa3-b01ce96d1945.png)

![screenshot from 2018-02-03 04-04-53](https://user-images.githubusercontent.com/22369767/35757978-992f63ae-0897-11e8-8807-4c5e26ab8ff1.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by rohan033** [comment]
@anjali-dhanuka Please review the PR.Correct me if I am wrong.

**Comment by anjali-dhanuka** [comment]
@rohan033 I was just working on the issue #583 and eventually this one also got fixed.

**Comment by rohan033** [comment]
@anjali-dhanuka PR #584 and #582 seem similar.Can there be a problem while merging.?

**Comment by anjali-dhanuka** [comment]
Yes you are right I need to change that. Thanks for notifying me. They are unncessary actually. But I don't think that there will be any issue in merging.

**Comment by MeepyMay** [comment]
Please use the issue template.

**Comment by anjali-dhanuka** [comment]
@MeepyMay Done.
