### ISSUE TITLE
Non-listed Organisation not displayed properly.

### ISSUE THREAD

**Issue by rohan033** [systers/vms#583]
## Description
Add a non-listed organisation in volunteer edit form keeping select organisation: None
After saving view the Organisation.
Type:UI Fix
Difficulty: Easy

## Mocks
Add/Update the organisation name in the non-listed organisation input box.

![image](https://user-images.githubusercontent.com/17281037/35758852-054cb0c4-089c-11e8-84a9-155198323ed4.png)

View **organisation** in profile.

![image](https://user-images.githubusercontent.com/17281037/35758905-53b14d2e-089c-11e8-9e20-6017b9fe24af.png)

View **organisation** when selected from the list.

![image](https://user-images.githubusercontent.com/17281037/35758991-f4520aac-089c-11e8-8914-0c4cf1013065.png)

## Acceptance Criteria
Fix the UI.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by sbansal3096** [comment]
I would like to work on this issue.

**Comment by anjali-dhanuka** [comment]
As you can see @sbansal3096 I have already submitted pull request for the issue.

**Comment by sbansal3096** [comment]
@anjali-dhanuka okay, thank you.
