### ISSUE TITLE
Add a datepicker to the templates where they are missing

### ISSUE THREAD

**Issue by vubo** [systers/vms#59]
Issue 11 from the [task list](https://docs.google.com/document/d/13GVI5yGsx4Aj1L0UYawPRo5ViyB7o-0v_UyMWyrOZMY/edit):

> When clicking on date in the administrator and volunteer reports, a datepicker (https://jqueryui.com/datepicker/) pops out. Add a datepicker to the templates where they are missing. For example, add the datepicker when specifying dates when creating events and jobs.

> The jQuery UI datepicker code has already been imported, so it should be as easy as adding "id="datepicker" to the code, like this:
> 
```
<div class="form-group">
	<label class="col-md-2 control-label">Date</label>
	<div class="col-md-8">
    	<input class="form-control" type="text" name="date" id="datepicker" value="{% if form.date.value %}{{ form.date.value }}{% endif %}">
	</div>
</div>
```

For administrator:
- [x] Create event
- [x] Create job
- [x] Create shift

**Comment by vubo** [comment]
https://github.com/systers/vms/pull/63

**Comment by tapasweni-pathak** [comment]
I think now this can be closed?

**Comment by vubo** [comment]
@tapasweni-pathak yes, thank you!
