### ISSUE TITLE
List of Organization not displayed in Volunteer search form after pressing search button once

### ISSUE THREAD

**Issue by sbansal3096** [systers/vms#594]
## Description
In the volunteer search form of an admin account, list of organizations appear to be empty after pressing search button once.   
## Mocks
Before pressing search button:
![screenshot from 2018-02-04 19-44-08](https://user-images.githubusercontent.com/25177636/35778475-acd055aa-09e4-11e8-8b5d-37f5134cc457.png)
After pressing search button:
![screenshot from 2018-02-04 19-44-35](https://user-images.githubusercontent.com/25177636/35778481-b0534bd8-09e4-11e8-9452-0e3364993796.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by sammy1997** [comment]
I am on this

**Comment by sbansal3096** [comment]
@sammy1997  Sorry, but I actually solved it and was just going to make a pull request.
