### ISSUE TITLE
Add commit guidelines to Contribution_Guide

### ISSUE THREAD

**Issue by kriti21** [systers/vms#598]
## Description
The contribution guide contains information on making pull requests. However, a good pull request should also contain good commits that have a relevant shortlog, description(if needed) and issue reference. Also it should contain information about git branching and changing commit message using `amend`. This would be very helpful for newcomers in open source community.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by kriti21** [comment]
I am working on this.

**Comment by MeepyMay** [comment]
Not a valid issue. Closing.

@kriti21 We created Systers Open Source standard contributing guidelines. We've had meetings/discussions about how to add Project Specific/Repo Specific guidelines, but we haven't completed the Project Specific template yet.
