### ISSUE TITLE
Add __str__ functions for all models to improve django-admin interface

### ISSUE THREAD

**Issue by sammy1997** [systers/vms#599]
## Description
None of the models have __str__ functions written. This makes viewing the objects on django-admin, and also debugging more difficult.

## Mocks
![admin1](https://user-images.githubusercontent.com/24635701/35813745-621a0336-0aba-11e8-803a-3351182af254.png)
![admin2](https://user-images.githubusercontent.com/24635701/35813747-62b250c8-0aba-11e8-98d0-bc64c49e49e2.png)
![admin3](https://user-images.githubusercontent.com/24635701/35813749-631a2aa4-0aba-11e8-8980-a75d3331fb49.png)
![admin5](https://user-images.githubusercontent.com/24635701/35813750-63a4736c-0aba-11e8-8dbc-4ee7365217c7.png)

## Acceptance Criteria
- [ ] Add __str__ or __unicode__ functions for all models

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15-20 mins

@tonythomas01 @tapasweni-pathak Please review this issue

**Comment by sammy1997** [comment]
I would like to work on this.

**Comment by sammy1997** [comment]
@tonythomas01 Please review this.

**Comment by rashmitpankhania** [comment]
Hello sir can i work on this issue?

**Comment by rashmitpankhania** [comment]
we just want to show name with it right?

**Comment by sammy1997** [comment]
Yes @rashmitpankhania I want to show the names or relevant fields for model objects . But as you see I have already claimed this task. I will send a PR as soon as @tonythomas01 or @tapasweni-pathak  reviews this.

**Comment by tonythomas01** [comment]
I think this is a valid improvement, yes

**Comment by sammy1997** [comment]
Ok. I will send a PR then.

**Comment by HargovindArora** [comment]
Hey @sammy1997 are you working on this? If no, can I proceed :-) ?

**Comment by sammy1997** [comment]
I have already sent out a PR for this issue. @HargovindArora
