### ISSUE TITLE
Replace 'None'  by placeholder in in resume upload field of volunteer sign up form

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#602]
## Description
Resume upload field in sign up form should have a placeholder

## Mocks
![image](https://user-images.githubusercontent.com/22369767/35915668-bf7d97bc-0c2d-11e8-8005-01f75491d3ac.png)
![image](https://user-images.githubusercontent.com/22369767/35915672-c56913b8-0c2d-11e8-97b0-85ef39319a7b.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by shreyateeza** [comment]
@anjali-dhanuka I want to work on this issue. Please assign it to me.

**Comment by anjali-dhanuka** [comment]
As you can see I have already sent a pr for this so this one is done.
