### ISSUE TITLE
Improve the URLs for vms apps

### ISSUE THREAD

**Issue by kriti21** [systers/vms#605]
## Description
The URLs that appear for the apps in vms are very exposed. Information such as ids of volunteers, shifts etc are all visible making them very vulnerable for unauthorized changes. Some relevant text instead of ids would be better.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by kriti21** [comment]
I am working on this.

**Comment by abhishekarya286** [comment]
Hi @kriti21. Are you still working on this?

**Comment by anjali-dhanuka** [comment]
@abhishekarya286 I wanted to work on this issue.

**Comment by tonythomas01** [comment]
Which URLs are we talking about ? General requests with id is not a problem - as the access to information for this id is restricted. 

POST should deal with formdata, API payloads etc which do not make sense to be sent as query params.

**Comment by anjali-dhanuka** [comment]
Yeah @tonythomas01 I was talking about the same.

**Comment by anjali-dhanuka** [comment]
Please use the issue template
