### ISSUE TITLE
Allow event names to be repeated in the create event form

### ISSUE THREAD

**Issue by kriti21** [systers/vms#607]
## Description
The problem I see with unique names for events is that it is possible for a two or more organizations to organize same event viz Introduction to Python in more than one places/cities. In that case the dates may differ but jobs might be similar. As a solution we can add organization name in the create event form and allow events with same names differentiated by their unique id.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by kriti21** [comment]
I am working on this.

**Comment by ikbalsingh** [comment]
@kriti21 Are you still working on this?
