### ISSUE TITLE
Report form should have option to enter organization name

### ISSUE THREAD

**Issue by kriti21** [systers/vms#609]
## Description
Refer https://github.com/systers/vms/issues/607 and https://github.com/systers/vms/issues/608

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by kriti21** [comment]
I am working on this.

**Comment by MeepyMay** [comment]
I'm closing this issue. Please update with the issue template. It's missing a "Acceptance Criteria" field & "Estimation" and needs the description in an Agile User Story format. Thanks!
