### ISSUE TITLE
Spelling error in README.md

### ISSUE THREAD

**Issue by PrajwalM2212** [systers/vms#611]
## Description

In README **speak peek** can be changed to **sneak peek**.

## Mocks
<img width="905" alt="screen shot 2018-02-11 at 3 14 52 pm" src="https://user-images.githubusercontent.com/30733262/36072083-45db088a-0f3f-11e8-9512-3022c188eb79.png">

### Update [Required]
- [ ] README.md

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
 2 minutes

**Comment by PrajwalM2212** [comment]
I would like to work on this.

**Comment by Yagya-Chaudhary** [comment]
Can you guide me what has to be done?

**Comment by PrajwalM2212** [comment]
@Yagya-Chaudhary  I have already sent the pull request. . So nothing to be done here.

**Comment by ayushgarg1804** [comment]
This typo has been fixed 2 months back in commit https://github.com/systers/vms/commit/7755e64e244e9f6e4a5c87d74269b011df8baa06
