### ISSUE TITLE
vagrant is not working properly

### ISSUE THREAD

**Issue by rashmitpankhania** [systers/vms#615]
it gives below error when trying to 'vagrant up'

The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format

and after trying to add manually it says no box installed with given url..

**Comment by HargovindArora** [comment]
@rashmitpankhania Please copy and google the exact error! And let us know if it helped! :)

**Comment by rashmitpankhania** [comment]
Ok I will work on it.

On Feb 14, 2018 12:30 PM, "Hargovind Singh Arora" <notifications@github.com>
wrote:

@rashmitpankhania <https://github.com/rashmitpankhania> Please copy and
google the exact error! And let us know if it helped! :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/systers/vms/issues/615#issuecomment-365514161>, or mute
the thread

**Comment by anjali-dhanuka** [comment]
@rashmitpankhania I would suggest u to ask the problems you are facing during set up on slack rather than opening an issue.

**Comment by MeepyMay** [comment]
I'm closing this issue. Please update with the issue template. Thanks!

**Comment by rashmitpankhania** [comment]
Hey,

I just signed the petition "Human Resource Department of India: Remove 75%
Attendance Bar in Graduate Colleges" and wanted to see if you could help by
adding your name.

Our goal is to reach 70,728 signatures and we need more support. You can
read more and sign the petition here:

https://chn.ge/2S2JH52

Thanks!
Rashmit
