### ISSUE TITLE
Password should be asked to confirm in sign up form for volunteer and administrator

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#616]
## Description
As a User, I need to confirm my password, so I don't make a mistake

## Mocks
![screenshot from 2018-02-13 20-03-43](https://user-images.githubusercontent.com/22369767/36158240-dc2a0318-1101-11e8-8547-8412f254dcbf.png)

### Update [Required]
- [x] adding a new field in form
- [x] Error handling in template

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by MeepyMay** [comment]
I'm closing this issue. Please update with the issue template. It's missing a "Acceptance Criteria" field, Estimation section, and needs the description in an Agile User Story format. Thanks!

i.e. As a User, I need to confirm my password, so I don't make a mistake.

**Comment by anjali-dhanuka** [comment]
@MeepyMay Its done.

**Comment by anjali-dhanuka** [comment]
@MeepyMay @ayushgarg1804 @kamsuri @abhishekarya286 Please review the PR.

**Comment by anjali-dhanuka** [comment]
Closed #802
