### ISSUE TITLE
Fix indentation and implement table cell padding in volunteer's profile view 

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#618]
## Description
The elements of the profile view of the volunteer are not properly aligned, they need to be left aligned to the left of the table row. 

## Mocks
![image](https://user-images.githubusercontent.com/22369767/36164082-4a44b4a6-1111-11e8-8990-6eb71f335463.png)

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by Ayukha** [comment]
@anjali-dhanuka  Can i try?

**Comment by anjali-dhanuka** [comment]
@Ayukha I am working on it.

**Comment by Ayukha** [comment]
Cool !🤘 I'll look some other issue to work upon.

**Comment by MeepyMay** [comment]
I'm closing this issue. Please update with the issue template. It's missing a "Acceptance Criteria" field and needs the description in an Agile User Story format. Thanks!

**Comment by anjali-dhanuka** [comment]
@MeepyMay Done.
