### ISSUE TITLE
Unlisted organizations added by volunteers to go into a suggestion list to admin

### ISSUE THREAD

**Issue by sbansal3096** [systers/vms#620]
## Description
In referene to issue #576 
Unlisted organizations added by volunteers can be added in a suggestion list which can be reviewed by admin. He can then either approve or reject them, and on approving they should be added to main list of organizations.
This way we can avoid adding of different versions of same organizations, i.e. Microsoft, Microsoft India, Microsoft Spain(or multiple departments added in the end). And at the same time we can easily increase our database of organizations. 
## Mocks
![image](https://user-images.githubusercontent.com/22369767/40883798-ede4ccc4-6722-11e8-8b8d-8fe856cfa1f7.png)

## Acceptance Criteria
The new list is added on the admin page
### Update [Required]
- [ ] Changes in the code to add new feature

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by anjali-dhanuka** [comment]
@sbansal3096 Which suggestion list are you talking about ?

**Comment by sbansal3096** [comment]
@MeepyMay Please review this.

**Comment by sbansal3096** [comment]
@anjali-dhanuka A new list can be shown to admin which contains all those unlisted organizations that are added by the volunteers. This new list is the one which I am referring to as suggestion list. This list can be shown in the "Organizations" page that appears in admin account.

**Comment by anjali-dhanuka** [comment]
@sbansal3096 You can discuss this on #vms channel . This can be included in ideas list for vms.

**Comment by MeepyMay** [comment]
I'm closing this issue. Please update with the issue template. Thanks!

**Comment by sbansal3096** [comment]
@MeepyMay  done, please reopen it.

**Comment by anjali-dhanuka** [comment]
closed #706
