### ISSUE TITLE
Textbox for Unlisted organisation doesn't hide in edit profile form if an organisation is selected from given list

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#622]
## Description
As a [USER],
I need to hide the textbox for entering unlisted organisation if an organisation is selected from the given list,.

## Mocks
![Uploading Screenshot from 2018-02-14 10-50-25.png…]()

### Update [Required]
- [ ] [Hide unlisted organisation textbox ]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by sammy1997** [comment]
I would like to work on this. @anjali-dhanuka @tonythomas01 @tapasweni-pathak

**Comment by anjali-dhanuka** [comment]
@sammy1997 I have already submitted a pr for this.

**Comment by sammy1997** [comment]
@anjali-dhanuka Ok :+1: . But as it was discussed in the open session @geekanamika had asked May about reporting issues, and we are supposed to wait for a mentor to review the Issue and then assign it according to Ccontribution guidelines . Right @MeepyMay @tonythomas01 ? :)
