### ISSUE TITLE
Hide textbox for resume link if resume file is uploaded in sign up form

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#624]
## Description
As a user I need to hide resume textbox if resume file is uploaded in sign_up form so that resume can't be uploaded 2 times.

## Mocks
![image](https://user-images.githubusercontent.com/22369767/36635634-b4be614e-19de-11e8-90e1-3d4cba344563.png)

### Update [Required]
- [x] [Hide textbox by javascript function]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes

**Comment by anjali-dhanuka** [comment]
@tonythomas01 @tapasweni-pathak should we do this?

**Comment by pranita-s** [comment]
Can I work on this ?

**Comment by anjali-dhanuka** [comment]
@pranita-s I have already submitted a pr for this one.

**Comment by MeepyMay** [comment]
Please include mocks, time estimation, and update description in an Agile User Story format. Thanks!

**Comment by anjali-dhanuka** [comment]
@MeepyMay Its done.

**Comment by anjali-dhanuka** [comment]
@abhishekarya286 @ayushgarg1804 @kamsuri @MeepyMay  Please review the PR.

**Comment by kamsuri** [comment]
Are you talking about the choose file button? 
Please provide a mock-up of the after screen, i'm not able to get this. Or elaborate it a little.

**Comment by anjali-dhanuka** [comment]
The textbox for resume link hides if we have chosen a file in choose file I
have pasted a screenshot too in the PR template.



‌

**Comment by kamsuri** [comment]
Oh, i got your point. Can you tell me the significance of that textbox even on the first screen?

**Comment by anjali-dhanuka** [comment]
@kamsuri We can fill the link of the resume in the textbox.

**Comment by anjali-dhanuka** [comment]
closed #855
