### ISSUE TITLE
Unreachable statements in vms/utils.py

### ISSUE THREAD

**Issue by sammy1997** [systers/vms#627]
## Description
The code vms/utils.py is scattered with unreachable return statements( statements that won't be executed in any case). The code could be cleaned up. 
## Mocks
![screenshot from 2018-02-17 14-14-00](https://user-images.githubusercontent.com/24635701/36339510-b6c0d374-13ed-11e8-879e-6275a8de01a1.png)
![screenshot from 2018-02-17 14-14-05](https://user-images.githubusercontent.com/24635701/36339511-b72acfb8-13ed-11e8-995d-a08c9a6f6ff5.png)

## Acceptance Criteria
- [ ] Remove unnecessary lines of unreachable code 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5-10 mins

@MeepyMay @tonythomas01 @tapasweni-pathak please review this

**Comment by sammy1997** [comment]
I would like to work on this after reviewed by one mentor. @MeepyMay @tonythomas01 @tapasweni-pathak

**Comment by tapasweni-pathak** [comment]
Sure, please go ahead, if you are able to find unreachable code.
