### ISSUE TITLE
After one volunteer search, organisation list disappears

### ISSUE THREAD

**Issue by sammy1997** [systers/vms#630]
## Description
As a user,
I need login as admin,
and search for a volunteer. Use the search feature. When we try to search again after that, the organisation list is no more shown.

## Mocks

![err_org](https://user-images.githubusercontent.com/24635701/36352696-d85d43d2-14e2-11e8-8439-57766f9837ba.png)
![err_org_2](https://user-images.githubusercontent.com/24635701/36352697-d8aa18e2-14e2-11e8-9e68-0da277555aa0.png)

Here is the problem in the code, in if part of search -
![err_org_3](https://user-images.githubusercontent.com/24635701/36352698-d8edac24-14e2-11e8-9473-f56e48812ce4.png)

### Update [Required]
- [ ] Organisations list should be shown after searches also.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5-10 mins

**Comment by sammy1997** [comment]
@tapasweni-pathak @tonythomas01 Please review this issue. I would like to work on this.

**Comment by sammy1997** [comment]
@kamsuri Please review this issue. I would like to work on this.

**Comment by ramitsawhney27** [comment]
Please go ahead and resolve this.

**Comment by sammy1997** [comment]
@ramitsawhney27 I am closing this issue wrt #594 . Thanks.
