### ISSUE TITLE
Error in editing organisation as administrator

### ISSUE THREAD

**Issue by sammy1997** [systers/vms#631]
## Description
As a user,
I need login as admin, and go to edit organisation page and try to edit.

## Mocks
![err_org_edit](https://user-images.githubusercontent.com/24635701/36354114-5f28872a-14f5-11e8-97cd-481181b8d45f.png)
![error_org_2](https://user-images.githubusercontent.com/24635701/36354115-5f75bfa4-14f5-11e8-84a9-8434e9409842.png)

### Update [Required]
- [ ] Error in editing org should be removed.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10-15 mins

I have already got the solution to this error and would like to work on it.

**Comment by sammy1997** [comment]
@tonythomas01 @tapasweni-pathak Please review this issue.

**Comment by sammy1997** [comment]
Here is the solution https://stackoverflow.com/questions/46701426/using-modelformmixin-without-the-fields-attribute-is-prohibited

The issue is here in the OrganizationUpdateView. using form_class = OrganizationForm solves the issue
![screenshot from 2018-02-18 21-50-43](https://user-images.githubusercontent.com/24635701/36354151-df505874-14f5-11e8-9e66-1dbaa099a79e.png)

**Comment by mohitkyadav** [comment]
@sammy1997 It's working for me.
![screenshot 96](https://user-images.githubusercontent.com/25580776/36375487-70c15ade-1595-11e8-83e2-aeda532cf43c.png)

**Comment by pranita-s** [comment]
@sammy1997 Its working for me too

**Comment by anjali-dhanuka** [comment]
@sammy1997 working for me too. I guess it's your local error, I would suggest you to close the issue.

**Comment by sammy1997** [comment]
@anjali-dhanuka @pranita-s @mohitkyadav Have you guys pulled the recent code ? Because technically I didn't touch the file, and I am using the local dev environment as per requirements.txt, so how is this possible? Can you guys pull the code and try one? Else can you post the organization/views.py code snapshot for UpdateVIew class like I have posted ?

**Comment by anjali-dhanuka** [comment]
@sammy1997 I have pulled all the recent code and it's working completely fine for me now too.

**Comment by sammy1997** [comment]
Ok. I am closing this issue @anjali-dhanuka @pranita-s @mohitkyadav @tapasweni-pathak . But I am still getting this error. Even after stashing and pulling all the code.
