### ISSUE TITLE
Link not working in installation instructions.

### ISSUE THREAD

**Issue by mohitkyadav** [systers/vms#632]
## Description
As a contributor,
I need to install and run vms.

The link to [Install python-psycopg2 module](https://github.com/Nerdylicious/vms/wiki#install-python-psycopg2-module) is not working in https://github.com/systers/vms/blob/master/docs/Installation%20Guide.md#using-vagrant.

**Comment by valerycodes** [comment]
To install the python-psycopg2 module, you just need to run ths command `sudo apt-get install python-psycopg2` in  terminal. you can also find it here https://github.com/systers/vms/blob/master/docs/Installation%20Guide.md#install-python-psycopg2-module
I don't think this should be opened as an issue

**Comment by mohitkyadav** [comment]
@valerycodes I have no problem installing the python-psycopg2, the link given in the doc is not working. Don't you think that's an issue?
