### ISSUE TITLE
About Link not Working.

### ISSUE THREAD

**Issue by Ayukha** [systers/vms#634]
Hyperlink to About Page is empty. @tapasweni-pathak

**Comment by anjali-dhanuka** [comment]
@Ayukha where did u find the hyperlink?

**Comment by Ayukha** [comment]
I found it on the hosted site. When i tried to click on the About link. @anjali-dhanuka

**Comment by anjali-dhanuka** [comment]
@ayukha can you share mockups. I can't find it.

**Comment by Ayukha** [comment]
Sure. @anjali-dhanuka 
![screenshot](https://user-images.githubusercontent.com/19167324/36479385-8a929b18-172e-11e8-9b38-2801ee0a7cb4.png)

On clicking the About link , it does'nt  redirects to anyother page.

**Comment by anjali-dhanuka** [comment]
@Ayukha Have u pulled all the code? Previously there was an about like but it was removed in https://github.com/systers/vms/pull/531

**Comment by MeepyMay** [comment]
I'm closing this issue. Please update with the issue template. Thanks!
