### ISSUE TITLE
Internationalization and localization

### ISSUE THREAD

**Issue by valerycodes** [systers/vms#635]
## Description
From first glance I noticed that the application renders content only in English. The goal of internationalization and localization is to allow a single Web application to offer its content in two or more languages and formats tailored to the audience.

**Comment by anjali-dhanuka** [comment]
@valeriecodes that has been implemented already. i18n has been used for the purpose.

**Comment by valerycodes** [comment]
@anjali-dhanuka I can see that but how then do I render content in French rather than English?
FWIW I have tried localhost:8000/fr/ with no luck

**Comment by sammy1997** [comment]
@valerycodes Have a look at this. I guess thiss will help you understand i18n more.

http://www.marinamele.com/taskbuster-django-tutorial/internationalization-localization-languages-time-zones

**Comment by valerycodes** [comment]
@sammy1997 i am not looking for tutorials how to, the question if Internationaliztion have been correctly implemented on the app, how then do I get the website to render content in ffrench bcuz I tried localhost:8000/fr/ and it didn't work

**Comment by sammy1997** [comment]
@anjali-dhanuka I think the project isn't correctly configured to use translation using i18n . Also @valerycodes as the language has been set to fr-fr, the url should have that and not fr . But even for that to work the urls should have been used with i18n_patterns.

**Comment by sammy1997** [comment]
Here is the result
![internationalization](https://user-images.githubusercontent.com/24635701/36414639-fc1974c8-1648-11e8-9c23-97be03be4983.png)

**Comment by sammy1997** [comment]
@tapasweni-pathak @tonythomas01 Can you please review this ? I think this is a valid problem. 

If yes, @tapasweni-pathak @tonythomas01 @valeriecodes @anjali-dhanuka Can I work on this ?

**Comment by anjali-dhanuka** [comment]
@sammy1997 @tapasweni-pathak @tonythomas01 @valeriecodes The url patterns need to be mentioned like given here
https://djangobook.com/internationalization-url-patterns/

**Comment by sammy1997** [comment]
@anjali-dhanuka I have already worked out the solution, the ss above is from a working web app on my local host. :)

**Comment by prachi1210** [comment]
@sammy1997 can you raise a PR for the same? I cannot assign the issue to you without giving you collaborator access

**Comment by MeepyMay** [comment]
I'm closing this issue. Please update with the issue template. Thanks!

**Comment by sammy1997** [comment]
@valerycodes Can you please update this issue with the template ? Or can I  start this issue with the proper template ? @prachi1210 @MeepyMay @tapasweni-pathak
