### ISSUE TITLE
Attribute error : 'module' object has no attribute 'getmro'  

### ISSUE THREAD

**Issue by pranita-s** [systers/vms#637]
## Description
While running the command "python manage.py runserver" I encountered the error "Attribute error:module object has no attribute getmro". Please refer following screenshot:

![error_getmro](https://user-images.githubusercontent.com/14193989/36597401-069f4f34-18cf-11e8-9ffb-a00a215305f2.png)

Previously the command was running absolutely fine. I encountered this error suddenly. After studying about it, it might have occurred due to unexpected changes in .pyc files. 
Installing "django-inspect" takes care of these unexpected changes.

### Update [Required]
- [ ] Inclusion of "django-inspect" in requirements.txt

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by anjali-dhanuka** [comment]
@pranita-s This error occurs due to version problems. Try recloning the project and reinstall python too. django-inspect might not help as it just provides inspection convenience. For more information refer https://stackoverflow.com/questions/38022587/attributeerror-module-object-has-no-attribute-getmro

**Comment by pranita-s** [comment]
@anjali-dhanuka I was able to solve it by installing django-inspect.

**Comment by anjali-dhanuka** [comment]
@pranita-s Did u try recloning and reinstalling and checking versions?

**Comment by pranita-s** [comment]
@anjali-dhanuka I followed the same link when I encountered it. I recloned the project and tried again. Error persisted. Before reinstalling python, I gave django-inspect installation a try. It worked, the error was gone and project was running as before. I felt that instead of recloning the project and reinstalling python, django-inspect was a convenient solution.

**Comment by ikbalsingh** [comment]
@pranita-s  [This should help](https://stackoverflow.com/questions/33751859/django-wont-start-with-a-wierd-error-attributeerror-module-object-has-no-at#answer-38553511)
