### ISSUE TITLE
Instalation Guide not opening from link in Readme.md

### ISSUE THREAD

**Issue by abhishekarya286** [systers/vms#641]
## Description
As a new contributor, I need to build VMS on my machine.
In the installation section of the project's readme file, when I try to open the link for installation guide, I get the following error.

## Mocks
![image](https://user-images.githubusercontent.com/24565261/36852631-35d6cec2-1d92-11e8-9ce9-e320c3e309cb.png).

Error occurs in this part of README.md
```Installation
To get started, read the Installation Guide
```
## Update[Required]
- [ ] On clicking the link, the browser should open the file [Installation_Guide.md](https://github.com/systers/vms/blob/develop/docs/Installation_Guide.md).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor

## Estimation
5 mins.

**Comment by ramitsawhney27** [comment]
I believe in the meantime, you can access the Installation Guide from vms/docs/Installation_Guide.md, it'll be helpful till the link is fixed.

**Comment by abhishekarya286** [comment]
@ramitsawhney27, that can be done.
