### ISSUE TITLE
Internationalization and localization

### ISSUE THREAD

**Issue by sammy1997** [systers/vms#642]
## Description
As a user, we can try to use the two available languages English and French by doing localhost/fr-fr or /en-us. Both gives errors.
( I am reopening a closed issue with the correct template)
## Mocks
![translation](https://user-images.githubusercontent.com/24635701/36926791-8818ef7c-1e9f-11e8-87ad-9c69d865233f.png)

## Acceptance Criteria
- [ ] The internationalization and translations should work.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hour

Tag - beginner/intermediate .

**Comment by sammy1997** [comment]
I have worked on this issue before (this was #635 ) . But it was closed due to wrong issue template. I am referencing the PR to this one. @Buddhiprabha @prachi1210 @tapasweni-pathak Please review this.

**Comment by sammy1997** [comment]
@kamsuri Please review this.

**Comment by abhishekarya286** [comment]
@sammy1997, please correct the typo from "to user" to "to use" in the issue template.

**Comment by sammy1997** [comment]
@Buddhiprabha @prachi1210 @tapasweni-pathak Please review this

**Comment by sammy1997** [comment]
Done @abhishekarya286
