### ISSUE TITLE
Standard regex based password checks

### ISSUE THREAD

**Issue by ramitsawhney27** [systers/vms#644]
## Description
As a user, we can add certain constraints on the passwords (Combination of numbers/alphabets, not all numbers etc). I don’t think it’s needed presently, but it would be needed as the system scales and it is a feature worth adding, simply implementable by regular expressions. The criteria is taken from Microsoft technet for setting strong passwords.

### Updates required
- [ ] Error message when criteria of password is not matched by the below standard.
- [ ] Passwords must use at least three of the four available character types: lowercase letters, uppercase letters, numbers, and symbols.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by abhi20161997** [comment]
@ramitsawhney27  I would like to work on this issue.

**Comment by somyaup** [comment]
@ramitsawhney27  I am working on this issue.

**Comment by ramitsawhney27** [comment]
@somyaup sure go ahead.

**Comment by anjali-dhanuka** [comment]
closes #861
