### ISSUE TITLE
Error in the address field in Volunteer Sign Up page

### ISSUE THREAD

**Issue by abhishekarya286** [systers/vms#645]
## Description
As a user,
I need to sign-up as a volunteer and when I enter my house address in the address field, I get the error. 

## Mocks
The following image shows the error

![image](https://user-images.githubusercontent.com/24565261/36933271-0e11261a-1efc-11e8-96ce-13359863b141.png)
FYI, this is my official house address. It is `House No. 1319, Sector-55`

The problem is with the use of period `.` and the comma `,` in the address field. Here is the example on removing comma and period.
![image](https://user-images.githubusercontent.com/24565261/36933294-94e1afb6-1efc-11e8-93a7-ed0fcdf9bf9b.png)

The issue deals with how regexValidation for comma and period.

### Update [Required]
- [ ] On entering an address containing `.` (dot), `,`(comma), our model should accept that.
### Enhancement to Update [Optional]
- [ ] It should also accept some other special characters like `:` which can be there in a valid address.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes

**Comment by sammy1997** [comment]
I would like to work on this.

**Comment by abhishekarya286** [comment]
Sure @sammy1997.

**Comment by sammy1997** [comment]
@abhishekarya286 Please review the PR.
