### ISSUE TITLE
Previous dates available as Start and End dates of an event.

### ISSUE THREAD

**Issue by m-murad** [systers/vms#651]
## Description
As an admin,
When I create an event I'm able to select previous dates as the Start and End date of the event. Even though the user is not able to finally create the event because an error message is shown. But I should not be able to select previous dates for the event.

## Mocks
![screen shot 2018-03-05 at 8 06 15 pm](https://user-images.githubusercontent.com/17262180/36980648-efa63812-20b0-11e8-8ab7-ea3e86a056b9.png)

### Update [Required]
- [ ] Admin should not be able to select previus dates as Start or End dates for an event.
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by anjali-dhanuka** [comment]
@tapasweni-pathak @tonythomas01 @prachi1210 Please review pr #654
