### ISSUE TITLE
Organisation name not updated in signup form.

### ISSUE THREAD

**Issue by m-murad** [systers/vms#652]
## Description
As an admin,
If I edit the Organisation name the name is not updated in the SignUp form for new volunteers.

## Mocks
![screen shot 2018-03-05 at 8 28 47 pm](https://user-images.githubusercontent.com/17262180/36981821-26b959bc-20b4-11e8-9c75-7f679dc37e8d.png)

![screen shot 2018-03-05 at 8 29 25 pm](https://user-images.githubusercontent.com/17262180/36981827-2aa37936-20b4-11e8-8a59-5669908754f0.png)

### Update [Required]
- [ ] Name of Organization should be updated in the SignUp form.
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by anjali-dhanuka** [comment]
@m-murad It gets updated. You need to restart the server for that.

**Comment by m-murad** [comment]
Don't you think restarting the servers to reflect small change doesn't make sense?
The changes should be shown instantaneous.
What do you think?

**Comment by sammy1997** [comment]
I agree @m-murad . We had a big discussion on this here #577 . Do you think this will be a valid issue ? Then I can work on this issue. It's already open. @kamsuri @prachi1210 Views ?

**Comment by m-murad** [comment]
I think this should be fixed. Let's see what others think.

**Comment by sammy1997** [comment]
Is this valid @prachi1210 @kamsuri ? I would like to work on this if so.

**Comment by abhishekarya286** [comment]
Seems to me an issue. It should automatically update organizations without running the server again.

**Comment by anjali-dhanuka** [comment]
@abhishekarya286 I too think so.

**Comment by sammy1997** [comment]
Can I work on this ? @m-murad @abhishekarya286 @anjali-dhanuka . I was interested in doing this before in #577 but then a discussion followed after which we thought to just keep the issue open.

**Comment by abhishekarya286** [comment]
Cool, you may work on this.

**Comment by sammy1997** [comment]
Ok. On it @abhishekarya286 . Thanks.

**Comment by sammy1997** [comment]
@m-murad @abhishekarya286 I was unable to work on this as I was working on my proposal. I will pick up on this and send a PR in a day or 2. Thanks.

**Comment by anjali-dhanuka** [comment]
@sammy1997 I am reassigning this issue. As it seems you are unavailable to work on it,

**Comment by anjali-dhanuka** [comment]
closed #851
