### ISSUE TITLE
Once signup successfully, the user should automatically be logged in.

### ISSUE THREAD

**Issue by sammy1997** [systers/vms#656]
## Description
As a user, I need to signup. After a successful sign up I am redirected to main page. I should rather be logged in, like in most of the sites( as we don't have verification of mail as a step).
.

## Mocks
![x](https://user-images.githubusercontent.com/24635701/37109891-62c06a8c-2261-11e8-98e0-17d9ef223d6d.png)
![sign_up](https://user-images.githubusercontent.com/24635701/37110007-b7de075e-2261-11e8-8b1e-a47e9a8175f5.png)

### Update
- [ ] After a successful signup, user should be logged in

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by sammy1997** [comment]
@prachi1210 @kamsuri @MeepyMay @tapasweni-pathak Please review this issue. I would like to work on this .

**Comment by abhishekarya286** [comment]
Hi @sammy1997, even I was thinking about this functionality a day ago. Go ahead with this. Any comments on this, @prachi1210?

**Comment by abhishekarya286** [comment]
Also, please remove the "tag" part from the issue template. Otherwise, this issue won't be valid. Try to follow the guidelines. The concerned person will add the required labels.

**Comment by sammy1997** [comment]
Done @abhishekarya286 .

**Comment by sammy1997** [comment]
@prachi1210 @kamsuri @tapasweni-pathak Please review this . I may start working on this then.

**Comment by ramitsawhney27** [comment]
I don’t see much of a point in this, as we would incorporate the functionality of email verification at some point(needed as we scale). In that case this addition is only a one time operation per user, and is obsolete if we include the verification feature.

**Comment by abhishekarya286** [comment]
@sammy1997, I think Ramit is right in this regard. We don't need this functionality because as soon as #534 is merged, this will become obsolete as @ramitsawhney27 pointed out.

**Comment by sammy1997** [comment]
Ok I am closing this issue in that case
