### ISSUE TITLE
Error in showing upcoming shifts/events.

### ISSUE THREAD

**Issue by rohan033** [systers/vms#659]
## Description
Only the upcoming shifts [shift's date-time >= current date-time] should be shown. Currently, older(expired) shifts are also being shown.Similarly, in shift sign up page expired events can be removed from the display list. 
## Mocks
**before**. The first shift in the upcoming shifts is invalid as it has been expired [check the date-time].
![before](https://user-images.githubusercontent.com/17281037/37348628-935e8ae6-26fa-11e8-87d3-ede7a0f7eeea.png)

**similarly when signing for a shift**
![after-event](https://user-images.githubusercontent.com/17281037/37348818-0975fc6e-26fb-11e8-9bca-a7953dbdf077.png)

**What should be done** Remove the inconsistency in showing the upcoming shifts.
![after](https://user-images.githubusercontent.com/17281037/37348906-35374fce-26fb-11e8-906c-f637b6410abc.png)

### Update [Required]
- [ ] Remove the inconsistency in showing the upcoming shifts and events by only showing the valid events/shifts.
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by rohan033** [comment]
I would like to work on this issue.  @abhishekarya286 @tonythomas01 @tapasweni-pathak Please review this.

**Comment by abhishekarya286** [comment]
Cool. Go ahead.

**Comment by rohan033** [comment]
@abhishekarya286 Should we also keep "previous events/shifts" table under the current shift table so that volunteers can see which events have happened earlier?

**Comment by abhishekarya286** [comment]
I think it will be better but first discuss it on slack before coding.

**Comment by Monal5031** [comment]
ping @anjali-dhanuka this was also done?

**Comment by anjali-dhanuka** [comment]
Yes @Monal5031 closed #790
