### ISSUE TITLE
Pin python version to 2.7 in guides

### ISSUE THREAD

**Issue by Monal5031** [systers/vms#661]
## Description
Currently the requirements file pins the django version to 1.7.4 but according to https://docs.djangoproject.com/en/dev/releases/1.7/ , django1.7 doesn't support python version < 2.7, thus the installation guides needs to be updated specifying the use of python2.7 and not 2.5 or 2.6

## Mocks
![screenshot from 2018-03-16 09-46-34](https://user-images.githubusercontent.com/21009189/37503681-cfd2abc2-28ff-11e8-9447-5ea3c80aab14.png)

### Update
- [ ] Pin python version in installation guide to a version 2.7

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by Monal5031** [comment]
@MeepyMay @prachi1210 Please review this issue.

**Comment by sammy1997** [comment]
@Monal5031 I think we should aim at going higher with the versions. So we might pin Python to 2.7, but going down with the Django version is certainly not wanted. @m-murad @tapasweni-pathak @prachi1210 Views on this?

**Comment by Monal5031** [comment]
@sammy1997 Yes I think the same; we shouldn't use lower versions. I researched the code a little and found that our travis builds run on python2.7 thus this issue should be changed to `Update installation guide to specify to use python version 2.7`
@m-murad @tapasweni-pathak @prachi1210 Please check if its valid issue; if thats the case I'd like to send a PR 😄

**Comment by Monal5031** [comment]
ping @MeepyMay @prachi1210 @m-murad @tapasweni-pathak  please review this issue.

**Comment by Monal5031** [comment]
Since we are porting to py3.6 this is no longer valid.
