### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by Monal5031** [systers/vms#662]
## Description
The development as well as the live version of the vms website doesn't have a favicon.

## Mocks
![fav](https://user-images.githubusercontent.com/21009189/37538918-27bd4982-2978-11e8-9b0d-4dee01d06057.png)
![favicon_added](https://user-images.githubusercontent.com/21009189/37538922-2aafabda-2978-11e8-8818-83d29b90d637.png)

### Update
- [ ] Add favicon to vms website.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by sammy1997** [comment]
If verified, can I work on this?

**Comment by Monal5031** [comment]
@sammy1997 I'm waiting for @MeepyMay @prachi1210 to verify this issue otherwise I'd sent the PR already.

**Comment by ramitsawhney27** [comment]
Looks like a valid enhancement, please go ahead.
