### ISSUE TITLE
Update Docker Setup Wiki

### ISSUE THREAD

**Issue by manmeet0307** [systers/vms#667]
## Description
As a contributor,
I need to set up my environment for the project using docker,
so that I can contribute to project.
I faced issue :Unable to find image 'vms:latest' locally

## Mocks
![image](https://user-images.githubusercontent.com/32425680/38452882-7b83fe00-3a6a-11e8-86ca-ecfd27219142.png)

### Update [Required]
To Change docs for vms 6th step 
from Run docker run -e SECRET_KEY=foobarbaz vms
to
Run docker run -e SECRET_KEY=foobarbaz vms_web

## Estimation
10 minutes

**Comment by m-murad** [comment]
@manmeet0307 Do you want to fix this?
