### ISSUE TITLE
Tests for administrator profile view

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#670]
## Description
As a User, I need to add tests for administrator profile view, so that I can increase the code coverage.

## Mocks
![image](https://user-images.githubusercontent.com/22369767/38911635-4c85685a-42ee-11e8-955c-a8338433c8f0.png)

## Acceptance Criteria
- [ ] Tests for administrator profile view

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by anjali-dhanuka** [comment]
@tapasweni-pathak @m-murad @abhishekarya286 @ramitsahwney27 @prachi1210 @kamsuri @sammy1997 @tonythomas01 Please review the issue.

**Comment by anjali-dhanuka** [comment]
@ayushgarg You too please review the issue.

**Comment by kamsuri** [comment]
I'm not really sure if this is required. @ayushgarg & @abhishekarya286 can you provide your suggestions.

**Comment by anjali-dhanuka** [comment]
@kamsuri The administrator profile feature was added recently, thus there are no tests written for the same.

**Comment by sammy1997** [comment]
@anjali-dhanuka I don't think we need test as profile view will just render the data to html, and that woudn't hamper the coverage. I think test for editing can be added though. Views @kamsuri @ayushgarg @abhishekarya286 @m-murad ?

**Comment by sammy1997** [comment]
@anjali-dhanuka I don't think we need test as profile view will just render the data to html, and that woudn't hamper the coverage. I think test for editing can be added though. Views @kamsuri @ayushgarg @abhishekarya286 @m-murad ?

**Comment by anjali-dhanuka** [comment]
@Monal5031 @naman1901 I was suggesting writing a test_administratorProfile.py and writing it on the same lines as the https://github.com/systers/vms/blob/develop/vms/volunteer/tests/test_volunteerProfile.py

**Comment by Monal5031** [comment]
Will be done under #685 I guess. If not I'll reopen.
