### ISSUE TITLE
Tests for link navigation

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#671]
## Description
As a User, I need to add tests for link navigation, so that I can increase the code coverage.

## Acceptance Criteria
- [ ] Tests for link navigation

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by anjali-dhanuka** [comment]
@tapasweni-pathak @m-murad @abhishekarya286 @ramitsahwney27 @prachi1210 @kamsuri @sammy1997 @tonythomas01 Please review the issue.

**Comment by anjali-dhanuka** [comment]
@ayushgarg

**Comment by kamsuri** [comment]
@anjali-dhanuka It would be better if you explain it in a bit detailed manner or you can put 2 screenshots showing the link and the target page, just for an example of link navigation. Also, do mention the present code coverage and in you PR, mention the updated one. Update the issue and you can start working on this afterwards.

**Comment by kamsuri** [comment]
Also, in acceptance criteria add a point that code coverage gets increased which is main motive of the issue. And update the other one to passing/correct(or find some other appropriate word :P) tests.

**Comment by naman1901** [comment]
Has this been assigned to anyone? If not, @monal5031 can look into it as he's going to be writing tests for GSoC.

**Comment by Monal5031** [comment]
Yes, this can be added in my project goals.

**Comment by anjali-dhanuka** [comment]
Yes @Monal5031 @naman1901 I found this issue in documentation of a previous GSoC student. Thus I opened it. I can't share the screenshots as the tests are not in action for VMS.

**Comment by Monal5031** [comment]
Half are merged and half are in review.
