### ISSUE TITLE
Wiki Sidebar Update

### ISSUE THREAD

**Issue by ExactlyMay** [systers/vms#672]
## Description
As a newcomer,
I need to navigate the repo successfully,
so that I can understand where the project is in its development.

## Mocks
![screen shot 2018-04-19 at 3 47 20 pm](https://user-images.githubusercontent.com/2440938/39014663-06dcb230-43e9-11e8-997c-96a89b7c55e8.png)

### Update [Required]
- [ ] Update to [the template](https://docs.google.com/document/d/1h53P1h5g9hWEUsnOhpl9PgVzbWEGhTMIP2Pyta-MYSA/edit?usp=sharing) as discussed by the Community.
### Enhancement to Update [Optional]
- [ ] Link all GSoC/Outreachy student's pages if applicable.
- [ ] Link Final Reports page if applicable.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 3 Community Members.

## Estimation
10-30 minutes

**Comment by adi44** [comment]
I would like to work on this issue

**Comment by adi44** [comment]
can I be assigned this issue

**Comment by anjali-dhanuka** [comment]
@adi44 You can work on the issue

**Comment by anjali-dhanuka** [comment]
@adi44 Are u on the issue?

**Comment by adi44** [comment]
I am not

**Comment by tapasweni-pathak** [comment]
:wave: @adi44, you would need to create a `_Sidebar` to have a side bar in the Wiki. This has some [more](https://help.github.com/articles/creating-a-sidebar/) information, let me know if you don't have the permission I'll set up the base and then you can update with more information.

**Comment by adi44** [comment]
Hi @tapasweni-pathak I dont have the rights

**Comment by anjali-dhanuka** [comment]
@ExactlyMay Can u please help?

**Comment by anjali-dhanuka** [comment]
@ExactlyMay 
![image](https://user-images.githubusercontent.com/22369767/43713176-46382542-9996-11e8-8867-049599d36217.png)
Done so closing this.
