### ISSUE TITLE
Fix Selenium to work with newer versions of Firefox

### ISSUE THREAD

**Issue by naman1901** [systers/vms#676]
## Description
Selenium doesn't work with Firefox versions 47+. 

### Update [Required]
- [ ] Debug Selenium to work with newer Firefox versions
- [ ] Integrate Selenium with the Travis tests
- [ ] Update Installation Docs

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

**Comment by Monal5031** [comment]
Done in #682
