### ISSUE TITLE
Location specification for the event/job/shift 

### ISSUE THREAD

**Issue by vubo** [systers/vms#68]
Task 15 from the [task list](https://docs.google.com/document/d/13GVI5yGsx4Aj1L0UYawPRo5ViyB7o-0v_UyMWyrOZMY/edit):

>Need to add location (such as country, city and state) that the event/job/shift is being held at. Country, city and state fields should only need to belong to the Event, Job or Shift models. I would ask Rose, as an administrator of VMS, where she would like to specify the location. Does she want to specify location when creating Events? Or when creating Jobs? Or is it possible that shifts can take place at multiple locations, so she should specify the location at the Shift level?

@rosariorobinson would you answer these questions please? Should I program the location specification at the Event, Job, or Shift? Thank you!

![createevent](https://cloud.githubusercontent.com/assets/7673323/8393686/85370524-1d1b-11e5-91c7-d6e6d27cb61b.png)

**Comment by rosariorobinson** [comment]
Jobs are associated to an event, but not necessarily to a location. For instance, we have GSoC mentors which is a volunteer job/position. Mentors are located where ever they are located.

Events are always associated to a specific location. If we host a meetup, that is always at a particular location/city.

Shifts are usually associated to an event and a location. For GHC, we have specific volunteer jobs, and our GHC is held at different locations every year so it's important to capture their shift and location.

I hope this helps. Let me know if you need more clarification.

**Comment by vubo** [comment]
@rosariorobinson I created for Event new location fields: country, state, city, address, venue
Should I create the same fields for Shift?

![eventloc](https://cloud.githubusercontent.com/assets/7673323/8509692/63f38c28-22b3-11e5-80a7-eb77b7c3b35e.png)

**Comment by rosariorobinson** [comment]
Yes. Shifts for an event can be at a different venue (including city and state) and/or date/time as well.

**Comment by tapasweni-pathak** [comment]
@vubo Is this done for shifts also?

**Comment by vubo** [comment]
@tapasweni-pathak yes, here is the PR: https://github.com/systers/vms/pull/89

**Comment by tapasweni-pathak** [comment]
Closing this then. :smile:
