### ISSUE TITLE
Manage the shift hours

### ISSUE THREAD

**Issue by vubo** [systers/vms#69]
Task 17 from the [task list](https://docs.google.com/document/d/13GVI5yGsx4Aj1L0UYawPRo5ViyB7o-0v_UyMWyrOZMY/edit):

@rosariorobinson should be able administrators to manage (add/edit/delete) the shift hours for volunteers?

![shift](https://cloud.githubusercontent.com/assets/7673323/8393749/3d4bf1ea-1d1e-11e5-91cf-6e52a169e871.png)

**Comment by rosariorobinson** [comment]
Yes, the level should be...

Volunteer managers (VM) should be able to add/edit/delete shift hours and administrators too. This is for backup purposes in the even VMs are are unable to do so. This can happen.

**Comment by vubo** [comment]
I created the level.

Now we have Upcoming Shifts list and Shifts with Logged Hours list.

In the Upcoming Shifts list administrators/managers can Cancel Shift Registration and Log Hours for a volounteer.

In the Shifts with Logged Hours list administrators/managers can find logged hours, edit this hours and cancel them.

![manage](https://cloud.githubusercontent.com/assets/7673323/8545501/a6ae0edc-24af-11e5-95b8-00ee4c08f2c3.png)

**Comment by rosariorobinson** [comment]
@vubo what is the difference between shift registration and shift? Is it cancelling a shift registration so that no one can register for that shift, or is it cancelling an entire shift? I think I'd like to have both.

**Comment by vubo** [comment]
@rosariorobinson "Cancel Shift Registration" is cancelling a shift registration **for the volounteer**, who signed up for this shift. And this whole page "Manage Shifts" is for a selected volounteer (first you need to select a specific volunteer). 

Administrators can **delete an entire shift** in the Settings -> Shifts (after deleting nobody can see this shift).

![delete](https://cloud.githubusercontent.com/assets/7673323/8553403/849eec7e-24e3-11e5-94f4-427b453bd811.png)

Is it ok? Or do you need another option?

**Comment by rosariorobinson** [comment]
Oh okay, understood. No this fine. Thanks for explaining.
