### ISSUE TITLE
Use dicts (instead of lists) to represent model instances in tests

### ISSUE THREAD

**Issue by Monal5031** [systers/vms#697]
## Description
As a developer,
I need reference structured data in dict and not list,
the population of data, creation of instances, form filling (in selenium tests) from variables(references) is a use case of dict thus we need to change all instances where we populate data/create instances/fill forms(selenium) from lists

## Mocks
N/A

## Acceptance Criteria
- [ ] Update all instances of population of data from lists to dict
- [ ] Update all instance creation from lists to dict (In shift.utlils.py and some other places too)
- [ ] Update test_data.json to follow dict structure.
- [ ] Update dependent changes which were using these functions.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10-12 hours

**Comment by tonythomas01** [comment]
Please change title to: "Use dicts (instead of lists) to represent model instances in tests" . Thanks.

**Comment by Monal5031** [comment]
Completed in #866
