### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by vubo** [systers/vms#70]
Task 20 from the [task list](https://docs.google.com/document/d/13GVI5yGsx4Aj1L0UYawPRo5ViyB7o-0v_UyMWyrOZMY/edit):

@rosariorobinson would you like email notifications to be sent to volunteers when a shift they have signed up for is coming up?

**Comment by rosariorobinson** [comment]
Yes, that is good practice. Default should be 1 week notice, but also allow users to configure this themselves, perhaps maybe add a 1 day notification. Similar to like when you set up a meeting in Google calendar. You can set reminders.
