### ISSUE TITLE
Implement class based views for Login and Logout

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#708]
## Description
As a USER,
I need class based views,
so that I can make django 1.11 work better.

### Update [Required]
- [x] [Replace login and logout function based view by class based view]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by kamsuri** [comment]
@anjali-dhanuka this will be a good enhancement, go ahead with this.

**Comment by ayushgarg1804** [comment]
Go ahead @anjali-dhanuka

**Comment by anjali-dhanuka** [comment]
Closing, implemented in #711
