### ISSUE TITLE
Email notification to volunteers

### ISSUE THREAD

**Issue by kamsuri** [systers/vms#714]
## Description
As a USER,
I need to receive email notifications for shift assignment and it's cancellation,
so that I can update my scheduler with the same.

### Update [Required]
- [x] [Email notification for shift assignement]
- [x] [Email notification for shift cancellation]

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 2 mentors.

## Estimation
3 hours

**Comment by anjali-dhanuka** [comment]
closes #716
