### ISSUE TITLE
VMS Installation Guide fixes

### ISSUE THREAD

**Issue by veniemi1** [systers/vms#72]
Here are the improvements I would add to the VMS installation guide. I can put these in when I get back from training at the end of July if need be. 

Vms/Installation Guide.md:

Clone Project:
        *`git clone https://github.com/systers/vms.git` 
        *Make sure you are in the top level directory of where you want the cloned files to end up.
        *Check the contents of the destination directory to ensure that clone took place. 
Download Systers Ubuntu Virtual Machine
         *Replace content of Vagrantfile with file from @willingc in issue #49.
Using Vagrant
	*Type everything in the command prompt rather than the virtual machine. Leave the virtual machine window open though. 
	*Use Linux commands in command prompt. 
Install python-psycopg2 module
	*Stay in the VM while doing this.
-	Setup PostgreSQL
	*x.x is version number. I used version 9.3.
	*Before entering `python manage.py syncdb` command go into the file /vms/vms/vms/settings.py and under `DATABASES` change ‘myuser’ to ‘vmsadmin’ and ‘mypassword’ to ‘0xdeadbeef’

`# Database

DATABASES = {
    'default': {
        'ENGINE' : 'django.db.backends.postgresql_psycopg2',    #your database engine
        'NAME' : 'vms',             #the name of your database
        'USER' : 'vmsadmin',          #your DBMS username
        'PASSWORD' : '0xdeadbeef',  #your DBMS password
        'HOST' : 'localhost',
    }
}`

@willingc Here are my changes for the Installation Guide. Thank you again for all your help these last three weeks!

**Comment by willingc** [comment]
@veniemi1 Thank you! These are great suggestions.

I will update the docs with your suggestions. When you return, please do test them out. It's been my pleasure to mentor you :smiley: :cake: :bouquet:
