### ISSUE TITLE
TypeError at /en-us/shift/add_hours/volunteer_id/shift_id

### ISSUE THREAD

**Issue by Monal5031** [systers/vms#725]
## Description
As a volunteer,
I need to log my hours in the system.

## Mocks
![error](https://user-images.githubusercontent.com/21009189/41497957-8b4be028-717e-11e8-994f-805e5bad43ee.png)

## Acceptance Criteria
- [] Modify `wrapped_view` in `check_correct_volunteer` to use kwargs as views with multiple kwargs also access this function.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by anjali-dhanuka** [comment]
Hi @abhishekarya286 @ayushgarg1804 @kamsuri Can you please approve this issue so that I can send a PR for the same.
