### ISSUE TITLE
TypeError at /en-us/shift/view_hours/<volunteer_id>

### ISSUE THREAD

**Issue by Monal5031** [systers/vms#727]
## Description
As a volunteer,
I need to view my hours in the system.

## Mocks

![error](https://user-images.githubusercontent.com/21009189/41497989-514e61ba-717f-11e8-85d9-61a038b12641.png)

## Acceptance Criteria
- [] Modify `wrapped_view` in `check_correct_volunteer` to use kwargs as views with multiple kwargs also access this function.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by anjali-dhanuka** [comment]
Hi @abhishekarya286 @ayushgarg1804 @kamsuri Can you please approve this issue so that I can send a PR for the same.

**Comment by ayushgarg1804** [comment]
@Monal5031 please close if commit 8c724ea is all thats required :)
