### ISSUE TITLE
job inside an event not unique

### ISSUE THREAD

**Issue by jayesh92** [systers/vms#73]
While testing I found admin user can create a job with same details twice inside one event. Also, the same applies for shift inside job.  Shouldn't it be unique ?

**Comment by smarshy** [comment]
@tapasweni-pathak This issue still exists. It is possible to create a  job with the exact same details. This can lead to lots of confusion when there are many events and jobs and a volunteer is trying to sign up. Shouldn't some parameter such as  job name be made unique?

**Comment by tapasweni-pathak** [comment]
@smarshy Can you also test if event creation is unique or not? Is it possible to create two events with all the details same?

**Comment by smarshy** [comment]
@tapasweni-pathak It is not unique. Two events can have exact same details too.

**Comment by tapasweni-pathak** [comment]
I opened two issue for this problem, #329 and #330. Thanks for the work. :+1:
