### ISSUE TITLE
Log Hours constraint 

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#740]
## Description
As a Volunteer, I must only be able to log my hours for a shift only after the start time for the shift.

## Mocks
![image](https://user-images.githubusercontent.com/22369767/41815123-9bee2c0a-777e-11e8-9ffa-c42893921d34.png)

### Update [Required]
- [ ]  Set constraint on log hours view

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
1  hour

**Comment by Monal5031** [comment]
Yup this is a valid issue :+1: but some things I had in mind here worth discussing I guess,
Do we allow edit of logged hours?
Should the button of log hours be disabled if volunteer has logged once?

**Comment by kamsuri** [comment]
@anjali-dhanuka this issue is fine, go ahead with this. And yes as monal asked, does the button get disabled?

**Comment by ayushgarg1804** [comment]
I think it might be better if we enable logging hours after shift has started not ended as partial logging might be helpful to volunteer

**Comment by anjali-dhanuka** [comment]
Closed #792
