### ISSUE TITLE
Remove nbsp from vms code

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#746]
## Description
As a Developer,
I need to remove &nbsp from the code,
so that I can use padding and spaces which is a good practice to use.

## Mocks
![image](https://user-images.githubusercontent.com/22369767/41824866-346accd4-7835-11e8-9f22-7390187178f3.png)

### Update [Required]
-Replace &nbsp with padding

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 2 mentors.

## Estimation
2 hours

**Comment by anjali-dhanuka** [comment]
@ayushgarg1804 @abhishekarya286 @Monal5031 @kamsuri please review.

**Comment by Monal5031** [comment]
@anjali-dhanuka wasn't this done in #760 ?

**Comment by anjali-dhanuka** [comment]
That PR was reverted @Monal5031

**Comment by Monal5031** [comment]
@anjali-dhanuka btw some test will fail if you remove these blank lines, you'll need to update that too.
I remember that some test used split of spaces.

**Comment by anjali-dhanuka** [comment]
closed #842
