### ISSUE TITLE
Error in test_shiftSignUp of Event app

### ISSUE THREAD

**Issue by Monal5031** [systers/vms#747]
## Description
As a developer/tester,
I need to make sure all tests are stable,
so that I can ensure the proper working of project.

Unfortunately [this](https://github.com/systers/vms/issues/728) issue didn't successfully fix the issue, so a new alternative as discussed in [slack ](https://systers-opensource.slack.com/archives/C0QJXC8SK/p1529824141000074) was to break the test in 3 different tests.

## Mocks
[img](https://user-images.githubusercontent.com/21009189/41498166-f74e9ad6-7183-11e8-8fb9-1fe0ccbb1a28.png)

### Update [Required]
- [ ] Break `test_search_event` in 3 different checks as mentioned in slack.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
10 mins.

**Comment by Monal5031** [comment]
ping @prachi1210 @abhishekarya286 @naman1901 @pavankm @anjali-dhanuka @ayushgarg1804 Please review.

**Comment by abhishekarya286** [comment]
Yes, go ahead

**Comment by abhishekarya286** [comment]
Have you sent a PR?
