### ISSUE TITLE
Validate City and Country

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#75]
@vubo  I just saw yesterday's recording. I have one question, are we validating city and countries, when the user is entering the data in create event e.t.c?

If not, I feel its good to do that. There are packages that can achieve that for us.

**Comment by vubo** [comment]
@tapasweni-pathak thank you for watching and for your time :)
No, we don't do it, but it's a great idea! Do you have any advice? Any tools for implementing this?

**Comment by tapasweni-pathak** [comment]
@vubo,  @exploreshaifali recently implemented the check for cities and countries, in Systers Portal. 

@exploreshaifali Can you tell us which package you used?

**Comment by exploreshaifali** [comment]
Sure.

@vubo I used a django package, [django-cities-light][https://pypi.python.org/pypi/django-cities-light] to validate cities and countries.  They provide good doc, let me know if you need some help in it.

**Comment by tapasweni-pathak** [comment]
Thanks @exploreshaifali. :+1: :bouquet:

**Comment by saganshul** [comment]
I will do this work !

**Comment by saganshul** [comment]
@tapasweni-pathak  @vubo  #190 PR submitted please review.

**Comment by Monal5031** [comment]
@anjali-dhanuka is this done in citiies light PR?

**Comment by anjali-dhanuka** [comment]
Yes @Monal5031
