### ISSUE TITLE
No view for getting detailed information of an event

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#751]
## Description
As a User,
I need a view,
so that I can get information about location, description etc of an event.

## Mocks
![image](https://user-images.githubusercontent.com/22369767/41986541-1590086c-7a54-11e8-8cda-e783c5df30ff.png)

### Update [Required]
- [ ] [Add a detail view for event]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
3  hours

**Comment by anjali-dhanuka** [comment]
@abhishekarya286 @ayushgarg1804 @kamsuri Please review the issue.

**Comment by ayushgarg1804** [comment]
I'll suggest if we push this feature along with add description PR #723. Since there is a major requirement of this feature after adding description in event info.

**Comment by anjali-dhanuka** [comment]
@ayushgarg1804 @kamsuri What do you suggest?
