### ISSUE TITLE
Add checks for other field in all apps

### ISSUE THREAD

**Issue by Monal5031** [systers/vms#752]
## Description
Currently only the necessary fields in all apps are being checked there should be a check for other fields too viz. address, etc we are currently ignoring city, state and country as those will be checked separately in @anjali-dhanuka 's PR 

## Mocks
N/A

### Update [Required]
- [ ] Modify create functions to accept more than the required args
- [ ] Modify existing DB tests to cover test case at least once
- [ ] Modify selenium tests to cover test case at least once

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
4-5 hrs

**Comment by ayushgarg1804** [comment]
Why is it just for event app? Are you updating other PRs for other tests?

**Comment by Monal5031** [comment]
Oh my bad. In the meeting we only talked about event app so I thought it needed to be done for event only. I'll update it for other apps too.

**Comment by ayushgarg1804** [comment]
I just took event as an example 😅.

**Comment by Monal5031** [comment]
Lol yeah i get it now, will update it soon. I have to start with documentation first its important atm.
