### ISSUE TITLE
Upcoming shifts also shows past shifts

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#759]
## Description
As a Volunteer,
I need to see only my future shifts(the shifts whose start time> current time) in Upcoming shifts,
so that I can get the proper list of upcoming shifts.

## Mocks
![image](https://user-images.githubusercontent.com/22369767/42130019-c22f4712-7cf3-11e8-99d4-ee55c19b2542.png)

### Update [Required]
- [ ] Add time constraint on upcoming shifts

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by anjali-dhanuka** [comment]
@abhishekarya286 @ayushgarg1804 @kamsuri Please review the issue.

**Comment by abhishekarya286** [comment]
A valid issue

**Comment by kamsuri** [comment]
Hey @anjali-dhanuka, what do you mean by future unlogged shifts? All the future shifts will be the unlogged ones only, right?

**Comment by ayushgarg1804** [comment]
Valid issue, just as @kamsuri said all the future shifts implies unlogged shifts for future.

**Comment by anjali-dhanuka** [comment]
Done #789
