### ISSUE TITLE
Add timepicker everywhere

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#76]
@vubo I don't see a time picker in create shift? There are start and end time fields there. 

Can we add the timepicker wherever we are using the time related fields?

**Comment by vubo** [comment]
@tapasweni-pathak Yes, I plan to do it. I wanted to test it first on a single object (edit shift) and then just extend to others. Rose is also proposed to add to the profile setting-time-feature: p.m/a.m. or 24 hours.

**Comment by vubo** [comment]
https://github.com/systers/vms/issues/80

**Comment by willingc** [comment]
Closed #113 

Thanks @vubo and @tapasweni-pathak.

A tip for both of you...when merging a pull request if you put `Closes #xx` in the merge message the issue gets closed by GitHub (https://help.github.com/articles/closing-issues-via-commit-messages/). :smile:

**Comment by tapasweni-pathak** [comment]
This is awesome @willingc. :+1: Thanks for the link. :smile:
