### ISSUE TITLE
Add job search feature on administrator's end

### ISSUE THREAD

**Issue by kamsuri** [systers/vms#769]
## Description
As an administrator,
I need the functionality to search jobs,
so that i can filter them according to my requirements.

## Acceptance Criteria
- [ ]  Jobs can be searched using name, event, start date, end date, state, city or country.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
1.5 hours

**Comment by anjali-dhanuka** [comment]
closes #778
