### ISSUE TITLE
Add job search feature on volunteer's end

### ISSUE THREAD

**Issue by kamsuri** [systers/vms#771]
## Description
As a volunteer,
I need the functionality to search jobs,
so that i can filter them according to my requirements.

## Acceptance Criteria
- [ ]  Jobs can be searched using job name, start date or end date.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
1.5 hours

**Comment by anjali-dhanuka** [comment]
Closes #778
