### ISSUE TITLE
Add event search feature on volunteer's end

### ISSUE THREAD

**Issue by kamsuri** [systers/vms#772]
## Description
As a volunteer,
I need the functionality to search events,
so that i can filter them according to my requirements.

## Acceptance Criteria
- [ ]  Events can be searched using name, start date, end date, country, state or city.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
1.5 hours

**Comment by anjali-dhanuka** [comment]
Done #777
