### ISSUE TITLE
Add event and job field in Volunteer Search

### ISSUE THREAD

**Issue by kamsuri** [systers/vms#773]
## Description
As an administrator,
I need the functionality to search volunteers from event and job names as well.

## Acceptance Criteria
- [ ]  Volunteers can be searched using event or job name.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
1.5 hours

**Comment by anjali-dhanuka** [comment]
Done #774
