### ISSUE TITLE
Document Automated Testing in VMS

### ISSUE THREAD

**Issue by Monal5031** [systers/vms#779]
## Description
As a developer, I should document all the work I have done so that it can be used by future developers as reference and making it easy to contribute to the project.

## Mocks
N/A

### Update [Required]
- [x] Document failing test with failure reason and corresponding issue
- [x] Document Installation setup
- [x] Document Design Document
- [x] Document existing tests with docstrings.
- [ ] Document a short tutorial for automated testing in repo.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
 14-16 hours

**Comment by Monal5031** [comment]
@ayushgarg1804 I was thinking to create a separate doc to explain test cases 1-2 line each wouldnt docstrings repeat the same thing then?
Since tests dont have return vals and params so docstrings will only have test case description only.

**Comment by Monal5031** [comment]
Or shall I only document them in docstrings only and not a separate document?

**Comment by ayushgarg1804** [comment]
Its up to you actually. If you document them in docstrings you can automatically create a documentation from it and if you create a separate document then it will me more personalized and specific.
