### ISSUE TITLE
Not allowing use to create a post dated event

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#78]
@vubo Do we have one check which restricts the user to not create an event which is ended already, post dated event?

**Comment by vubo** [comment]
@tapasweni-pathak unfortunately, no. But I will do it. Thank you for the tip!

**Comment by tapasweni-pathak** [comment]
Great. :ok_hand:

**Comment by vubo** [comment]
@tapasweni-pathak could you close this issue please? PR https://github.com/systers/vms/pull/101

**Comment by tapasweni-pathak** [comment]
Done.
