### ISSUE TITLE
Add model tests for administrator app

### ISSUE THREAD

**Issue by Monal5031** [systers/vms#780]
## Description
As a developer, I need to make sure that everything in the project is tested so as to maintain quality of the project.

## Mocks
N/A

### Update [Required]
- [ ] Model tests for administrator app

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentor.

## Estimation
0.5 hours

**Comment by abhishekarya286** [comment]
What exactly will you be doing here?

**Comment by Monal5031** [comment]
This part was left in administrator tests, you can see in event app that there is `test_model` test which is missing here. I'm finding missing things while I'm going through the project for documentation.
