### ISSUE TITLE
Past Events or Ongoing Events Not to be editable

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#784]
## Description
As a User,
I need to not allow the administrators to edit the ongoing or past events,
so that I can avoid unnecessary changes.

### Update [Required]
- [x] Put a check on event date
- [x] Restrain from editing the event 

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
2 hours

**Comment by anjali-dhanuka** [comment]
@abhishekarya286 @ayushgarg1804 @kamsuri Please review

**Comment by ayushgarg1804** [comment]
Go ahead 👍

**Comment by anjali-dhanuka** [comment]
closes #856
