### ISSUE TITLE
Unique ids for event

### ISSUE THREAD

**Issue by tapasweni-pathak** [systers/vms#79]
@vubo Do we have unique ids associated with every new event. If not, I feel its good to add it.

If there are two events having same details, name and same start and end time, are we able to distinguish between the two in our code?

**Comment by vubo** [comment]
@tapasweni-pathak it's a good point. Event model has only name, start_date and end_date: https://github.com/systers/vms/blob/develop/vms/event/models.py#L4
Should I create a new hidden ID-field which will be filled in automatically?

**Comment by tapasweni-pathak** [comment]
@vubo Yes, that's seems the best we can do. Something which is not visible but it is there inside the database.

**Comment by willingc** [comment]
This issue is related to Issue #73.

**Comment by vubo** [comment]
@tapasweni-pathak I'm working on this issue right now and I noticed that Django itself automatically creates the required id field. Here is the table for events:

![image](https://cloud.githubusercontent.com/assets/7673323/8937075/7ce9400a-3556-11e5-9587-95110a97fcc6.png)

**Comment by tapasweni-pathak** [comment]
Yes, right, Django does it. :) Cool. Then we don't need to do it. 

Will we be able to free them if someone deletes the event associated with them?

**Comment by vubo** [comment]
What do you mean? That this id (from the deleted event) will be assign to a new event?

**Comment by tapasweni-pathak** [comment]
Yes. If a event gets deleted, it has a associated unique id as 123. Then we will be able to reuse that id? or will it keep incrementing, no matter if some previous ones get freed?

**Comment by vubo** [comment]
Honestly, I do not know how Django assigns IDs. Have you worked with this issue?

**Comment by tapasweni-pathak** [comment]
I know how Django assigns it, but not sure if it reuses/frees the previously generated one. I'll try it and then we will look into this.

**Comment by vubo** [comment]
Thank you :)

**Comment by varunnaganathan** [comment]
Reusing/freeing the ID is the responsibility of the database used and not that of django.Generally ,for most databases the auto increment field does not reset when few entries are deleted.
If we desire the field values to be reused on deletion of entries we need to implement a custom ID field.

**Comment by smarshy** [comment]
@tapasweni-pathak Since unique ids are being used by default, can this issue be closed now? Perhaps another one could be opened for re-use of deleted ids, if needed.

**Comment by tapasweni-pathak** [comment]
@smarshy Yes, closing this. Please raise an issue for the other one.
