### ISSUE TITLE
Communication with Portal Api 

### ISSUE THREAD

**Issue by anjali-dhanuka** [systers/vms#796]
## Description
As a User, I want to create the events from the API in VMS.

### Update [Required]
- [ ] Fetch meet-ups from Portal 
- [ ]  Send them to createview

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by abhishekarya286** [comment]
valid issue

**Comment by anjali-dhanuka** [comment]
closes #799
