### ISSUE TITLE
Feedbacks from VMS users

### ISSUE THREAD

**Issue by vubo** [systers/vms#82]
@rosariorobinson offered to run the test VMS project and to collect the feedbacks and reviews of those users who will test the project.

@willingc @tapasweni-pathak maybe you know a suitable platform for the collection of the users feedbacks? Thank you!

**Comment by rosariorobinson** [comment]
When you are ready, please let me know. I will have someone upload new code to our test server so that we can start testing. 

cc @jproft

**Comment by vubo** [comment]
@rosariorobinson perhaps we can use a google plus group for this?
https://plus.google.com/b/114580226929432094000/114580226929432094000/posts

**Comment by tapasweni-pathak** [comment]
@vubo I would suggest Google Forms. It easy to share the forms everywhere, get input from user, does not require any sign up.

We can have some feature specific questions in the form and some suggestions, what they liked most, something in this line, so that we will touch almost all parts of our application. It should not be too long also.

**Comment by vubo** [comment]
@tapasweni-pathak thank you for the idea! It looks very good and does not require any sign up - perfekt. I created a test form: http://goo.gl/forms/Ojr8pf7LSj

**Comment by tapasweni-pathak** [comment]
@vubo :+1:

**Comment by willingc** [comment]
My apologies for the late response. Google Forms is a great solution.

**Comment by rosariorobinson** [comment]
Could we perhaps have a template?

**Comment by vubo** [comment]
@rosariorobinson here is it: https://docs.google.com/forms/d/1IkUzcqL6OB1PsrT0bCdDKTnPH_F3EBwnuCMcu-LNv3g/edit

Is it ok? Can you edit it?

**Comment by tapasweni-pathak** [comment]
We can repoen it, if needed.
