### ISSUE TITLE
Move get_results_list to BasePage from POM pages

### ISSUE THREAD

**Issue by Monal5031** [systers/vms#823]
## Description
`get_results_list` in POM pages doesn't depend on anything in its pages and is yet defined in each POM page. Thus to reduce code duplication it should be moved to BasePage of POM and made static.

## Mocks
N/A

### Update [Required]
- [ ] Move `get_results_list` from pom pages to basepage

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 mins.

**Comment by SukhnandanMalhotra** [comment]
Hey, can I work on this issue?

**Comment by Monal5031** [comment]
Sure @SukhnandanMalhotra go ahead :+1: Make sure you know what exactly needs to be done and introduce yourself on slack and ask questions on slack if needed. :)

**Comment by SukhnandanMalhotra** [comment]
Please share the invite link for slack. The one mentioned is giving a 404 page.

**Comment by Monal5031** [comment]
@SukhnandanMalhotra Did you join the slack or still need the link?
