### ISSUE TITLE
[Outreachy] Intrested in contributing

### ISSUE THREAD

**Issue by Vishnupriya1507** [systers/vms#869]
I'm Vishnupriya Srivastava, from India.I am completing my graduation from Bits Pilani,India.I am a backend developer.I've done projects for my college using django framework,recently i worked with django channels creating a multichat gaming website.
I would like to contribute to your project either by participating in outreachy or gsoc.
I read about this projects from last year's .

Please guide to on getting started

**Comment by Monal5031** [comment]
@Vishnupriya1507 It'd be great if you could introduce yourself in the slack's intro channel. We'd better gudie you there.

**Comment by Monal5031** [comment]
@Vishnupriya1507 It'd be great if you could introduce yourself in the slack's intro channel. We'd able to better guide you there.

**Comment by anjali-dhanuka** [comment]
@Vishnupriya1507 Please join the AMA sessions, I can guide you in stuff

**Comment by anjali-dhanuka** [comment]
closing this @Vishnupriya1507
