### ISSUE TITLE
Changing documentation to run the project

### ISSUE THREAD

**Issue by Tlazypanda** [systers/vms#877]
## Description
The following command throws an error because it is missing initialization of an extra field in the model which cant be set as null.
`insert into organization_organization values (1, 'Google');`

## Mocks
![screenshot from 2018-11-10 02-54-24](https://user-images.githubusercontent.com/33183263/48301639-f824c280-e516-11e8-9c12-22a06bb47555.png)

### Update [Required]
- [ ] Update documentation to support the following change.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Monal5031** [comment]
GFI @Tlazypanda also mention the field you are adding in your commit message. And update docs accordingly with the fields
PS: these kind of issues should not take more than 10  mins :stuck_out_tongue:
