### ISSUE TITLE
inconsistency between shift time and volunteer shift time

### ISSUE THREAD

**Issue by jayesh92** [systers/vms#88]
If an admin has assigned a shift from `0900hrs to 1500hrs`, volunteer is able to log hours in a shift from `1800hrs to 1830hrs` also. Should this be allowed ?
Tests pass with this use case

**Comment by tapasweni-pathak** [comment]
I do not see a point why it should be allowed. What do you think @vubo ?

**Comment by vubo** [comment]
I'm not sure. I think we should ask @rosariorobinson

**Comment by rosariorobinson** [comment]
To @jayesh92 question, no this should not be allowed. Volunteers should only be able to log hours that admin/manager has assigned for availability. We have to manage what volunteers can sign up for. Good catch.

**Comment by willingc** [comment]
@rosariorobinson Is there ever a case where there are multiple admins for a shift? For example, you are admin for 0900 to 1500 and I am admin for 1200 to 2000 giving a total time needing staffing. Is this a possible use case?

**Comment by smarshy** [comment]
@tapasweni-pathak _Status update :_ This behaviour has been changed and as of now, a volunteer is not allowed to log hours which fall outside the assigned working hours.
