### ISSUE TITLE
Change documentation to support current version of Django

### ISSUE THREAD

**Issue by Tlazypanda** [systers/vms#881]
## Description
For the current version of Django . the following commands are outdated and are now replaced by a single command of migrate.They need to be removed from the documentation to allow users to install the app with ease.
`python manage.py sqlall app_name_here`
`python manage.py syncdb`

## Mocks
![screenshot from 2018-11-11 07-15-20](https://user-images.githubusercontent.com/33183263/48308093-c0069980-e581-11e8-9246-9a92c2816839.png)

### Update [Required]
- [ ] Documentation needs to remove these commands.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Monal5031** [comment]
GFI @Tlazypanda :+1: I think this got missed out somewhere during the change, anyways nice catch :tada:

**Comment by Monal5031** [comment]
Ping @Tlazypanda still on it?

**Comment by Tlazypanda** [comment]
Yup
