### ISSUE TITLE
Updating Readme with the Installation steps through virtual environment.

### ISSUE THREAD

**Issue by muskan6769** [systers/vms#882]
## Description
As a developer,
I need to add Installation steps through virtual environment as the installation steps through docker as mentioned in the README are using python 2.7 instead of python 3.6,

### Update [Required]
- [ ] Installation steps through virtual environment should be added in README.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by Monal5031** [comment]
You are going to change the link in readme to installation setup present in aut_docs or write a new one? @muskan6769

**Comment by muskan6769** [comment]
@Monal5031 There is already a link to installation guide that is through the virtual box and vargant. So I just want to add another link for easy installation using the virtual environment for the linux users.

**Comment by Monal5031** [comment]
Dont add but Replace the existing link, since vagrant and virtual box one needs to be updated.
GFI :+1: send a PR
