### ISSUE TITLE
Updating the installation guide with ``` python manage.py cities_light``` command.

### ISSUE THREAD

**Issue by muskan6769** [systers/vms#888]
## Description
I need to add ``` python manage.py cities_light``` command to the installation guide for installation of django cities_light so that we can get a list of countries,state and cities while signing up

### Update [Required]
- [ ] Updating in command in installation guide.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by Monal5031** [comment]
Valid issue, GFI if you want 👍

**Comment by agarwalrounak** [comment]
@Monal5031 I will work on it.

**Comment by Monal5031** [comment]
go ahead @agarwalrounak
