### ISSUE TITLE
Change psycopg2 to version 2.7.4 

### ISSUE THREAD

**Issue by abhishekspeer** [systers/vms#895]
## Description
As a developer,
I need to upgrade `psycopg2` from its current version `2.7.3` to `2.7.4`,
so that I can accomplish a hassle free procedure while setting up the project locally.

## Mocks
NA

### Update [Required]
- [x] Change psycopg2 from its current version 2.7.3 to 2.7.4 in requirements.txt.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Monal5031** [comment]
In future, we might move to psycopg2-binary not beneficial for now
