### ISSUE TITLE
Error while including comma in address field while creating new event.

### ISSUE THREAD

**Issue by 01shobitha** [systers/vms#897]
## Description
There is an error while including comma in the address field while creating an event. I need to modify the RegexValidator to rectify the error.

## Mocks
![screenshot](https://user-images.githubusercontent.com/32234630/50733307-4241c180-11b1-11e9-8959-7456412d89f6.png)

### Update [Required]
- [ ] Update the RegexValidator in address field in the model- Event.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by Monal5031** [comment]
@01shobitha Yeah I guess it is a valid issue, as someone may have additional details in their address like `flat number, block number...`
Please check if this error is in other apps too which have the address field in their models.

**Comment by 01shobitha** [comment]
@Monal5031 Sure, I will check the other apps too for this bug. Thank you :)

**Comment by LordGameleo** [comment]
Is this issue open??
