### ISSUE TITLE
Sample Committee Volunteer Application

### ISSUE THREAD

**Issue by rosariorobinson** [systers/vms#9]
Here is sample of the GHC committee volunteer application from last year. The GHC Committee would be a volunteer job.

![image](https://cloud.githubusercontent.com/assets/63290/5868721/7e2d6040-a262-11e4-81db-fe7a57c9a343.png)

![image](https://cloud.githubusercontent.com/assets/63290/5868725/96703182-a262-11e4-9f07-b1c0f24dd8b0.png)

![image](https://cloud.githubusercontent.com/assets/63290/5868731/a5473dfe-a262-11e4-876e-db8eadea90e5.png)

![image](https://cloud.githubusercontent.com/assets/63290/5868737/b80f372a-a262-11e4-9f58-1e786fe7abd9.png)

![image](https://cloud.githubusercontent.com/assets/63290/5868745/c5f2a11a-a262-11e4-9a57-5c19e5656952.png)

**Comment by vubo** [comment]
@rosariorobinson it's still relevant? In wich form it should be realized? Perhaps as a volunteer job with a form to fill? Thank you!

**Comment by rosariorobinson** [comment]
Good point. Not relevant now because we have so many job opportunities. Your suggestion to volunteer job with a form to fill is good.

**Comment by willingc** [comment]
@rosariorobinson @vubo From the earlier comments, I think that we can close out this issue.
