### ISSUE TITLE
end time should be less than start time

### ISSUE THREAD

**Issue by jayesh92** [systers/vms#91]
While testing the shift hours view, I can enter end time less than start time. This should not be allowed and a corresponding check should be added. Also, I think same is the case with all time fields.

**Comment by vubo** [comment]
@jayesh92 here is a comment from @Nerdylicious: https://github.com/systers/vms/blob/develop/vms/shift/forms.py#L27

**Comment by jayesh92** [comment]
@vubo then shouldn't a date-time field make more sense than only time field ?

**Comment by vubo** [comment]
@jayesh92 I'm not sure. A date-field can also be confusing. We need feedback from users to understand.

**Comment by jayesh92** [comment]
@vubo not date field, I'm suggesting a date-time field which contains both date and time and also since shift model contains a date, start_time and end_time so I don't think a shift extending beyond a day makes sense.

**Comment by willingc** [comment]
@vubo Please check with @rosariorobinson about her preference. Dates and times can be a pain on many projects. It would be good to go through the use cases with her.

1. Separate date fields (start and end) with separate time fields (start and end) - I could see some volunteers that are organizing multiday events have shifts that span multiple days.

2. Whichever implementation makes sense there should be appropriate checks done for reasonable inputs?

3. I haven't looked at it yet, but are we handling time zones or are all events in local time? Local time may be a reasonable assumption for on-site events. For use cases, such as a sprint where volunteers may be remote, the volunteer's time zone may be more useful for the volunteer.

cc/@tapasweni @jayesh92

**Comment by vubo** [comment]
@rosariorobinson now we can create and edit only a one-day shift. Should it be so?

![image](https://cloud.githubusercontent.com/assets/7673323/8895313/00f63bbe-33d6-11e5-8ebc-7402a67ce8bb.png)

@willingc 3. We don't handle time zones.

**Comment by smarshy** [comment]
@tapasweni-pathak This seems to be changed and resolved. Now there are checks to ensure end time is greater than start time
