### ISSUE TITLE
Some model migrations are missing

### ISSUE THREAD

**Issue by marylicious** [systers/vms#913]
## Description
When the command `python manage.py migrate` is used, it only migrates  admin, auth, cities_light, contenttypes and sessions. 

Use the command `python manage.py makemigrations <app>` to create the missing migrations.

### Update 
- [ ] Update migrations to handle properly all the models

## Definition of Done
- [ ]  Create migration of `administrator`
- [ ]  Create migration of `organization`
- [ ]  Create migration of `event`
- [ ]  Create migration of `job`
- [ ]  Create migration of `shift`
- [ ]  Create migration of `volunteer`
- [ ] Approval by 1 mentor.

## Estimation
less than an hour

**Comment by marylicious** [comment]
I'm not sure if this is a proper issue or I did something wrong and it's only happening on my machine, but I lost time thinking it was some other thing. So, having all the migrations can make everything more beginner-friendly.

**Comment by aayush-05** [comment]
`makemigrations` is basically used to generate out sql commands, while `migrate` command is used to apply those generated commands to the database.
So, running just the `migrate` command does the work of both of them. The installation guide mentions the migrations for some particular apps, may be because those are the only ones required (not sure).

**Comment by MarkoShiva** [comment]
> I'm not sure if this is a proper issue or I did something wrong and it's only happening on my machine, but I lost time thinking it was some other thing. So, having all the migrations can make everything more beginner-friendly.

In case of this project look like they are a bit against adding migrations to the git. Not sure why as that is part that is needed when you want to setup project.
So however if you use `python manage.py migrate --noinput --traceback --settings=vms.settings` you stay without migrations. So I'm not sure that PR will be accepted.

**Comment by marylicious** [comment]
> > I'm not sure if this is a proper issue or I did something wrong and it's only happening on my machine, but I lost time thinking it was some other thing. So, having all the migrations can make everything more beginner-friendly.
> 
> In case of this project look like they are a bit against adding migrations to the git. Not sure why as that is part that is needed when you want to setup project.
> So however if you use `python manage.py migrate --noinput --traceback --settings=vms.settings` you stay without migrations. So I'm not sure that PR will be accepted.

ok thank you I will close it
