### ISSUE TITLE
A problem after updating Django

### ISSUE THREAD

**Issue by vubo** [systers/vms#92]
After updating Django I can run
```
python manage.py runserver [::]:8000
```
but not 
```
python manage.py test
```
I get an error:
```
django.db.utils.ProgrammingError: relation "auth_user" does not exist
```

@tapasweni-pathak @jayesh92 do you have this problem with Django 1.8? Can you run tests?

**Comment by willingc** [comment]
@vubo You may need to run `python manage.py makemigrations` before running `python manage.py test`

**Comment by tapasweni-pathak** [comment]
@vubo Try [this](http://stackoverflow.com/questions/29689365/auth-user-error-with-django-1-8-and-syncdb-migrate).

**Comment by vubo** [comment]
@willingc @tapasweni-pathak thank you! I did it, but it did not help. 

I installed again Django 1.7, made all migrations and updated to Django 1.8. After that it finally works. Maybe it can be useful to someone.
