### ISSUE TITLE
Check error handling when a volunteer tries to sign up before an admin

### ISSUE THREAD

**Issue by willingc** [systers/vms#95]
If a volunteer user tries to create an account before an admin creates an account, the vms displays an error message. The message does not explain why the system is not creating the account. An edge case but likely one we should cover.

**Comment by shoaib1987** [comment]
@willingc Will you please give steps to generate an error message you mentioned in the description? I was able to sign up as a user without creating an administrator account(administrator table is empty).

**Comment by willingc** [comment]
@shoaib1987 Likely this was fixed between when the issue was filed and now. You followed the steps that I had when the error occurred. Thanks for checking into this issue :cake: I'm going to close it at this time.
