### ISSUE TITLE
Make menu items more user friendly (Settings, Create Admin Account)

### ISSUE THREAD

**Issue by willingc** [systers/vms#97]
After logging in as an admin, I see these menu choices:
<img width="1244" alt="screen shot 2015-07-26 at 4 48 10 pm" src="https://cloud.githubusercontent.com/assets/2680980/8896607/4fc42c08-33b6-11e5-82c5-b085767955f3.png">

I would expect that I could edit my settings password, email, name, etc. from a menu item where "Create Admin Account" is.

"Settings" is a little vague since it implies that I can adjust my account settings which I don't believe that I can do from that menu.

This doesn't need to be addressed now. I just want an issue open so that I will remember for the future ;)

**Comment by vubo** [comment]
@willingc I totally agree. Maybe we should call this menu item simply "Events"?

**Comment by willingc** [comment]
Let's change it to Events for now.

It probably makes sense to do a user interface planning meeting after the GSoC demo to look at with the users (Rose and others) at the overall labeling of menus.

**Comment by willingc** [comment]
Closing this issue since #125 addresses the menu. We can always reopen if additional feedback from the demo warrants it.
